### ISSUE TITLE
displayName contains nonstandard characters

### ISSUE THREAD

**Issue by xtrium-lnx** [Microsoft/vswhere#115]
Hi,

On my computer, with a french version of VS, the locator (tagged: "Visual Studio Locator version 2.1.3 [query version 1.12.134.36697]") returns the following string for displayName :

    displayName: Visual Studio Community�2017

(the ? being a 0xFF)

Since the VSCode CMake extension relies on this, it breaks pretty much everything on my builds with VS2017 right now.

**Comment by heaths** [comment]
It's likely an encoding issue. Please see https://github.com/Microsoft/vswhere/wiki/Encoding. Your system encoding should correspond to your UI language, or you need to make sure your shell environment corresponds at least.

**Comment by heaths** [comment]
I can also confirm that the display strings for several editions do use something other than a space, though I can't reproduce it causing a problem using the fr-FR locale even with console code page 437 (default for en-US as well). What code page is your console set to? (You can use `chcp` to display it.)

**Comment by heaths** [comment]
For what it's worth, the source character is actually extended ASCII character 0xC2 (194), which with an 850 OEM code page is ending up as 0xFF (255). The UTF-8 and Windows-1252 code pages do convert this to a supported space character.

I've filed a bug internally to fix this (if possible) in the product definitions (i.e. not a vswhere bug), but hopefully changing your code page helps.
