### ISSUE TITLE
Cannot find preview versions

### ISSUE THREAD

**Issue by sebastienros** [Microsoft/vswhere#121]
I tried with the latest release from the release page and got the same issue.

`Visual Studio Locator version 2.2.11+gf1a9c6c78d [query version 1.15.103.11219]`

I only have a single Preview version 

![image](https://user-images.githubusercontent.com/1165805/33506168-7d499e78-d6a3-11e7-8aba-393710667e8f.png)

```
C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere.exe
Visual Studio Locator version 2.2.11+gf1a9c6c78d [query version 1.15.103.11219]
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Program Files (x86)\Microsoft Visual Studio\Installer>
```

**Comment by heaths** [comment]
If you look at the usage (`'?`) it shows you have to use `-prerelease` to see prerelease versions. This was a requested breaking change from 1.x that lead to the 2.x versions.

**Comment by vvuk** [comment]
Hmm, I'm not sure -prerelease is actually working as intended:

Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.17.1176.60362]

```
$ vswhere.exe  -property installationPath -prerelease
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional

$ vswhere.exe  -property installationPath -prerelease -all
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional
```

The preview version runs just fine, so I'm not sure it's due to it being "incomplete and may not launch", as -all implies

**Comment by heaths** [comment]
Yes, it probably means it's incomplete. If you use the [VSSetup](https://github.com/Microsoft/vssetup.powershell) module it can give you specifics in the `State` property.

**Comment by vvuk** [comment]
Indeed you're right -- my desktop didn't actually reboot while I went to get a coffee, it just dropped back out to the login screen somehow.  Sorry for the noise!
