### ISSUE TITLE
Can't detect VS 2017 build tools (15.5.2), empty output

### ISSUE THREAD

**Issue by rhyskoedijk** [Microsoft/vswhere#125]
I've read every thread on similar issues, but can't for the life of me find a solution to this problem. 

After upgrading to v15.5.2 of the VS 2017 build tools, vswhere outputs nothing.
Prior to the upgrade, TFS was able to detect MSBuild 15, but not afterwards.
I have since completely uninstalled all VS 2017 tooling and reinstalled them, but no instance of vshwere.exe (tried TFS [v1.1] and VS/Installer [v2.2]) will show the installed instances.

I can see the installed tools in windows explorer, but vswhere will not find them,

![before_working](https://user-images.githubusercontent.com/123988/34506163-3f52a640-f08f-11e7-9b2f-16b90943df87.png)
![after_failing](https://user-images.githubusercontent.com/123988/34506162-3f060c2c-f08f-11e7-8512-64ee3b6b0460.png)
![vswhere](https://user-images.githubusercontent.com/123988/34506164-3fa0b9e8-f08f-11e7-94ab-28ab2b6460a4.PNG)

Can somebody advise what is missing here, it is doing my head in.
Thanks,

**Comment by rhyskoedijk** [comment]
Also note that when I reinstalled the build tools (after this issue started happening), I reinstalled them to C:\, where previously they were installed to E:\

The change in drive letter shouldn't be an issue, as it was broken before I decided to uninstall/reinstall.

**Comment by heaths** [comment]
_vswhere_ doesn't show the query API version, which means it's no longer installed. Please run https://aka.ms/vscollect.exe and attach %TEMP%\vslogs.zip when it finishes to diagnose why.

In the meantime, download and install (just double-click to install) https://download.visualstudio.microsoft.com/download/pr/100390094/d68d54e233c956ff79799fdf63753c54/Microsoft.VisualStudio.Setup.Configuration.msi, which is the latest release of the query API.

**Comment by BlackFrog1** [comment]
I am having the same issue where it's not detecting MSBuild Engine 15.1.1012.6693.  
![vswhere result](https://user-images.githubusercontent.com/550820/34589243-199a2096-f17e-11e7-9215-a16fe3d5e4d8.png)

I ran [https://aka.ms/vscollect.exe](https://aka.ms/vscollect.exe), but the %TEMP%\vslogs.zip is 43 MB large.  There is a limit of 10 MB attachment.

Where can I upload the vslogs.zip for you to access?

**Comment by heaths** [comment]
OneDrive or any other cloud drive is a good place.

**Comment by rhyskoedijk** [comment]
@heaths, thanks.

I've installed the VS Setup Configuration, but it still doesn't show the query version in the console output. My vslogs.zip is also quite large, is there something specific I can extract from it or do you literary need the full zip.

**Comment by heaths** [comment]
Please post the whole thing. There are various pieces I may need and it will be faster than going back and forth. If you'd rather secure it for just me, I can encrypt my email for you via PGP/GPG if you share your public key.

**Comment by rhyskoedijk** [comment]
https://1drv.ms/u/s!Apd2_IzUpiILbVWub6IpW1X9C94

**Comment by heaths** [comment]
I'm not sure why, but I can't seem to access that link. I wonder if OneDrive now tries to open ZIPs and is maybe timing out since it's big? I really have no idea. Is it possible to stick it in a folder by itself and just share the folder?

**Comment by rhyskoedijk** [comment]
https://1drv.ms/f/s!Apd2_IzUpiILblLKcxrUP4Kg-n8

**Comment by rhyskoedijk** [comment]
Uploaded. does it work better now?

**Comment by rhyskoedijk** [comment]
Hi, any update on this? Did you need any further information? thanks

**Comment by heaths** [comment]
I took a look at the files and all information shows that the query API should be present. Do you have DLLs in %ProgramData%\Microosoft\VisualStudio\Setup (2 subdirectories)? If so, from an elevated command prompt please try running _regsrv32.exe_ on them to register them again and try again. Let me know if that works. I'm not sure how they'd get deregistered since we removed the old version and installed the newer one that would've registered them.

**Comment by rhyskoedijk** [comment]
Running regsrv32.exe on the two .dll and rebooting now shows the query version. However, I still don't see my build tools installation. I reinstalled the build tools again hoping the query API fix might have changed things, but it hasn't.

![capture](https://user-images.githubusercontent.com/123988/34901755-c1839a52-f873-11e7-8fb3-2043463de801.PNG)

It looks like I'm now in the same boat as @BlackFrog1.
Any pointers on how I can diagnose why the installation isn't showing up now?

**Comment by heaths** [comment]
Build Tools is not selected by default. See #22. In short, pass `-products *`. `-?` shows more options, such as `-prerelease` was a requested breaking change that warranted the jump to v2 a while back.

**Comment by rhyskoedijk** [comment]
`-product *` flag work great. Thanks for your help.
