### ISSUE TITLE
VSTest instructions do not work for VS Test Agent 2017

### ISSUE THREAD

**Issue by jnm2** [Microsoft/vswhere#126]
We have the VS2017 build tools and test agent (15.5.3) installed on a build server rather than full VS.

The -requires string `Microsoft.VisualStudio.PackageGroup.TestTools.Core` ([which the wiki recommends](https://github.com/Microsoft/vswhere/wiki/Find-VSTest)) works for full VS but apparently not for VS Test Agent.

`vstest.console.exe` is clearly present at both `C:\Program Files (x86)\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\CommonExtensions\Microsoft\TestWindow` and `C:\Program Files (x86)\Microsoft Visual Studio\2017\TestAgent\Common7\IDE\Extensions\TestPlatform`.

Removing the -requires and running `vswhere -latest -products * -property installationPath` works great, but I'd rather there wasn't the possibility of it resolving to an installation that was lacking VSTest. How can I determine which -requires string to use for the test agent installation?

**Comment by heaths** [comment]
@davsterl I've seen this problem for a few common components like this. Could we add a common parent without adverse effects to selection?

@jnm2 I could consider adding something like `-requiresany` but don't have a lot of time right now. You're free to submit a PR if you want it sooner than later; otherwise, 2 invocations of _vswhere_ will be necessary.

**Comment by jnm2** [comment]
The best outcome is for there to be a single simple ID that means "this installation contains %InstallDir%\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" for the purposes of those of us who write build scripts. If something happens to disillusion that hope, I'll consider doing a PR.

**Comment by Davsterl** [comment]
Right now they do contain two unique sets of packages, so it would require some real untangling to split the graph such that a packagegroup is shared between the two with just those bits. 

I'll talk to some folks on this side to see how feasible it is as I don't know what the contents of all those packages are.

**Comment by jnm2** [comment]
@heaths Thanks for doing that.

The wiki should probably be updated. The VSTest page, for instance, says:

> Starting with version 1.0.40, you can easily find the root path of the latest instance of VS that contains the tools. Note that we generally recommend using package IDs with "Workload" or "Component" in the name, but in this case both "Microsoft.VisualStudio.Workload.ManagedDesktop" and "Microsoft.VisualStudio.Workload.Web" install the requires test tools and vswhere does not support OR selection.

@Davsterl I would still like to find out whether a change can be made so that a single package ID can signal the presence of vstest.console.exe. Should I file an issue through the VS feedback tool?

**Comment by Davsterl** [comment]
@jnm2 That would be great! I'll look out for it and use it to track it internally.

**Comment by heaths** [comment]
Thanks, @jnm2. I will update the wiki.

**Comment by jnm2** [comment]
@Davsterl Thank you! I'll link it here for future readers: https://developercommunity.visualstudio.com/content/problem/183405/there-is-no-installer-package-id-which-signals-the.html

**Comment by jnm2** [comment]
Looping back from @ganesp's response, the ID to use for VSTest console which works in all types of installation is this: `Microsoft.VisualStudio.TestTools.TestPlatform.V1.CLI`

@heaths Instead of recommending `-requires Microsoft.VisualStudio.Workload.ManagedDesktop Microsoft.VisualStudio.Workload.Web -requiresAny` on the wiki instructions for locating VSTest, does it make sense to recommend `-requires Microsoft.VisualStudio.TestTools.TestPlatform.V1.CLI` in all cases instead?

**Comment by jnm2** [comment]
@heaths In addition, there's a chance that people looking to resolve the installation path of VSTest should really be using the [Microsoft.TestPlatform NuGet package](https://www.nuget.org/packages/Microsoft.TestPlatform/) (currently preview-only) [according to](https://developercommunity.visualstudio.com/solutions/185103/view.html) @PBoraMSFT. This should probably be suggested on the wiki too, since not having such a package is likely why people are trying to locate VSTest in their scripts in the first place. What do you think?

**Comment by heaths** [comment]
We do not document package IDs because they can and do change. Only product, workload, and component IDs.

**Comment by jnm2** [comment]
Hmm, so the best future-proof solution for locating vstest.console.exe is `-requires Microsoft.VisualStudio.Workload.ManagedDesktop Microsoft.VisualStudio.Workload.Web -requiresAny`? It's sad to hear that there isn't a stable vstest-specific ID since that is 1:1 with what I *actually* care about; the workload IDs are incidental implementation details. I'd rather talk about what I want than have to always leave a comment explaining why the magic works.

**Comment by johnaceous** [comment]
> We do not document package IDs because they can and do change. Only product, workload, and component IDs.

@heaths Hmm, in 2021, the workload appears to have changed, while the package id is still the same. I just installed VS 2019 Enterprise with only the "ASP.NET and web development" workload checked. VSSetup reports only the following two workloads:

```
Name: Visual Studio Enterprise 2019

Type      Id
----      --
Workload  Microsoft.VisualStudio.Workload.CoreEditor
Workload  Microsoft.VisualStudio.Workload.NetWeb
```

Consequently, the query from the wiki fails to find anything:
```
vswhere -latest -products * -requires Microsoft.VisualStudio.Workload.ManagedDesktop Microsoft.VisualStudio.Workload.Web -requiresAny -property installationPath
```

Yet changing that to `Microsoft.VisualStudio.Workload.NetWeb` finds the appropriate install. I cannot find any mention of `Workload.Web` in [the Visual Studio Docs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2019).

Perhaps I should switch to `-requires Microsoft.VisualStudio.TestTools.TestPlatform.V1.CLI` which at this point has proven more stable than the workload?

**Comment by heaths** [comment]
I've passed this feedback along. For now, yes, do what works best for your scenario. This is unfortunate, but many package IDs changes with far more frequency. That doesn't mean they all do.
