### ISSUE TITLE
Obtain workloads/components associated with an install

### ISSUE THREAD

**Issue by ewanharris** [Microsoft/vswhere#128]
When using vswhere programmatically and presenting that information to an end-user I would find it useful to have a list of packages so that if my `-requires foo bar` call returns no VS instances because the user hasn't installed package bar then I'm able to find out what's missing and display some information to a user on how to remedy the situation.

I guess this falls into the realm of two feature requests

- Implement a flag to return the missing workload/components when the `-requires` flag is used, probably best to keep this an opt-in due to making a change in the programs behaviour
- Add a workload/component field to the object representing a Visual Studio instance, again I imagine this might want to be hidden behind a flag as this would probably increase the amount of output significantly

I'd be happy to contribute this if you like the request

**Comment by heaths** [comment]
This information is already available from the https://github.com/Microsoft/vssetup.powershell module. That is more for exploratory purposes and I don't want to turn vswhere into that project. I might be open to an *opt-in* switch to display missing workloads or components for each instance, but it really depends on how it's implemented and what the switch is named. It really needs to infer that any instances returned (matching whatever products are specified, including the defaults) should not be used.

Still, I'd recommend using the `VSSetup` module (in PowerShell, just `install-module -scope currentuser vssetup -force`) for this kind of work.

**Comment by heaths** [comment]
With no progress on this request and because I think it would cause a regression in many output parsers, we recommend instead you use the `VSSetup` module.
