### ISSUE TITLE
Can not detect `Microsoft Visual C++ Build Tools 2015`

### ISSUE THREAD

**Issue by DmitrySokolov** [Microsoft/vswhere#129]
1) Microsoft Visual C++ Build Tools 2015 downloaded from http://landinghub.visualstudio.com/visual-cpp-build-tools
2) vswhere 2.3.1+g0cacce77a7

run `vswhere.exe -prerelease -latest -property installationPath`

actual: outputs nothing

expected: path to the installed MSVC build tools

**Comment by KindDragon** [comment]
You forgot `-products *`
```
-products arg  Finds instances matching the given product IDs, defaults to Community, 
               Professional and Enterprise. "*" searches for all installed product IDs.
```

**Comment by DmitrySokolov** [comment]
`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`

outputs nothing

**Comment by heaths** [comment]
This tool is for Visual Studio 2017 and newer. The backward compatibility detection was added only for Visual Studio products. Registry-based detection of older Build Tools SKUs is possible without this utility.

**Comment by alexkaratarakis** [comment]
@DmitrySokolov 
This script from vcpkg might help you:
https://github.com/Microsoft/vcpkg/blob/master/scripts/findVisualStudioInstallationInstances.ps1#L35
