### ISSUE TITLE
vswhere doesn't find "Visual C++ for Python"

### ISSUE THREAD

**Issue by efahl** [Microsoft/vswhere#134]
Attempting to find all cl.exe locations on one of our development machines shows all but the 9.0 installation.

> p:/installers/SCons/vswhere.exe -all -legacy -property installationPath
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
C:\Program Files (x86)\Microsoft Visual Studio 14.0\
c:\Program Files (x86)\Microsoft Visual Studio 10.0\

Here's what cygwin find shows me:

> find c:/ -iname cl.exe
c:/Program Files (x86)/Common Files/Microsoft/Visual C++ for Python/9.0/VC/bin/amd64/cl.exe
c:/Program Files (x86)/Common Files/Microsoft/Visual C++ for Python/9.0/VC/bin/cl.exe
c:/Program Files (x86)/Common Files/Microsoft/Visual C++ for Python/9.0/VC/bin/x86_amd64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX64/x64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX64/x86/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x86/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/Hostx86/x86/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/amd64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_arm/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64_x86/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_arm/cl.exe

**Comment by heaths** [comment]
_vswhere_ finds installation roots. From there you have to construct the path or do a recursive search. It does not scan the hard drive or search %PATH%. It's not intended to. The README and the wiki have more information.

**Comment by bdbaddog** [comment]
The VC for Python can be found in the registry.

        (SCons.Util.HKEY_CURRENT_USER, r'Microsoft\DevDiv\VCForPython\9.0\installdir',),

Can vswhere be updated to check that path as well?

**Comment by heaths** [comment]
That is outside the scope of vswhere. Our wiki contains more information, including a newly release FAQ and an example for finding VC as also recommended by the VC team. Registry lookups are not supported since they can only point to a single instance.

**Comment by bdbaddog** [comment]
Your code does use registry lookups to find legacy installs currently... 
Or am I mistaken?

https://github.com/Microsoft/vswhere/blob/develop/src/vswhere.lib/LegacyProvider.h#L17

And the list of searched legacy versions:

https://github.com/Microsoft/vswhere/blob/develop/src/vswhere.lib/InstanceSelector.cpp#L125

Looks like it's hardcoded to only look for legacy versions 10.0, 11.0, 12.0, 14.0

Can you point to a scope statement which specifies which versions of visual studio (legacy) are meant to be supported?

**Comment by efahl** [comment]
Ok, I'm still a bit tentative here, so correct my assumptions:

1) vswhere is only ever going to locate packages that are "proper" VS installations, i.e., those that contain devenv.exe somewhere.

2) Since "Visual C++ for Python" is sort of a hacked up partial installation, vswhere will never be able to detect it, and we'll have to fall back to some other method instead (as Bill suggests, just poke the registry).

**Comment by heaths** [comment]
@efahl, no, _vswhere_ locations installation paths (roots) of Visual Studio (by default) or related SKUs (if you use `-products` as documented in the usage and wiki). You can dictate what workloads and/or components you require of an instance for it to be returned. It does not locate those components (components often have many EXEs, or none at all but are an aggregation). From the installation root, most EXE paths are in a fixed path. MSBuild and VC tool chains are an exception, and our wiki has examples of how to find them.

@bdbaddog registry is only supported for legacy detection. We do not support it for Visual Studio 2017. The fact that I implemented it and the lines of code you referenced exist are proof it's supported but, as with the point of _vswhere_ described above, only finds the root installation path.

**Comment by bdbaddog** [comment]
@heaths Sure. the 9.0 for python is a legacy. SCons (scons.org) supports back to Visual Studio 6.0 currently. I was just hoping we could use vswhere to support all versions of Visual Studio we support and drop our registry inspection code all together.  Providing partial information on older versions would be of use for your user community..   Would  a pull request be accepted?

**Comment by heaths** [comment]
Finding specific tool locations is outside the scope of _vswhere_. As previously state, it is for finding the root installation path only.

**Comment by bdbaddog** [comment]
Yes. I'm talking about a patch to find root install path of older versions of visual studio (older than 2010)

**Comment by heaths** [comment]
At the time legacy support was added, versions older than Visual Studio 2010 are not supported and we made a decision not to support them in _vswhere_. You will need to continue using legacy registry detection for older, unsupported versions of Visual Studio,
