### ISSUE TITLE
Find `tf.exe` example

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vswhere#136]
To find `tf.exe`, you can use:

```
function Find-VisualStudioTf {
    $ErrorActionPreference = 'Stop'

    $path = .\tools\vswhere -latest -products * -requires Microsoft.VisualStudio.TeamExplorer -property installationPath
    $path = join-path $path '\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\tf.exe'
    return $path
}
```

**Comment by heaths** [comment]
Thank you for the example.

**Comment by heaths** [comment]
Please see my reply on issue #157. Thank you for thinking of it, though.

**Comment by Indigo744** [comment]
For anyone coming here, you can use this simple one-liner:
```
"vswhere" -latest -products * -requires Microsoft.VisualStudio.TeamExplorer -find "**\Team Explorer\TF.exe"
```
Which output for me:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe
```

**Comment by icnocop** [comment]
@Indigo744 which version of vswhere are you using?

I'm using the one included in the Azure DevOps build agent `vsts-agent-win-x64-2.153.1.zip` and I get the following error:

```
Visual Studio Locator version 1.0.62
Copyright (C) Microsoft Corporation. All rights reserved.

Error 0x57: Unknown parameter: find
```

Thank you.

**Comment by heaths** [comment]
Find was introduced in a later version. I recommend pulling it from nuget.org or hosting the binary yourself so you can rely on what functionality was included.
