### ISSUE TITLE
 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by nguyenlaai9** [Microsoft/vswhere#139]
Command "C:\Users\Nguyen\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Nguyen\\AppData\\Local\\Temp\\pip-build-fqs8d29_\\pygraphviz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Nguyen\AppData\Local\Temp\pip-17tfsbtx-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Nguyen\AppData\Local\Temp\pip-build-fqs8d29_\pygraphviz\

please, can i hlep me !

**Comment by heaths** [comment]
You need to file a bug against whatever is wrapping vswhere, if this even has anything to do with vswhere.
