### ISSUE TITLE
Should -requires support multiple values in quotes?

### ISSUE THREAD

**Issue by sean-rose** [Microsoft/vswhere#141]
Running it like `vswhere -requires "X Y"` doesn't currently work, it has to be like `vswhere -requires X Y`. Is that intentional by design, or would a pull request adding support for quoted values be welcome?

I ran into this because [Cake's VSWhere add-in](https://cakebuild.net/dsl/vswhere/) currently puts quotes around the `-requires` value.

**Comment by heaths** [comment]
Quotes around arguments means to treat the arguments between quotes as a single argument. This is typical in any command line application on any platform I've used, and thus by design. I suggest you file a bug with Cake.
