### ISSUE TITLE
How to manually register the necessary COM entries for easy custom deployments?

### ISSUE THREAD

**Issue by AndrewJDR** [Microsoft/vswhere#143]
Hello,

With our VS deployments, to ease custom deployments of VS build tools, deploy to different/strange configurations (like Wine on linux), and also to simply understand how things work, we'd really prefer to just be able to copy a few directories, then make a couple of registry entries and be up and running like the old days.

With this new COM-based method of doing things, It sounds like this should still be possible, but I'll need to register some things with COM now rather than registry entries.

Is this process documented somewhere? If not, could it please please be done?

It would read something like this:
1. Copy the build tools to a target system, for e.g.:
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\
As well as your Window 10 kit here:
C:\Program Files (x86)\Windows Kits\10
2. Also copy the COM component to some-such directory and register it with `some command`.
3. Now run these COM related commands to register the presence of your VC tools and windows 10 kit:
```
etc
etc
```

(Note for most things I'm fine just doing the first step, but some tools like CMake actually use vswhere style techniques, and so they need these installation roots to be registered properly via com, or they won't be able to find the VC tools at all). Thanks!

**Comment by heaths** [comment]
That wasn't supported even in the "old days". A number of dependencies need to be properly installed. Without going through the installer - for any past or current version of Visual Studio and/or Build Tools - the product is not in a supported state.

Installing the product properly will install the query APIs. vswhere also supports the `-legacy` switch to use registry detection for Visual Studio 2010 through 2015 such that the query API does not have to be installed.

**Comment by AndrewJDR** [comment]
VS build tools 2017 msbuild/cl.exe/link.exe work just fine to build c/c++ projects after copying the relevant folders I mentioned to a machine and setting three or four environment variables related to the UniversalCRT. I have built many solutions and projects successfully this this way. I can ship a compiler toolchain as part of a private repository without needing to worry about deploying it everywhere. I run run msbuild/cl/link under wine. All of this works very nicely -- supported or not.

Where it breaks down is when tools like cmake become involved, as they depend upon these vswhere-like queries to find the VS installation, which depends on COM rather than at least allowing for simpler environment variable or registry entry overrides (i.e. "here's my VS installation, here's my Windows Kit" is all that is needed in many cases).

I guess I'll just switch to the ninja generator with cmake and set the INCLUDE/LIB environment variables (which does also work... I just tested it). Or I'll try to convince the cmake devs (and any other projects that will listen) to implement ways of circumventing the vswhere-like query system and by way of a set of environment variables or something so that msbuild can work again.

Sigh.

**Comment by heaths** [comment]
Environment variables will not be supported for reasons I've said in several other issues and in blog posts: they don't work with multi-instancing, same reason we no longer support registry-based detection. Anything using them would not be supported and subject to breaking changes.

Instead of trying to circumvent the system and deploy Build Tools on a way that has never been supported or checking in binaries to your repo (never recommended work DVCS like git), have to considered [containerizing](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container) the build (you can map the source directory - many projects including docker itself build this way) or using a [supported and easy to acquire] (https://blogs.msdn.microsoft.com/vcblog/2016/04/26/stay-up-to-date-with-the-visual-c-tools-on-nuget/) method of getting the toolset you want?

**Comment by AndrewJDR** [comment]
Is there any reason environment variable support cannot be offered when no installations are found via the COM method? This way, the multi-instances you mentioned could be located via the COM method if present, but if none are found via this method, environment variables would be used if available (for the single instance that they point to). This would keep things simpler for those that wish to opt out of the COM deployment type and use the same simple folder form of deployment that can already be used for all other build chains on the market (ninja+clang/gcc or cmake+clang/gcc).

The other options you mentioned are not things that I will consider because they are more complicated and resource consuming than what is necessary with any other compiler toolchain on the market. I didn't even say that I'm using git, so its binary file handling is not really germane here (for e.g. P4 handles binaries just fine, and large companies have been using it that way for years... they check in their build toolchains all the time. Alternatively, a fast shared network drive with all the compiler toolchains is another popular deployment technique I've seen).

**Comment by heaths** [comment]
The COM APIs provide more than just the installation path and many tools rely on this information to light up features based on what packages are installed, for example.

It doesn't change the fact that copying Visual Studio this way is not and has not been supported. You've reverse engineered part of what the installation is doing but there's more that goes on such as the [dockerfiles and integrations tests on this site](https://github.com/Microsoft/vswhere/tree/develop/docker) show.

**Comment by AndrewJDR** [comment]
Okay, I'm just going to move to cmake+ninja+cl.exe+link.exe for my buildchains, keeping msbuild.exe out of the equation entirely. This allows things to stay simple. In the future, I'll probably just move off of cl/link based buildchains altogether and settle on clang especially once they get their windows linker in order. I'm simply not interested in any kinds of deployments that depend upon COM and don't support straightforward environment variable based setups.
