### ISSUE TITLE
Using vsdevmd.bat environment variables in powershell

### ISSUE THREAD

**Issue by aslatter** [Microsoft/vswhere#150]
This wiki page recommends this snippet of powershell for loading `vsdevcmd` environment variables into a powershell script: https://github.com/Microsoft/vswhere/wiki/Start-Developer-Command-Prompt

``` powershell
$installationPath = vswhere.exe -prerelease -latest -property installationPath
if ($installationPath -and (test-path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
  & "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo && set" | foreach-object {
    $name, $value = $_ -split '=', 2
    set-content env:\"$name" $value
  }
}
```

This breaks for me for environment variables with newlines in them. It would be good if the wiki suggested a more robust technique.

Ultimately what I'm looking for is a supported way to script `msbuild` on a build-server - getting environment variables from `vsdevcmd.bat` is (as far as I know?) a required step in that process.

**Comment by heaths** [comment]
A more robust way is what we document at https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container: run vsdevcmd.bat then run powershell.exe (as shown in the example Dockerfile). This will simply inherit environment variables. Then whether you run powershell.exe first or not at all, running msbuild.exe will pick up those environment variables. You could also pass command line arguments to vsdevcmd.bat as documented in its own usage text to further customize the environment if so needed.

This is only an example of a basic set up for a docker container. Different build processes will have different requirements and workflows. It would not be possible to document all the various ways people might use this base setup and is outside the scope of this repository.

**Comment by clouds56** [comment]
As pwsh getting popular, is there any plan to add native support for PowerShell/pwsh? Say a command like `Init-VSDev` which would set all parameters for you.
Or at least `vswhere --vars` which output environment variables set by vsdevcmd.bat in some robust way.
It is annoying open another instance to access `msbuild/cl`

**Comment by clouds56** [comment]
try this:

```pwsh
if ($installationPath -and (Test-Path "$installationPath\Common7\Tools\vsdevcmd.bat")) {
  $json = $(& "${env:COMSPEC}" /s /c "`"$installationPath\Common7\Tools\vsdevcmd.bat`" -no_logo -arch=x64 && pwsh -Command `"Get-ChildItem env: | Select-Object Key,Value | ConvertTo-Json`"")
  if ($LASTEXITCODE -ne 0) {
    Write-Error "($LASTEXITCODE) $installationPath\Common7\Tools\vsdevcmd.bat: $json"
  } else {
    # Write-Host $json
    $($json | ConvertFrom-Json) | ForEach-Object {
      $k, $v = $_.Key, $_.Value
      Set-Content env:\"$k" "$v"
    }
  }
}
```

**Comment by heaths** [comment]
There's also the ]VSSetup](https://github.com/Microsoft/vssetup.powershell) module you can easily acquire using `Import-Module VSSetup` if you want to initialize a PowerShell environment.

As for a PowerShell-native developer command prompt, please open feedback for the Visual C++ team at https://developercommunity.visualstudio.com.
