### ISSUE TITLE
Best way to list available toolsets?

### ISSUE THREAD

**Issue by jclay** [Microsoft/vswhere#151]
Since VS 2017 can have multiple version of the MSVC compiler installed, what is the recommended way to list the installed version of the compilers?

https://blogs.msdn.microsoft.com/vcblog/2017/11/15/side-by-side-minor-version-msvc-toolsets-in-visual-studio-2017/

From this link, I'd like to start off vcvarsall with `-vcvars_ver=14.11` parameter, but I'd first like to make sure the target machine has the proper toolset installed.

**Comment by heaths** [comment]
That is outside the scope of vswhere, which finds the installation path (and other basic information) of a version of Visual Studio that meets basic requirements. If the Visual C++ team has created new components for each version of the toolset they support and that you can install based on what is available at https://aka.ms/vs/workloads, you can use https://github.com/Microsoft/vssetup.powershell to enumerate all the packages for an installation of Visual Studio which might suit your needs.
