### ISSUE TITLE
Tool does not work with VS 2017 Build Tools

### ISSUE THREAD

**Issue by andyfisher100** [Microsoft/vswhere#154]
After installing the VS 2017 build tools and using vswhere -all, nothing is returned.

This is a problem as VSWhere is used by the Azure DevOps "VSTest" build task. On our build machines we don't want to install the full IDE and only the build tools. This fails saying that visual studio, specifically the VS test console, is not installed but this is because VSwhere does not return any values. 

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestV2/versionfinder.ts#L114

**Comment by heaths** [comment]
That's not what `-all` does. You need to use `-products *`. See #8.

**Comment by andyfisher100** [comment]
Apologies, i assume this is an issue with the command line used by the test task then.

**Comment by heaths** [comment]
Yes. Please file a bug in the https://github.com/Microsoft/vsts-tasks project against the VSTestV2 task.

**Comment by vasokot** [comment]
i have same problem, but 

> vswhere -products *  did not help


`
C:\>vswhere -products *
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.17.1230.42073]
Copyright (C) Microsoft Corporation. All rights reserved.
`

**Comment by heaths** [comment]
If it's a prerelease, you also need `-prerelease`. If the install wasn't 100% successful, you'll also need `-all`. Put them all together anyway and you should see it.
