### ISSUE TITLE
Was vswhere.exe supposed to find a "Build tools" install? 

### ISSUE THREAD

**Issue by vasokot** [Microsoft/vswhere#155]
Installing VS Build Tools 15 2017 on windows-docker via command line
but vswhere.exe cannot detect it
`
C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere -products *
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.17.1230.42073]
Copyright (C) Microsoft Corporation. All rights reserved.
`
found only legacy versions
`
C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere -legacy
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.17.1230.42073]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: VisualStudio.14.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 14.0\
installationVersion: 14.0
`

Any ideas how fix it?

**Comment by vasokot** [comment]
yes! `vswhere -products * -all` work!
It means, install wasn't 100% successful ?

**Comment by heaths** [comment]
There might be a pending reboot. If you open the Visual Studio Installer, it should show a yellow exclamation mark with more information. If you're having trouble remedying that situation, please use the Feedback Tool button in the upper-right corner to report an issue with necessary logs.

As it is, it appears vswhere is working as designed so I'm closing this issue.
