### ISSUE TITLE
Wiki page to find VsixPublisher.exe

### ISSUE THREAD

**Issue by jnm2** [Microsoft/vswhere#157]
Would you be interested in adding this under the https://github.com/Microsoft/vswhere/wiki/Examples page?

```ps1
$visualStudioInstallation = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VSSDK -property installationPath

$vsixPublisher = Join-Path $visualStudioInstallation 'VSSDK\VisualStudioIntegration\Tools\Bin\VsixPublisher.exe'
& $vsixPublisher publish [...]
```

Reference:
https://docs.microsoft.com/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line
https://docs.microsoft.com/visualstudio/install/workload-component-id-vs-community#components-included-by-this-workload-17

**Comment by heaths** [comment]
Depending on your workload selection, there are dozens upon dozens of EXEs under the installation root directory. The wiki pages show a few of the more common ones primarily for the sake of showing how to use vswhere.exe more generally. It's not really tenable to have an example for nearly any and every EXE.

Fortunately, GitHub issue pages are indexed by search engines like Bing and Google, so if others are looking for an example, your example here will be helpful. Thank you!
