### ISSUE TITLE
Tool does not pick up VS 2019 preview

### ISSUE THREAD

**Issue by MatthewKaes** [Microsoft/vswhere#158]
I removed visual studio 2017 and installed visual studio 2019 preview. Now the following command returns nothing

```
vswhere.exe -property installationPath -all -requires Microsoft.Component.MSBuild -requires Component.MDD.Android -latest
```

I tried several configuration and couldn't get it to pick up 2019 preview, although I was able to get it to work with 2017 preview.

**Comment by heaths** [comment]
As noted in the `-?` usage text, you need to specify `-prerelease` for pre-releases. By default, the tool was designed to find all stable (released, launchable) instances. One must opt into pre-release and potentially unstable (requires reboots, installation errors, etc.) instances.
