### ISSUE TITLE
Find MSBuild 16 (VS2019) with vswhere

### ISSUE THREAD

**Issue by zivkan** [Microsoft/vswhere#161]
Can someone please update [this wiki page](https://github.com/Microsoft/vswhere/wiki/Find-MSBuild) with a sample on how to find msbuild.exe that works reliably with both MSBuild 15 (shipped with VS2017) and MSBuild 16 (shipped in the VS2019 preview)?

I added the `-prerelease` flag to get the preview versions of VS/MSBuild, but `msbuild.exe` is no longer under `MSBuild\15.0` and I hoped that VSWhere would help find the executable, rather than me having to iterate all possible permutations in my script until I find the file. Is there a better way?

**Comment by heaths** [comment]
"15.0" is replaced with "Current" going forward. I can update the wiki page to try "Current" and fall back to "15.0", but vswhere is not specific to MSBuild or any other of the very many tools we chain not only in VS, but other products like Build Tools that are installed.

**Comment by zivkan** [comment]
Thank you. I'm aware that vswhere isn't specific to MSBuild, but since Visual Studio doesn't add msbuild to the system or user path, it seems to be a very common task that build scripts need. Failing the build script just because the user didn't use the developer command prompt is not suitable. A reliable way to discover msbuild.exe is a product gap that vswhere mostly fills, even if that's not it's primary goal.

I'm glad that the MSBuild team will be making it easier for us with MSBuild 16 and later. It's just a bit of an issue during the period we need to support MSBuild 15 and lower.

And thanks for updating the wiki. I link customers to it when I see questions related to finding msbuild, so it's really useful.

**Comment by nnit-TroelsJensen** [comment]
> I'm glad that the MSBuild team will be making it easier for us with MSBuild 16 and later. It's just a bit of an issue during the period we need to support MSBuild 15 and lower.

+1

**Comment by heaths** [comment]
I implemented the new `-find` parameter to make this even easier. See the updated wiki for finding msbuild for details.

**Comment by nnit-TroelsJensen** [comment]
@heaths I know of the new find method, but i cannot deploy new vswhere easily on all 20 build agents, that we have. So the interim period is the issue.

**Comment by gorgonzola81** [comment]
@heaths @nnit-TroelsJensen Same problem for us. Any news?

**Comment by heaths** [comment]
@gorgonzola81, news of what? The wiki was updated, and if you'd rather use `-find` then acquire vswhere.exe via nuget or chocolatey to control which version you use. There's no bug here, only a couple of existing options.

**Comment by nikhilagrawaldotnet** [comment]
@heaths #194 Does `-find` only work for VS2019?

**Comment by heaths** [comment]
It works for VS2017 and VS2019 - anything using the new setup engine, which we implemented for VS2017+.

**Comment by qlik-okl** [comment]
@heaths -find does not work for vswhere version installed with VS2017. This means there is no good version independent vswhere call that can get the full path to msbuild on a node. That is unfortunate in a typical build farm setup.

**Comment by heaths** [comment]
New features will inevitably ship with new versions. If you want to better control which version you use, you are encouraged to use the nuget- or chocolatey-obtainable versions of vswhere. Our wiki has examples.
