### ISSUE TITLE
Option -products does not accept the id for VS2017 Express Desktop

### ISSUE THREAD

**Issue by imuzzolini** [Microsoft/vswhere#163]
The option `-products` with the value `Microsoft.VisualStudio.Workload.WDExpress` does not work.
The page https://aka.ms/vs/workloads (which is mentioned in the vswhere help) lists `Microsoft.VisualStudio.Workload.WDExpress` as the official id for the product Visual Studio Desktop Express 2017.

I am able to workaround the problem by using the id `Microsoft.VisualStudio.Product.WDExpress`.

I don't know if the problem is in the page about product ids or in the implementation of vswhere.

**Comment by heaths** [comment]
The documentation is wrong. For the product, you need "Microsoft.VisualStudio.**Product**.WDExpress". I'll log a bug against the documentation owners to make sure that's fixed. Thanks for pointing it out.
