### ISSUE TITLE
Does not detect VS 2019 even with -prerelease switch.

### ISSUE THREAD

**Issue by PawanKartikS** [Microsoft/vswhere#167]
Invoking vswhere as `vswhere -prerelease` does not pickup VS 2019. Switch `-all` is to be provided along with `-prerelease` to pickup VS 2019 preview. Is this an issue or am I missing something?

This is preventing from building `vcpkg` from source as the `bootstrap.ps1` does not provide `-all` switch, but only provides `-prerelease`.

**Comment by heaths** [comment]
If `-all` is necessary that means that VS2019 is not in a launchable, supportable state. Our [latest release](https://github.com/Microsoft/vswhere/releases/latest) dumps common state properties - including the state itself - to help diagnose the problem, or just run the Visual Studio Installer which should show a yellow exclamation mark with a tooltip describe what is required (often times a reboot is pending).

If the product is launchable, `-prerelease` is enough to enumerate it. This is a well-tested scenario.

**Comment by PawanKartikS** [comment]
Uninstalling the previous version of VS and rebooting the system helped.

**Comment by heaths** [comment]
I'm glad you were able to get unblocked, but without the repro environment in its previous state we will not be able to diagnose the issue further.
