### ISSUE TITLE
VSWhere does not show VS 2019 BuildTools SKU

### ISSUE THREAD

**Issue by MattGal** [Microsoft/vswhere#177]
`c:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe` -all on a machine with only VS 2019 BuildTools SKU RTM  shows nothing.  Interestingly, installing VS Buildtools is where this vswhere came from. 

Output:
```
Visual Studio Locator version 2.6.7+91f4c1d09e [query version 2.0.2250.60958]
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by heaths** [comment]
`-all` shows instances in any state. `-products *` is required to show any product. By default, only Community, Professional, and Enterprise are enumerated. See #22.
