### ISSUE TITLE
vswhere not reporting any installs after 2019

### ISSUE THREAD

**Issue by kiwidoggie** [microsoft/vswhere#178]
I have currently installed Visual Studio Professional 2017. For some odd reason after installing 2019 bricked my 2017 install where it could not find any of the header files. After a complete uninstall of both products and reinstall of ONLY 2017, vswhere refuses to find my install, which is breaking my builds.

I've tried vswhere -all, vswhere -products *, etc to no avail. What does vswhere check so I can fix it?

![image](https://user-images.githubusercontent.com/9152262/56843783-cef4b600-685a-11e9-937d-cd5e8778ffe7.png)

![image](https://user-images.githubusercontent.com/9152262/56843788-d916b480-685a-11e9-8e5a-e3ea596ded28.png)

**Comment by heaths** [comment]
The query API version is not in the header, which means it is not installed. Try repairing Visual Studio 2017 and see if that fixes the issue.

**Comment by kiwidoggie** [comment]
I have done repair, full uninstall and reinstall with no changes. What query API or which headers should vswhere be checking (that's not getting fixed via repair or reinstall)?

**Comment by Rychard** [comment]
As indicated by the referenced issue above, I have just found issues using `vswhere` after installing the Visual Studio 2019 build tools inside a container.

For convenience, here's a link to the page containing the steps to produce such a container:

https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019

When running `vswhere`, no output is produced, and the only thing installed in this container was the Visual Studio 2019 build tools.

```
PS C:\> & 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' -all
Visual Studio Locator version 2.6.7+91f4c1d09e [query version 2.0.2250.60958]
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\>
```

Just thought I'd mention this here in case you were interested in being able to reproduce the issue locally for debugging purposes.

**Comment by deggua** [comment]
Same issue here, same cause, remains unfixed after uninstall/re-install. Seems to break some utilities that require visual studio installation detection.

**Comment by heaths** [comment]
@Rychard, that is a separate issue. `-all` does not find all products. According to `-h`, you need to pass `-products *` to find any products. By design, vswhere.exe finds only Visual Studio SKUs including Community, Professional, and Enterprise.

**Comment by heaths** [comment]
@kiwidoggie a repair should've fixed the issue, but since it did not, please open an elevated PowerShell prompt and run the following:

```powershell
install-module -scope currentuser MSI # answer Y to any prompts to install nuget.exe
get-msirelatedproductinfo '{1571205C-BAD1-4237-BFE6-B77E622C51DB}'
```

If that returns a result, run:

```powershell
get-msirelatedproductinfo '{1571205C-BAD1-4237-BFE6-B77E622C51DB}' | repair-msiproduct
```

**Comment by IanKemp** [comment]
@Rychard that's a duplicate of #177 and many others and unrelated to this one.

**Comment by dtivel** [comment]
I had the same problem.  VS repair did not work.  However, @heaths' [suggestion](https://github.com/microsoft/vswhere/issues/178#issuecomment-487670874) did work for me.

**Comment by kiwidoggie** [comment]
> I had the same problem. VS repair did not work. However, @heaths' [suggestion](https://github.com/microsoft/vswhere/issues/178#issuecomment-487670874) did work for me.

This appears to fix vswhere for me, still is a bug that needs fixing on the VS team's side.

**Comment by heaths** [comment]
A repair should have fixed it. Please run https://aka.ms/vscollect and attach %TEMP%\vslogs.zip to a new feedback issue you can file from the Feedback icon in the upper-right corner of the Installer UI. Do not share the files via GitHub since they contain PII. With a feedback ticket, it is tied to your account and only we can see them long enough to hopefully diagnose why a repair did not work.

**Comment by kiwidoggie** [comment]
Thank you I will.
