### ISSUE TITLE
Find MSBuild wiki example doesn't work with VS2017

### ISSUE THREAD

**Issue by idbrii** [microsoft/vswhere#180]
It seems the `-find` parameter is no longer (or not yet) supported?

This is the batch file from [Find MSBuild](https://github.com/microsoft/vswhere/wiki/Find-MSBuild):

    @echo off
    setlocal enabledelayedexpansion
    
    for /f "usebackq tokens=*" %%i in (`vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe`) do (
      "%%i" %*
      exit /b !errorlevel!
    )

I try running it as testvswhere.bat:

    C:\> set PATH="C:\Program Files (x86)\Microsoft Visual Studio\Installer\";%PATH%
    C:\> c:\scratch\testvswhere.bat
    '"Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.17.1230.42073]"' is not recognized as an internal or external command,
    operable program or batch file.

If I try just the vswhere command used by both the batch and PowerShell examples:

	C:\> "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe

	Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.17.1230.42073]
	Copyright (C) Microsoft Corporation. All rights reserved.

	Error 0x57: Unknown parameter: find

Microsoft Visual Studio Professional 2017  (Pro)
Version 15.8.4
VisualStudio.15.Release/15.8.4+28010.2026

Removing the `-find` command and it's argument successfully spits out some information, but nothing useful in finding MSBuild.exe. I don't see anything in `-help` that sounds like it will give me the path I'm looking for.

**Comment by heaths** [comment]
`-find` was added later to Visual Studoi and is not in the version of Visual Studio 2017 you have. If you want to control which version of vswhere you have and on which features you can depend, you should acquire it via nuget or chocolatey, as documented here: https://github.com/microsoft/vswhere/wiki/Installing

**Comment by idbrii** [comment]
Is there a way to use my older version of vswhere to find out where MSBuild is installed?

The best I've managed to find is:

```
c:\>"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -requires Microsoft.Component.MSBuild -property installationPath
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
```

and then appending `MSBuild\15.0\Bin\MSBuild.exe`  to the end.

**Comment by heaths** [comment]
See our [wiki page](https://github.com/microsoft/vswhere/wiki/Find-MSBuild).

**Comment by idbrii** [comment]
Ah. [it's in the history of the page](https://github.com/microsoft/vswhere/wiki/Find-MSBuild/62adac8eb22431fa91d94e03503d76d48a74939c). Essentially the same as my installationPath solution.

Thanks for your help!
