### ISSUE TITLE
Any plans on creating an npm package

### ISSUE THREAD

**Issue by canpolat** [microsoft/vswhere#181]
Hi,

Do you have any plans on creating an npm package for vswhere? If not,  would it be OK if I attempted to do it?

**Comment by heaths** [comment]
I started on one that works with the API directly but with node-gyp support waning and node-cmake not supporting pre-built binaries I didn't feel it was worth the time given you can use vswhere with node already (see the wiki for examples). I'm not sure it belongs in this repo anyway, but we might consider a PR. The project subdirectory should have its own subordinate version.json and ideally should statically link vswhere.lib that already implements all the selection logic.

I'd be happy to pick this back up if someone could provide an easy way (even examples) of bundling binaries with node-cmake. The other issue there is that - whether I'm using gyp or cmake as the base - the other projects here ideally need to be converted or a non-codified build order exists I'd rather avoid.

**Comment by canpolat** [comment]
Thank you for the quick response. I currently use the hard-coded path "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" which works on all our machines (so far). We use `grunt-msbuild` to build the solutions and the latest version of it requires the path to msbuild which brought me to this repository. Would be great if we could omit the hard-coded path; but I also submitted a PR to `grunt\msbuild` that would relieve us from that dependency. Worst case scenario is to request all developers to `choco install vswhere` (which is not that bad, really). I'm closing this issue :)

**Comment by heaths** [comment]
Use an environment variable for C:\Program Files (x86) (varies depending on current prices bitness) and that path is always supported starting in Visual Studio 2017 version 15.1.

FWIW, I did check and the prebuild module now supports cmake-js based on an [issue I opened](https://github.com/cmake-js/cmake-js/issues/114) and forgot about. I might take another stab at this. The idea was to link vswhere.lib but provide more functionality a la https://github.com/microsoft/vssetup.powershell.

**Comment by canpolat** [comment]
Sounds very good 👍

**Comment by gengjiawen** [comment]
@heaths Looks the upstream issue got merged.

Also, another is just publish the binary in npm package.
See https://github.com/fritx/win-7zip/blob/981a5fc45c67a283f4c3077fe96208c18c232043/package.json#L14

**Comment by gengjiawen** [comment]
Also I am planning use this lib for `envinfo` https://github.com/tabrindle/envinfo/issues/155. 

So publishing this as npm package will be very helpful.

**Comment by heaths** [comment]
You can package it with your module provided you include the license, e.g. Third-party prices.txt. At this time, we have no plans to upload anything to npm.
