### ISSUE TITLE
Fails to find msbuild in windows container

### ISSUE THREAD

**Issue by agr** [microsoft/vswhere#182]
Dockerfile:
```
FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2 as build
ADD https://github.com/microsoft/vswhere/releases/download/2.6.7/vswhere.exe vswhere.exe
```

build and run:
```
docker build -t vswhere-test .
docker run --rm --entrypoint /vswhere.exe vswhere-test -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
```

Produces no output, while MSBuild happily resides in `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe`.

**Comment by heaths** [comment]
The .NET team removes them to reduce size: https://github.com/microsoft/dotnet-framework-docker/blob/master/4.7.2/sdk/windowsservercore-ltsc2019/Dockerfile#L29-L33. Looks like they already have a [bug on them](https://github.com/microsoft/dotnet-framework-docker#265).
