### ISSUE TITLE
error C2039: 'binary_function': is not a member of 'std'

### ISSUE THREAD

**Issue by BeErikk** [microsoft/vswhere#184]
`binary_function` is apparently deprecated in C++11 and removed in C++17. The macro `_HAS_AUTO_PTR_ETC` hides it in the headers with C++17 in VS2019. I have the following as standard compiler settings:
`-Wall -MP -sdl -guard:cf -Zo -std:c++latest -permissive- -Zc:__cplusplus -Zc:externConstexpr -Zc:inline -Zc:throwingNew`
To succeed compiling I had to change it to:
`-Wall -MP -sdl -guard:cf -Zo -Zc:__cplusplus -Zc:externConstexpr -Zc:inline -Zc:throwingNew`

Got a lot of warnings. Please consider updating to C++17 and `-permissive-`

**Comment by heaths** [comment]
Any particular reason why? Nothing in C++17 is particularly interesting for a project that builds with a single warning (duplicate symbol not in my code but two separate libs) when building the solution as written in either VS2017 or VS2019.

**Comment by BeErikk** [comment]
No offence, I didn't mean criticise. You are of course right. However, I got multiple issues when I tried to compile the project in VS2019. I get a mysterious lock of the Windows SDK UCRT to an old non-installed version (both in VS2017 and in VS2019). Perhaps something is wrong at my side. Perhaps I'm not building in the right way. I was just trying to hint maybe it was time for an overhaul. I thought making the project pass with `-Wall -std:c++latest -permissive-` could be a reasonable, pretty delimited task that could solve the issues I experienced. If the work would be useful or worth the effort is beyond me.

**Comment by heaths** [comment]
When you opened the solution in VS2019, were you prompted to install missing features? I added a .vsconfig file a while ago that should have everything you need to build successfully. I tried this in a clean VM and was able to build successfully after running `nuget restore` (or just right-click on the solution, and click "Restore packages").

**Comment by BeErikk** [comment]
No, I just retargeted the solution to 10.0.18362.0 and v142. And when I got troubles I updated the NuGet packages.

I was forced to add 
`$(WindowsSdkDir)Include\$(WindowsTargetPlatformVersion)\ucrt;` to project include dirs

The project `UniversalCRT*` variables all points to  bogus
`<WindowsKits>10\<*>\10.0.14393.0\<*>`

while all other Windows SDK paths are correct

In my other project, I have open in another VS2019 instance, all paths are OK. It must, therefore, be on a per solution/project I think. There are some posts on StackOverflow about the phenomena.

Actually, I eventually ended up compiling the project in my highly modded VS2008, only using the VS2019 tools. Fast and works "like a charm" ;). That's why the custom compiler settings.

**Comment by heaths** [comment]
At some point I'll have to migrate to newer versions because v141 is deprecated past VS2019, which also means we'd likely need to drop XP support (which I only added for `-legacy` support) so we'll either have to maintain a custom build or drop it. At that point I'll revisit, but since you changed the solution and projects by upgrading them, it's not currently a bug against the existing code. But thanks for reporting the issues you ran into and I'll keep those in mind to fix/work around when the time comes.
