### ISSUE TITLE
Update vswhere whenever the Visual Studio Installer is run

### ISSUE THREAD

**Issue by IanKemp** [microsoft/vswhere#186]
There is currently no way to automatically update the installed version of vswhere to the latest version, which is painful. Since vswhere is now an integral part of the VS installation, it should be updated as part of it, i.e. any time the Visual Studio Installer is run.

**Comment by heaths** [comment]
It is part of the Visual Studio Installer and updated when the installer is. The recommended method to control which version (newest, or some specific version) of vswhere is to acquire it via nuget or chocolatey. This is the only way to control what features/behavior you get regardless of the machine state on which you run.
