### ISSUE TITLE
Can it be used to find earlier than VS 2017

### ISSUE THREAD

**Issue by jayvdb** [microsoft/vswhere#187]
The readme only talks about VS 2017.

It would be helpful if it could also detect older versions, to simplify build scripts which need to find the best `vcvarsall.bat` on the host, and falling back to older versions if that is necessary.

It would also be useful if it could provide the args needed for the host.

e.g. for VS 2014, vcvarsall.bat needs(?) an argument x86 / x86_amd64 / etc

If these features are available already, an example of this in the readme would be great.

**Comment by heaths** [comment]
If you pass `-?` (or `-h`, which is common with many programs even across platforms), it shows you usage, such as you can use `-legacy` to find installation roots for VS2010 and newer. Many other command line switches do not work with `-legacy`, though. This was designed to work with the new engine we started using for VS2017.
