### ISSUE TITLE
Find VS2017 installation directory with with "vswhere -version" when VS2019 or higher version exists

### ISSUE THREAD

**Issue by anujcgi013** [microsoft/vswhere#188]
@echo off
set vswhere= "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"

for /f "usebackq tokens=*" %%i in (`%vswhere% -version '[15.0,)' -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do (
  set InstallDir=%%i
)

if exist "%InstallDir%\MSBuild\15.0\Bin\MSBuild.exe" (
--------------------------------------------------------------
I have above batch command for VS2017 build, but with **"VsWhere Latest"** I am always getting VS2019 directory path and because VS2019 does not have folder "15.0" its failing to build.

`%vswhere% -versions 15.* -products * -requires Microsoft.Component.MSBuild -property installationPath`

Any help will be appreciated. Thanks

**Comment by heaths** [comment]
You specified both 15.0 and newer and `-latest`, and since 16.0 (VS2019) is newer that's what gets returned. Drop `-latest`, or use a version range like `[15.0,16.0)`.

**Comment by anujcgi013** [comment]
I had corrected it to "%vswhere% -versions 15.* -products * -requires Microsoft.Component.MSBuild -property installationPath"

Still having issues. Is there any issues with the above syntax.

Thanks,

**Comment by heaths** [comment]
That is not the correct syntax for `-version`. Please see `-help` for examples.
