### ISSUE TITLE
What's the equivalent of vswhere -find in vssetup.powershell

### ISSUE THREAD

**Issue by icraftsoftware** [microsoft/vswhere#189]
Hello

I would prefer to use vssetup.powershell, which is PowerShell native than vswhere.exe. However I can't find the PowerShell equivalent for the `-find` parameter of vswhere. For instance:

`vswhere.exe -latest -requires Microsoft.VisualStudio.TestTools.TeamFoundationClient -find **\Microsoft.TeamFoundation.Client.dll`

Is it supported by PowerShell? If so, how should I write it?

Thank you for your help

François

PS: this is a duplicate of [vssetup.powershell:issue#52](https://github.com/microsoft/vssetup.powershell/issues/52)

**Comment by heaths** [comment]
It isn't supported but easy enough to do in PowerShell yourself by piping to `get-childitem`. But please ask questions about that module in it's own repo.
