### ISSUE TITLE
Vswhere -find do not return results on Windows Server 2012 with VS2017

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [microsoft/vswhere#194]
In my CI pipeline,  I am using `vswhere` 2.6.7 for getting MSBuild instance. When I run it locally it returns results, but when I run it on Windows 2012 servers, it returns no results.

    vswhere.exe -latest -requires "Microsoft.Component.MSBuild" -property installationPath -nologo -products *

    vswhere.exe -latest -requires "Microsoft.Component.MSBuild" -find MSBuild\**\Bin\MSBuild.exe

![image](https://user-images.githubusercontent.com/26463468/62043681-929c7180-b21e-11e9-85e7-3ab5387b3c38.png)

**Comment by heaths** [comment]
Did you check that msbuild.exe is actually in that path for Build Tools on Server 2012? There are no platform-specific APIs that are used (well, nothing that isn't on Windows XP or newer, anyway).

**Comment by heaths** [comment]
BTW, I noticed that you didn't include `-products *` in the second command. If only Build Tools installed, you still need that. Add that to the command line and try again.

**Comment by heaths** [comment]
Closing since there's been no response and the command line in the second instance is wrong in the screenshot (you need to provide the `-products *` in that invocation as well). If this continues to repro even with that command line parameter, please comment and we can reopen for investigation.
