### ISSUE TITLE
Why not provided as global tool?

### ISSUE THREAD

**Issue by TFTomSun** [microsoft/vswhere#196]
Why is that tool not provided as [global tool](https://docs.microsoft.com/de-de/dotnet/core/tools/global-tools)? And why is the batch code so complicated? 

I proposed in another thread that it would be nice to have a global tool that directly redirects to msbuild e.g.

> dotnet msbuild-net /t:Publish ...

please make it simple :)
Thank you.

**Comment by TFTomSun** [comment]
I've just created a global tool for me:

**Program.cs**
```cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace MsBuildNet
{
    class Program
    {
        static void Main(string[] args)
        {
            var programFiles = Environment.GetEnvironmentVariable("ProgramFiles(x86)");
            var vsWhereExe = Path.Combine(programFiles, "Microsoft Visual Studio", "Installer", "vswhere.exe");
            var processStartInfo = new ProcessStartInfo(vsWhereExe, @"-latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe");
            processStartInfo.RedirectStandardOutput = true;
            using (var vsWhereProcess = Process.Start(processStartInfo))
            {
                vsWhereProcess?.WaitForExit();
                var msbuildExe =  vsWhereProcess?.StandardOutput.ReadToEnd().Split(Environment.NewLine).First();

                var arguments = args.Any() ? args.Aggregate((a, b) => $"{a} {b}") : string.Empty;
                Process.Start(msbuildExe, arguments)?.WaitForExit();
            }

        }
    }
}

```

**MsBuildTool.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>msbuild-net</ToolCommandName>
  </PropertyGroup>

</Project>
```

**Comment by heaths** [comment]
Thank you for the suggestion, but it's already acquirable as a nuget package that can be unpacked easily. You can use it from batch or PowerShell, the latter of which is easy to use if you output JSON and pipe to `ConvertFrom-Json`. Does that not work for you?

As for using specific command line args as you have done, people have different requirements for supported products or required workloads, which is why its meant to be used in customized use cases. This may work for you, but I've seen many different use cases.

**Comment by heaths** [comment]
...and if you use PowerShell, it's even easier to get a single location:

```powershell
$path = vswhere -prerelease -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\bin\MSBuild.exe
& $path /m /p:Configuration=Release
```

This tool is meant to be flexible for a myriad of reasons. MSBuild is not the only use case for vswhere.

**Comment by TFTomSun** [comment]
yeah maybe this repository is the wrong one to request something like this. Anyway you could still think about providing vswhere itself as a global tool. With .NET 5 everything will become one anyway.

**Comment by heaths** [comment]
Thanks for the suggestion, but you can do that today as well with nuget.exe:

```
nuget install -x -o . vswhere
vswhere\tools\vswhere.exe ...
```

As this supports more than .NET (Core or Framework) I don't see a lot of value in making it acquirable through so many different methods. I do think making a specific .NET Framework-specific MSBuild command as you've demonstrated makes some sense, but also agree it's outside the scope of this repo. Perhaps in another projects under https://github.com/dotnet?

**Comment by TFTomSun** [comment]
yeah, just that nuget is not a registered command by default like dotnet. you can't call it in any context. And vswhere is not a registered command after the installation too... so whereever you call this u create a new local copy of that tool.

**Comment by heaths** [comment]
dotnet.exe isn't registered by default - it doesn't come with Windows. You can simply download [nuget.exe](https://nuget.org/nuget.exe) to anywhere, including in directories already in your PATH. And it does work without packages.config or nuget.config. That command I pasted above I tested in a new subdirectory of %TEMP%. It searches nuget.org by default if no other nuget.config is present in its lookup order.

**Comment by DavidDeSloovere** [comment]
I think it's time to rethink this. 
Having vswhere as a local/global tool would be awesome.

**Comment by TonyValenti** [comment]
I want this too.

**Comment by heaths** [comment]
It's already available with winget, scoop, and chocolatey: https://github.com/microsoft/vswhere/wiki/Installing. What are the benefits of yet another deployment mechanism that requires .NET when the others will install vswhere to `%PATH%`?

**Comment by Malcolmnixon** [comment]
The benefit of having this as a dotnet tool is for CI builds where tool versions can be specified with a '.config/dotnet-tools.json' file. Each different CI job can call for a different version of the dotnet tool without having to have them "installed" into the OS/Path.

Especially for regulated environments it's critically important to control the exact version of tools installed on a system.

**Comment by heaths** [comment]
winget, scoop, and chocolatey all let you specify a version as well and a couple let you specify an extraction location instead of a normal install. This tool isn't even specific to .NET, so I don't think adding yet another installation mechanism that is provided by .NET makes sense. CI machines are also typically ephemeral so I also don't see how updating the PATH in lieu of extraction is problematic. There's a non-zero cost to maintaining all these accounts required to publish to different locations.
