### ISSUE TITLE
Question regarding earliest supported VS version (-legacy)

### ISSUE THREAD

**Issue by assarbad** [microsoft/vswhere#197]
Hi,

I am curious what is the earliest supported VS version supported by the `-legacy` switch and if that is very limited whether you would accept patches extending its scope back to, say, VS 2002.

Thanks.

**Comment by heaths** [comment]
It only checks Visual Studio 2010 and newer, as those are currently the only supported versions.

**Comment by assarbad** [comment]
And what's your stance regarding the support of older versions, if it were to be contributed?

I am asking because I am interested in adding it. But I'd definitely steer clear of any situation where this would result in a (hard) fork. I'd rather prefer to see this in the real that will be installed with new VS versions.

The reason I am asking is [this script](https://bitbucket.org/assarbad/scripts/src/default/setvcvars.cmd) which could benefit from such functionality.

Thanks.

**Comment by heaths** [comment]
We had discussed it when I originally added this feature and decided we'd only support Visual Studio versions that themselves were in support. While technically the registry detection is mostly the same, there are slight difference to account for and already `-legacy` support has kept my hands a bit tied with other new features we've wanted to add, so we probably wouldn't take it.

**Comment by assarbad** [comment]
Thanks for the info.
