### ISSUE TITLE
Unable to find suitable Visual Code toolchain. Visual Studio 2019 Community problem. 

### ISSUE THREAD

**Issue by Ali-NS** [microsoft/vswhere#198]
Hi all, I try the Flutter for Desktop for the first time using https://github.com/google/flutter-desktop-embedding.git, appear the Visual Studio Installation problem when running flutter doctor command.

![flutter_desktop_embedding_problem](https://user-images.githubusercontent.com/53884434/62673559-0bdb5780-b9c9-11e9-968e-85f31449e9a8.png)

- The Visual Studio 2019 - Community already installed in the c:\Program Files (x86)\Microsoft Visual Studio, still problem. 

- vswhere.exe is default file In the c:\Program Files (x86)\Microsoft Visual Studio\Installer, version 2.6.7+91f4c1d09e

I ran this `vswhere -format json -utf8 -latest`  command :

> C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere

> Visual Studio Locator version 2.6.7+91f4c1d09e

> Copyright (C) Microsoft Corporation. All rights reserved.

> C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere -format json -utf8 -latest

> []

> C:\Program Files (x86)\Microsoft Visual Studio\Installer>

![Visual_Studio_vswhere_problem](https://user-images.githubusercontent.com/53884434/62673841-1fd38900-b9ca-11e9-912c-c9838a8c460f.png)

**Comment by stuartmorgan** [comment]
```
C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere -format json -utf8 -latest

[]
```

To provide some context on the above, `vswhere -format json -utf8 -latest` is the command that `flutter` is using internally to locate Visual Studio (there are more precise queries that find a version with specific components, but it falls back to that simple form to determine if it's installed at all, to make the error message specific).

**Comment by heaths** [comment]
If you have a prerelease installed, you need to specify `-prerelease`, and if the product is in a broken state (perhaps pending a reboot) `-all` is required as stated in the usage output. Pass both and there are properties that will tell you if it's launchable and/or a prerelease.

**Comment by Ali-NS** [comment]
I'm sorry, the problem is because not install the Visual Studio 2019 Community until finish. This is why `vswhere -format json -utf8 -latest` command json result is empty. 

After download the Visual Studio 2019 Community installer https://visualstudio.microsoft.com/downloads/ ;

- Install vs_community__297403493.1565237702.exe
- Check list -> **Desktop development with C ++** 
- Choose in the **Installation details** -> **''Windows 10 SDK (10.0.17763.0)''** and **''MSVC v141 - VS 2017..."** 
- Select Install button to Finishing the Installation Visual Studio 2019 Community.

![3](https://user-images.githubusercontent.com/53884434/62691190-5de7a180-b9f8-11e9-8989-485cdbd89b19.png)

After Installation finish, please restart the PC.

![Visual_Studio_2019_Community_Install_Restart](https://user-images.githubusercontent.com/53884434/62692603-26c6bf80-b9fb-11e9-875e-76f2dbfa87ea.png)

I ran  `vswhere -format json -utf8 -latest`, OK.

![Visual_Studio_2019_vswhere_command](https://user-images.githubusercontent.com/53884434/62692662-478f1500-b9fb-11e9-8afb-866339465aec.png)

I ran  `flutter doctor`, OK.

![Flutter_Doctor_test](https://user-images.githubusercontent.com/53884434/62692731-62fa2000-b9fb-11e9-83bb-c6a9bd8bc8f1.png)

Thank you @stuartmorgan, @heaths for the respon.

**Comment by stuartmorgan** [comment]
> if the product is in a broken state (perhaps pending a reboot) -all is required as stated in the usage output.

Thanks, I was aware that the logic needed to be updated to incorporate `-prerelease`, but had missed `-all`.

**Comment by eswarvarma-dev** [comment]
still same issue

**Comment by stuartmorgan** [comment]
@eswarvarma-dev The specific cause here is fixed. If you have similar symptoms on latest master you should file a new Flutter issue with details.
