### ISSUE TITLE
VsWhere cannot find components

### ISSUE THREAD

**Issue by marinat** [microsoft/vswhere#199]
I'm trying to run flutter desktop example, but flutter doctor cannot find necessary vs components https://github.com/flutter/flutter/issues/40335

**Comment by heaths** [comment]
The command works against my 16.3 Preview 3.0 install. Teams may change component names, though they are encouraged not to. Use https://github.com/microsoft/vssetup.powershell to run the following and see if the components truly are installed or what other names they might be under for 16.2 (which is what you have installed):

```powershell
get-vssetupinstance -path 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community' | select -expand Packages | select -expand Id | sort
```

**Comment by marinat** [comment]
Result of command execution :

Component.Microsoft.VisualStudio.LiveShare
GitHub.VisualStudio.16
MessagePack_v2_0_94
Microsoft.Build
Microsoft.Build.Dependencies
Microsoft.Build.FileTracker.Msi
Microsoft.CodeAnalysis.Compilers
Microsoft.CodeAnalysis.ExpressionEvaluator
Microsoft.CodeAnalysis.VisualStudio.Setup
Microsoft.Component.MSBuild
Microsoft.CredentialProvider
Microsoft.DiaSymReader
Microsoft.IntelliTrace.CollectorCab
Microsoft.IntelliTrace.DiagnosticsHub
Microsoft.IntelliTrace.DiagnosticsHub.Resources
Microsoft.MSHtml
Microsoft.Net.4.7.2.FullRedist
Microsoft.Net.4.7.2.FullRedist.Resources
Microsoft.Net.4.TargetingPack
Microsoft.Net.PackageGroup.4.7.2.Redist
Microsoft.NuGet.Build.Tasks
Microsoft.PackageGroup.ClientDiagnostics
Microsoft.ServiceHub
Microsoft.VisualC.14.21.CodeAnalysis.ConcCheck.X64
Microsoft.VisualC.14.21.CodeAnalysis.ConcCheck.X64.Resources
Microsoft.VisualC.14.21.CodeAnalysis.ConcCheck.X86
Microsoft.VisualC.14.21.CodeAnalysis.ConcCheck.X86.Resources
Microsoft.VisualC.14.21.CodeAnalysis.Extensions.X64
Microsoft.VisualC.14.21.CodeAnalysis.Extensions.X86
Microsoft.VisualC.14.21.CRT.Headers
Microsoft.VisualC.14.21.CRT.Redist.X64
Microsoft.VisualC.14.21.CRT.Redist.x64.OneCore.Desktop
Microsoft.VisualC.14.21.CRT.Redist.X86
Microsoft.VisualC.14.21.CRT.Redist.x86.OneCore.Desktop
Microsoft.VisualC.14.21.CRT.Source
Microsoft.VisualC.14.21.CRT.x64.Desktop
Microsoft.VisualC.14.21.CRT.x64.OneCore.Desktop
Microsoft.VisualC.14.21.CRT.x64.Store
Microsoft.VisualC.14.21.CRT.x86.Desktop
Microsoft.VisualC.14.21.CRT.x86.OneCore.Desktop
Microsoft.VisualC.14.21.CRT.x86.Store
Microsoft.VisualC.14.21.PGO.Headers
Microsoft.VisualC.14.21.PGO.X64
Microsoft.VisualC.14.21.PGO.X86
Microsoft.VisualC.14.21.Prem.Tools.HostX64.TargetX64
Microsoft.VisualC.14.21.Prem.Tools.HostX64.TargetX64.Resources
Microsoft.VisualC.14.21.Prem.Tools.HostX64.TargetX86
Microsoft.VisualC.14.21.Prem.Tools.HostX64.TargetX86.Resources
Microsoft.VisualC.14.21.Prem.Tools.HostX86.TargetX64
Microsoft.VisualC.14.21.Prem.Tools.Hostx86.Targetx64.Resources
Microsoft.VisualC.14.21.Prem.Tools.HostX86.TargetX86
Microsoft.VisualC.14.21.Prem.Tools.HostX86.TargetX86.Resources
Microsoft.VisualC.14.21.Tools.Core.x86
Microsoft.VisualC.14.21.Tools.HostX64.TargetX64
Microsoft.VisualC.14.21.Tools.HostX64.TargetX64.Resources
Microsoft.VisualC.14.21.Tools.HostX64.TargetX86
Microsoft.VisualC.14.21.Tools.HostX64.TargetX86.Resources
Microsoft.VisualC.14.21.Tools.HostX86.TargetX64
Microsoft.VisualC.14.21.Tools.Hostx86.Targetx64.Resources
Microsoft.VisualC.14.21.Tools.HostX86.TargetX86
Microsoft.VisualC.14.21.Tools.HostX86.TargetX86.Resources
Microsoft.VisualCpp.ATL.Headers
Microsoft.VisualCpp.ATL.Source
Microsoft.VisualCpp.ATL.X64
Microsoft.VisualCpp.ATL.X86
Microsoft.VisualCpp.CRT.ClickOnce.Msi
Microsoft.VisualCpp.CRT.Redist.Resources
Microsoft.VisualCpp.DIA.SDK
Microsoft.VisualCpp.Redist.14
Microsoft.VisualCpp.Redist.14
Microsoft.VisualCpp.Redist.14.Latest
Microsoft.VisualCpp.Redist.14.Latest
Microsoft.VisualCpp.RuntimeDebug.14
Microsoft.VisualCpp.RuntimeDebug.14
Microsoft.VisualCpp.Tools.Common.Utils
Microsoft.VisualCpp.Tools.Common.Utils.Resources
Microsoft.VisualCpp.Tools.Common.UtilsPrereq
Microsoft.VisualStudio.AppResponsiveness
Microsoft.VisualStudio.AppResponsiveness.Resources
Microsoft.VisualStudio.AppResponsiveness.Targeted
Microsoft.VisualStudio.Branding.Community
Microsoft.VisualStudio.ClientDiagnostics
Microsoft.VisualStudio.ClientDiagnostics.Resources
Microsoft.VisualStudio.ClientDiagnostics.Targeted
Microsoft.VisualStudio.CodeSense.Community
Microsoft.VisualStudio.CodeSense.Community.Resources
Microsoft.VisualStudio.Community
Microsoft.VisualStudio.Community.Extra
Microsoft.VisualStudio.Community.Extra.Resources
Microsoft.VisualStudio.Community.Msi
Microsoft.VisualStudio.Community.Msi.Resources
Microsoft.VisualStudio.Community.Resources
Microsoft.VisualStudio.Community.x64
Microsoft.VisualStudio.Community.x86
Microsoft.VisualStudio.Component.CoreEditor
Microsoft.VisualStudio.Component.Debugger.JustInTime
Microsoft.VisualStudio.Component.IntelliCode
Microsoft.VisualStudio.Component.NuGet
Microsoft.VisualStudio.Component.Roslyn.Compiler
Microsoft.VisualStudio.Component.TextTemplating
Microsoft.VisualStudio.Component.VC.14.21.x86.x64
Microsoft.VisualStudio.Component.VC.ATL
Microsoft.VisualStudio.Component.VC.CoreIde
Microsoft.VisualStudio.Component.VC.Redist.14.Latest
Microsoft.VisualStudio.Component.VC.TestAdapterForBoostTest
Microsoft.VisualStudio.Component.VC.TestAdapterForGoogleTest
Microsoft.VisualStudio.Component.Windows10SDK.17763
Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core
Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions
Microsoft.VisualStudio.Connected
Microsoft.VisualStudio.Connected.Resources
Microsoft.VisualStudio.CoreEditor
Microsoft.VisualStudio.CoreEditor.Resources
Microsoft.VisualStudio.Debugger
Microsoft.VisualStudio.Debugger.CollectionAgents
Microsoft.VisualStudio.Debugger.Concord
Microsoft.VisualStudio.Debugger.Concord.Managed
Microsoft.VisualStudio.Debugger.Concord.Managed.Resources
Microsoft.VisualStudio.Debugger.Concord.Remote
Microsoft.VisualStudio.Debugger.Concord.Remote
Microsoft.VisualStudio.Debugger.Concord.Remote.Resources
Microsoft.VisualStudio.Debugger.Concord.Remote.Resources
Microsoft.VisualStudio.Debugger.Concord.Resources
Microsoft.VisualStudio.Debugger.DbgHelp.Win8
Microsoft.VisualStudio.Debugger.ImmersiveActivateHelper.Msi
Microsoft.VisualStudio.Debugger.JustInTime
Microsoft.VisualStudio.Debugger.JustInTime.Msi
Microsoft.VisualStudio.Debugger.Managed
Microsoft.VisualStudio.Debugger.Managed.Resources
Microsoft.VisualStudio.Debugger.Package.DiagHub.Client.VSx86
Microsoft.VisualStudio.Debugger.Parallel
Microsoft.VisualStudio.Debugger.Parallel.Resources
Microsoft.VisualStudio.Debugger.Remote
Microsoft.VisualStudio.Debugger.Remote
Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8
Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8
Microsoft.VisualStudio.Debugger.Remote.DiagHub.Client
Microsoft.VisualStudio.Debugger.Remote.DiagHub.Client
Microsoft.VisualStudio.Debugger.Remote.Resources
Microsoft.VisualStudio.Debugger.Remote.Resources
Microsoft.VisualStudio.Debugger.Resources
Microsoft.VisualStudio.Debugger.Script
Microsoft.VisualStudio.Debugger.Script
Microsoft.VisualStudio.Debugger.Script.Msi
Microsoft.VisualStudio.Debugger.Script.Resources
Microsoft.VisualStudio.Debugger.Script.Resources
Microsoft.VisualStudio.Debugger.TimeTravel.Agent
Microsoft.VisualStudio.Debugger.TimeTravel.Record
Microsoft.VisualStudio.Debugger.TimeTravel.Runtime
Microsoft.VisualStudio.Debugger.TimeTravel.Runtime
Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost
Microsoft.VisualStudio.Devenv
Microsoft.VisualStudio.Devenv.Config
Microsoft.VisualStudio.Devenv.Msi
Microsoft.VisualStudio.Devenv.Resources
Microsoft.VisualStudio.Editors
Microsoft.VisualStudio.ExtensionManager
Microsoft.VisualStudio.ExtensionManager.Resources
Microsoft.VisualStudio.FileHandler.Msi
Microsoft.VisualStudio.FileHandler.Msi
Microsoft.VisualStudio.Finalizer
Microsoft.VisualStudio.GraphModel
Microsoft.VisualStudio.GraphModel.Resources
Microsoft.VisualStudio.GraphProvider
Microsoft.VisualStudio.GraphProvider.Resources
Microsoft.VisualStudio.Initializer
Microsoft.VisualStudio.IntelliCode
Microsoft.VisualStudio.LanguageServer
Microsoft.VisualStudio.LanguageServer.Resources
Microsoft.VisualStudio.LiveShare
Microsoft.VisualStudio.LiveShareApi
Microsoft.VisualStudio.Log
Microsoft.VisualStudio.Log.Resources
Microsoft.VisualStudio.Log.Targeted
Microsoft.VisualStudio.MefHosting
Microsoft.VisualStudio.MefHosting.Resources
Microsoft.VisualStudio.MinShell
Microsoft.VisualStudio.MinShell.Interop
Microsoft.VisualStudio.MinShell.Interop.Msi
Microsoft.VisualStudio.MinShell.Msi
Microsoft.VisualStudio.MinShell.Msi.Resources
Microsoft.VisualStudio.MinShell.Platform
Microsoft.VisualStudio.MinShell.Platform.Resources
Microsoft.VisualStudio.MinShell.Resources
Microsoft.VisualStudio.MinShell.x86
Microsoft.VisualStudio.NativeImageSupport
Microsoft.VisualStudio.Net.Eula.Resources
Microsoft.VisualStudio.NuGet.Core
Microsoft.VisualStudio.NuGet.Licenses
Microsoft.VisualStudio.NuGet.PowershellBindingRedirect
Microsoft.VisualStudio.OpenFolder.VSIX
Microsoft.VisualStudio.PackageGroup.Community
Microsoft.VisualStudio.PackageGroup.CommunityCore
Microsoft.VisualStudio.PackageGroup.Core
Microsoft.VisualStudio.PackageGroup.CoreEditor
Microsoft.VisualStudio.PackageGroup.Debugger.Core
Microsoft.VisualStudio.PackageGroup.Debugger.Script
Microsoft.VisualStudio.PackageGroup.Debugger.TimeTravel.Record
Microsoft.VisualStudio.PackageGroup.MinShell
Microsoft.VisualStudio.PackageGroup.MinShell.Interop
Microsoft.VisualStudio.PackageGroup.NuGet
Microsoft.VisualStudio.PackageGroup.Progression
Microsoft.VisualStudio.PackageGroup.TeamExplorer.Common
Microsoft.VisualStudio.PackageGroup.TestTools.CodeCoverage
Microsoft.VisualStudio.PackageGroup.TestTools.Core
Microsoft.VisualStudio.PackageGroup.TestTools.DataCollectors
Microsoft.VisualStudio.PackageGroup.TestTools.Native
Microsoft.VisualStudio.PackageGroup.TestTools.TestPlatform.IDE
Microsoft.VisualStudio.PackageGroup.TestTools.TestPlatform.Legacy
Microsoft.VisualStudio.PackageGroup.TestTools.TestPlatform.V1.CLI
Microsoft.VisualStudio.PackageGroup.TestTools.TestPlatform.V2.CLI
Microsoft.VisualStudio.PackageGroup.VC.CoreIDE.Express
Microsoft.VisualStudio.PackageGroup.VC.CoreIDE.Reduced
Microsoft.VisualStudio.PackageGroup.VsDevCmd
Microsoft.VisualStudio.PerfLib
Microsoft.VisualStudio.PerformanceProvider
Microsoft.VisualStudio.Platform.CallHierarchy
Microsoft.VisualStudio.Platform.Editor
Microsoft.VisualStudio.Platform.NavigateTo
Microsoft.VisualStudio.Product.Community
Microsoft.VisualStudio.ProjectServices
Microsoft.VisualStudio.ProjectSystem
Microsoft.VisualStudio.ProjectSystem.Full
Microsoft.VisualStudio.ProTools
Microsoft.VisualStudio.ProTools.Resources
Microsoft.VisualStudio.ScriptedHost
Microsoft.VisualStudio.ScriptedHost.Resources
Microsoft.VisualStudio.ScriptedHost.Targeted
Microsoft.VisualStudio.Setup.Configuration
Microsoft.VisualStudio.TeamExplorer
Microsoft.VisualStudio.TestTools.Pex.Common
Microsoft.VisualStudio.TestTools.Pex.Common.Resources
Microsoft.VisualStudio.TestTools.TeamFoundationClient
Microsoft.VisualStudio.TestTools.TeamFoundationClient.Resources
Microsoft.VisualStudio.TestTools.TestPlatform.IDE
Microsoft.VisualStudio.TestTools.TestPlatform.Legacy.Agent
Microsoft.VisualStudio.TestTools.TestPlatform.Legacy.Common
Microsoft.VisualStudio.TestTools.TestPlatform.Legacy.Core
Microsoft.VisualStudio.TestTools.TestPlatform.Legacy.Core.Resources
Microsoft.VisualStudio.TestTools.TestPlatform.Legacy.Professional
Microsoft.VisualStudio.TestTools.TestPlatform.Legacy.TestTools
Microsoft.VisualStudio.TestTools.TestPlatform.Legacy.Tips
Microsoft.VisualStudio.TestTools.TestPlatform.Legacy.Tips.Resources
Microsoft.VisualStudio.TestTools.TestPlatform.V1.CLI
Microsoft.VisualStudio.TestTools.TestPlatform.V1.CPP
Microsoft.VisualStudio.TestTools.TestPlatform.V2.CLI
Microsoft.VisualStudio.TestTools.TestWIExtension
Microsoft.VisualStudio.TestTools.TestWIExtension.Res
Microsoft.VisualStudio.TestTools.TP.Legacy.Common.Res
Microsoft.VisualStudio.TestTools.TP.Legacy.Tips.Common
Microsoft.VisualStudio.TestTools.TP.Legacy.Tips.Msi
Microsoft.VisualStudio.TestTools.TP.V1.CLI.Resources
Microsoft.VisualStudio.TestTools.TP.V1.CPP.Resources
Microsoft.VisualStudio.TextMateGrammars
Microsoft.VisualStudio.TextTemplating.Core
Microsoft.VisualStudio.TextTemplating.Core.Resources
Microsoft.VisualStudio.TextTemplating.Integration
Microsoft.VisualStudio.TextTemplating.Integration.Resources
Microsoft.VisualStudio.TextTemplating.MSBuild
Microsoft.VisualStudio.TextTemplating.MSBuild.Resources
Microsoft.VisualStudio.VC.DevCmd
Microsoft.VisualStudio.VC.DevCmd.Resources
Microsoft.VisualStudio.VC.Ide.ATL
Microsoft.VisualStudio.VC.Ide.ATL.Resources
Microsoft.VisualStudio.VC.Ide.Base
Microsoft.VisualStudio.VC.Ide.Base.Resources
Microsoft.VisualStudio.VC.Ide.Common
Microsoft.VisualStudio.VC.Ide.Common.Resources
Microsoft.VisualStudio.VC.Ide.Core
Microsoft.VisualStudio.VC.Ide.Core.Resources
Microsoft.VisualStudio.VC.Ide.Core.VCProjectEngine
Microsoft.VisualStudio.VC.Ide.Core.VCProjectEngine.Resources
Microsoft.VisualStudio.VC.Ide.Debugger
Microsoft.VisualStudio.VC.Ide.Debugger.Concord
Microsoft.VisualStudio.VC.Ide.Debugger.Concord.Resources
Microsoft.VisualStudio.VC.Ide.Debugger.Resources
Microsoft.VisualStudio.VC.Ide.Dskx
Microsoft.VisualStudio.VC.Ide.Dskx.Resources
Microsoft.VisualStudio.VC.Ide.LanguageService
Microsoft.VisualStudio.VC.Ide.LanguageService.Resources
Microsoft.VisualStudio.VC.Ide.MDD
Microsoft.VisualStudio.VC.Ide.MDD.Resources
Microsoft.VisualStudio.VC.Ide.Pro
Microsoft.VisualStudio.VC.Ide.Pro.Resources
Microsoft.VisualStudio.VC.Ide.ProjectSystem
Microsoft.VisualStudio.VC.Ide.ProjectSystem.Resources
Microsoft.VisualStudio.VC.Ide.ResourceEditor
Microsoft.VisualStudio.VC.Ide.ResourceEditor.Resources
Microsoft.VisualStudio.VC.Ide.TestAdapterForBoostTest
Microsoft.VisualStudio.VC.Ide.TestAdapterForGoogleTest
Microsoft.VisualStudio.VC.Ide.VCPkgDatabase
Microsoft.VisualStudio.VC.Ide.WinXPlus
Microsoft.VisualStudio.VC.Ide.x64
Microsoft.VisualStudio.VC.Items.Pro
Microsoft.VisualStudio.VC.Llvm.Base
Microsoft.VisualStudio.VC.MSBuild.ARM
Microsoft.VisualStudio.VC.MSBuild.ARM.v142
Microsoft.VisualStudio.VC.MSBuild.Base
Microsoft.VisualStudio.VC.MSBuild.Base.Resources
Microsoft.VisualStudio.VC.MSBuild.X64
Microsoft.VisualStudio.VC.MSBuild.X64.v142
Microsoft.VisualStudio.VC.MSBuild.X86
Microsoft.VisualStudio.VC.MSBuild.x86.v142
Microsoft.VisualStudio.VC.MSVCDis
Microsoft.VisualStudio.VC.Templates.Desktop
Microsoft.VisualStudio.VC.Templates.Pro
Microsoft.VisualStudio.VC.Templates.Pro.Resources
Microsoft.VisualStudio.VC.Templates.UnitTest
Microsoft.VisualStudio.VC.Templates.UnitTest.Resources
Microsoft.VisualStudio.VC.UnitTest.Desktop.Build.Core
Microsoft.VisualStudio.VirtualTree
Microsoft.VisualStudio.VirtualTree.Resources
Microsoft.VisualStudio.VisualC.Logging
Microsoft.VisualStudio.VsDevCmd.Core.DotNet
Microsoft.VisualStudio.VsDevCmd.Core.WinSdk
Microsoft.VisualStudio.VsDevCmd.Ext.NetFxSdk
Microsoft.VisualStudio.WebSiteProject.DTE
Microsoft.VisualStudio.WebSiteProject.DTE.Resources
Microsoft.VisualStudio.WebTools
Microsoft.VisualStudio.WebTools.MSBuild
Microsoft.VisualStudio.WebTools.MSBuild.Resources
Microsoft.VisualStudio.WebTools.Resources
Microsoft.VisualStudio.WebTools.WSP.FSA
Microsoft.VisualStudio.WebTools.WSP.FSA.Resources
Microsoft.VisualStudio.WebToolsExtensions
Microsoft.VisualStudio.WebToolsExtensions.Resources
Microsoft.VisualStudio.Workload.CoreEditor
Microsoft.VisualStudio.Workload.NativeDesktop
Microsoft.VS.VC.MSBuild.X64.Resources
Microsoft.WebTools.DotNet.Core.ItemTemplates
Microsoft.WebTools.DotNet.Core.ItemTemplates.Resources
Microsoft.WebTools.Shared
Microsoft.WebTools.Shared.Resources
Microsoft.Windows.UniversalCRT.Msu.7
MS.VS.TestTools.TestPlatform.Legacy.TestTools.Resources
SQLCommon
SQLCommon.Resources
sqlsysclrtypes
sqlsysclrtypes
Win10SDK_10.0.17763

**Comment by heaths** [comment]
If you check the list passed to `-requires`, you'll find you're missing `Microsoft.VisualStudio.Component.VC.Tools.x86.x64`, which corresponds to the component (at least in 16.3 preview) titled "MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.23)". Make sure you have that checked.
