### ISSUE TITLE
vshere - what if enterprise and professional version of Visual Studio is installed on machine

### ISSUE THREAD

**Issue by rguabhi9** [microsoft/vswhere#200]
What would vswhere.exe will return if multiple versions of Visual studio is installed on same machine, like, Enterprise and Professional. Which installation path it will return.

**Comment by heaths** [comment]
All of them, unless you pass `-latest`, which is described in the usage:

```
-latest        Return only the newest version and last installed.
```

**Comment by rguabhi9** [comment]
Thanks heaths, but what if i have to get installation path for specific version like, if i want installation path of enterprise version, when both enterprise and professional version are installed on same machine.

**Comment by heaths** [comment]
The only difference (apart from their license) is what components are included with each. If you have a use-case that requires certain components, use `-requires` with a list of what components you need. Apart from that, it won't matter if it's Professional or Enterprise. But if, for some reason, you really want to specify which you want, use `-product`. Please see `-help` for more usage.

**Comment by rguabhi9** [comment]
Thanks Heaths. It was a great help
