### ISSUE TITLE
vswhere isn't finding Visual Studio 2019

### ISSUE THREAD

**Issue by dewilcox** [microsoft/vswhere#202]
I just installed Visual Studio 2019 version 16.3.1 because it supports .NET 3.0. I don't remember for sure whether vswhere found Visual Studio 2019 before the update, but it definitely isn't finding VS2019 now. The installed location for VS2019 is in the standard place.

Here's the output from vswhere when I run it with no parameters:

> Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]
Copyright (C) Microsoft Corporation. All rights reserved.

> instanceId: 1e9399d2
installDate: 8/21/2019 1:11:16 PM
installationName: VisualStudio/15.9.15+28307.812
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
installationVersion: 15.9.28307.812
productId: Microsoft.VisualStudio.Product.Enterprise
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\devenv.exe
state: 4294967295
isComplete: 1
isLaunchable: 1
isPrerelease: 0
isRebootRequired: 0
displayName: Visual Studio Enterprise 2017
description: Microsoft DevOps solution for productivity and coordination across teams of any size
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.9.15
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2019-08-21T19:11:16.6657878Z
catalog_buildBranch: d15.9
catalog_buildVersion: 15.9.28307.812
catalog_id: VisualStudio/15.9.15+28307.812
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.9.15
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 15
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.9.15+28307.812
catalog_requiredEngineVersion: 1.18.1049.33485
properties_campaignId: 1875101798.1566414581
properties_channelManifestId: VisualStudio.15.Release/15.9.15+28307.812
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe

By contrast, if I specifically request a 2019 version using the command-line parameters `-version "16.0,17.0)"`, I get nothing:
> Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]
Copyright (C) Microsoft Corporation. All rights reserved.

Am I doing something wrong?

**Comment by heaths** [comment]
Does the Visual Studio Installer report any errors for 2019 in the UI? If you run vswhere with `-all` and/or `-prerelease` does it show up? What is the output if it does?

**Comment by dewilcox** [comment]
Thank you @heaths, when I checked the Visual Studio Installer I saw that I needed a restart. After restarting, vswhere finds VS2019 without any issue. Silly mistake on my part, obviously. Thank you for your help!
