### ISSUE TITLE
Powershell will help full

### ISSUE THREAD

**Issue by dhmuralikrishna** [microsoft/vswhere#205]
vswhere is better than VsSetup PowerShell, it will be nice if you can give the powershell that wraps vswhere.

**Comment by heaths** [comment]
They should have the same functionality, except for `-find` which you can do many other ways in PowerShell. If you really want to use vswhere with PowerShell, use `vswhere | convertfrom-json` - the main reason I added the JSON output format. But there's no reason to deprecate one over the other. They have different purpose.

**Comment by dhmuralikrishna** [comment]
vswhere | convertfrom-json is not working. 
1.) Those header values, can get read of that by taking from 4th line. 
2.) installDate format is giving invalid Json

Visual Studio Locator version 2.6.7+91f4c1d09e [query version 2.1.1046.44959]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: b5bac3fb
installDate: 8/8/2019 11:18:53 AM

**Comment by heaths** [comment]
Sorry, I meant `vswhere -format json | convertform-json`. All the same data as VSSetup, though.

**Comment by dhmuralikrishna** [comment]
Thank you so much.
