### ISSUE TITLE
-version 15.0 return 15 and 16

### ISSUE THREAD

**Issue by sinukus** [microsoft/vswhere#206]
This is dumb:

>"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"  -property installationPath -version 15.0
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
**C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise**

Why oh why does it return 2019?

**Comment by heaths** [comment]
Because, like with VSIX extension manifests from which we use the same syntax for version ranges, "15.0" is equivalent to "[15.0,)", which means 15.0 and newer. If you want to constrain major versions, vswhere's usage has an example:

```
  -version arg   A version range for instances to find. Example: [15.0,16.0) will find versions 15.*
```
