### ISSUE TITLE
Current choice of characters for the version range is unfortunate (cmd.exe)

### ISSUE THREAD

**Issue by assarbad** [microsoft/vswhere#208]
I am using `Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]`.

Could you please explain how to wield the argument to `-version` inside of a `for` with backticks?

I am failing at this with all the knowledge of cmd.exe I have. Consider the following. Obviously the closing parenthesis `)` will trip the command processor:

```
:: _VSWHERE points to vswhere.exe ... for this example we can assume the assignment on next line
set _VSWHERE=vswhere.exe
set VSWHERE_RANGE=15.0,16.0
for /f "usebackq tokens=*" %%i in (`"%_VSWHERE%" -products * -format value -property installationPath -version [%VSWHERE_RANGE%)`) do (
    call :SetVar _VCINSTALLDIR "%%i"
)
```

(Error: [backtick] was unexpected at this time.)

`:SetVar` is a "sub" that works around the delayed expansion issue where `setlocal delayedexpansion` isn't available (the script is meant to cater VS versions starting with 2002).

... however, `^)` and `^[` should do the job (trimmed down to `-version ...`):

```
-version ^[%VSWHERE_RANGE%^)
```

... gives me:

```
_VCINSTALLDIR=Error 0x57: Argument expected
```

... which is obviously the output of `vswhere.exe` captured via `for`.

Conveniently (for you ;-)) seemingly no examples for use of `vswhere.exe` mention `-version` and instead resort to `-latest`, which is not suitable for me, however.

Any advice welcome. Otherwise this looks like an oversight regarding the oddities of the command processor.

**Comment by assarbad** [comment]
**NB:** the issue is specific to running from inside a script. I am attaching an example script that resembles closely what I am working on.

[`example.cmd` inside a ZIP file](https://github.com/microsoft/vswhere/files/3795957/example.zip)

**Comment by abelbraaksma** [comment]
As an idea, would it help to use delayed expansion, and / or putting the `(` etc inside variables (with `set local on` and then accessing those variables as `! VAR!` instead of  `%VAR%`.

Another alternative: try piping. 

(not real solutions, but perhaps workarounds) 

(just

**Comment by assarbad** [comment]
@abelbraaksma: Hmm, I actually tried putting the `)` into the variable, but that didn't help. I'll try again to see if it would work somehow.

However, I just noticed that there appears to be a (largely undocumented) means of expressing _exactly_ what I want: `-version 15` and `-version 16` respectively. Alas, from the documentation of [`ISetupHelper::ParseVersionRange`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.setup.configuration.isetuphelper.parseversionrange) it's unclear whether this is even intentional, nor does it document when this quite desirable behavior became available. And since this is a behavior in a COM interface, it's kind of hard to test it. No matter which version of `vswhere.exe` I check out and build myself, the behavior I would rely on is inside a blackbox (a COM class).

Anyway, that said it would be nice if @heaths or someone else from MS would have a comment on whether that behavior with passing plain integers did work in the first available version of the `ISetupHelper` interface or was added later on. Thanks in advance.

**Comment by heaths** [comment]
Yes, `-version 15` is supposed to be equivalent to `-version [15,0)`. The range syntax is the same as that supported by VSIX extensions, which was by design. Unfortunately, escaping in batch is painful, but did you try @abelbraaksma's suggestion using `setlocal enabledelayedexpansion`? The following worked for me:

```batch
setlocal enabledelayedexpansion
set range=[15.0,17.0)

for /f "usebackq delims=" %%i in (`vswhere.exe -prerelease -latest -version !range! -property installationPath`) do (
    echo %%i
)
```

**Comment by assarbad** [comment]
Awesome. Thanks, Heath! Nope, hadn't found the time yet to test it out. But the fact that a simple integer works suits me even better.
