### ISSUE TITLE
Create a tools nuget package

### ISSUE THREAD

**Issue by damianh** [Microsoft/vswhere#21]
It would be very useful if this were shipped to nuget.org as a tools nuget package so build scripts (cake, psake etc) can download and leverage.

**Comment by heaths** [comment]
Can you confirm if how I did https://www.nuget.org/packages/VSIXBootstrapper (from https://github.com/Microsoft/vsixbootstrapper) is sufficient, or if there are specific changes you'd like?

**Comment by damianh** [comment]
I had a peek into that package, looks sufficient indeed. Just the `vswhere.exe` in the `\tools\` folder. Cheers. (The `.props` file isn't needed I think).

**Comment by heaths** [comment]
Thinking about this more, I may instead create a Chocolatey package which not only is a NuGet package, but is installable both by `choco` and `install-package -provider chocolatey`.

**Comment by damianh** [comment]
I think these are separate concerns. Doesn't chocolatey need to run a
script to download the binaries and install it on PATH? A nuget package is
self contained, like xunit.runner.console.

Prob do both.

On 3 Mar 2017 7:23 a.m., "Heath Stewart" <notifications@github.com> wrote:

Thinking about this more, I may instead create a Chocolatey package which
not only is a NuGet package, but is installable both by choco and
install-package
-provider chocolatey.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vswhere/issues/21#issuecomment-283876055>,
or mute
the thread

**Comment by heaths** [comment]
Tools can be contained within the NuPkg used by Chocolatey.

**Comment by damianh** [comment]
@devlead see any issues with this approach wrt to Cake?

**Comment by devlead** [comment]
@damianh @heats you can fetch from chocolatey too with the #tool directive. so Cake wouldn't have any issue with it.
The issue I can see that many corporations whitelist which feeds are allowed, some even only their own proxying nuget.org as upstream.
So IMHO best would be if it was avail on both nuget.org and Chocoloatey, then it would just work for all.

**Comment by heaths** [comment]
Will publish packages soon along with acquisition documentation.

**Comment by heaths** [comment]
See https://www.nuget.org/packages/vswhere. The chocolatey package has to go through moderation before its visible. Same packge either way, except that installing via chocolatey will make sure _vswhere.exe_ is in your `PATH`.

**Comment by devlead** [comment]
@haitch excellent 👍
