### ISSUE TITLE
-version argument causes 'Error 0x57: Argument expected' - when called from batch file

### ISSUE THREAD

**Issue by TFSUser1** [microsoft/vswhere#210]
The following batch file fails with "Error 0x57: Argument expected"
The command "vswhere.exe  -nologo -requiresAny -property installationPath -version [16.0,17.0]" works fine when used alone in a command window.
I'm trying to detect the install folder for VS 2019 and VS 2019 only.
Removing the -version argument causes the error to go away, but... that's not going to give me the results I need.

@ECHO off
@REM SETLOCAL EnableDelayedExpansion
SET FOUNDVCINSTALLDIR=

ECHO "Find Visual Studio 2019 (16.x)"
FOR /f "usebackq tokens=* " %%i IN (`vswhere.exe  -nologo -requiresAny -property installationPath -version [16.0,17.0]`) DO (
   ECHO "Line: %%i"
   SET FOUNDVCINSTALLDIR=%%i
)

IF NOT DEFINED FOUNDVCINSTALLDIR (
   ECHO "Visual Studio 2019 Installation Not Found!"
   EXIT /B 1
)

IF NOT EXIST "%FOUNDVCINSTALLDIR%\" (
   ECHO "Error: Visual Studio 2019 Install Folder Not Found!"
   EXIT /B 1
) ELSE (
   ECHO "Success: Visual Studio 2019 Install Folder Found"
   ECHO "FOUNDVCINSTALLDIR==%FOUNDVCINSTALLDIR%"
)

**Comment by heaths** [comment]
This is a problem with batch parsing and not the tool. You can put the version in quotes like so:
```cmd
for /f "usebackq tokens=*" %%i in (`vswhere.exe -property installationPath -version "[16.0,17.0)"`) do (
    echo %%i
)
```

**Comment by TFSUser1** [comment]
> This is a problem with batch parsing and not the tool. You can put the version in quotes like so:
> for /f "usebackq tokens=*" %%i in (`vswhere.exe -property installationPath -version "[16.0,17.0)"`) do (
>     echo %%i
> )

Thank you brother! That works. I've also noticed that this works:
FOR /f "usebackq tokens=* " %%i IN (`vswhere.exe -nologo -version 16.0 -property installationPath`) DO (
   ECHO "Line: %%i"
   SET FOUNDVCINSTALLDIR=%%i
)

**Comment by heaths** [comment]
You can do that, but it's not equivalent. "[16.0,17.0]" means get me all 16.* and 17.* versions. Just "16.0" is equivalent to "[16.0,)" which means 16.* or newer.

**Comment by IkeStarnes** [comment]
> You can do that, but it's not equivalent. "[16.0,17.0]" means get me all 16.* and 17.* versions. Just "16.0" is equivalent to "[16.0,)" which means 16.* or newer.

I only want 16.x, VS 2019.

**Comment by heaths** [comment]
Use "[16.0,17.0)" then (closing parenthesis, not square bracket).

**Comment by TFSUser1** [comment]
Thanks!
