### ISSUE TITLE
Find-VC needs update for Visual Studio 2019

### ISSUE THREAD

**Issue by PerMildner** [microsoft/vswhere#215]
https://github.com/microsoft/vswhere/wiki/Find-VC was last updated 2017. Since then VS 2019 has been released.

Also, the `vsdevcmd.bat` in VS 2019 seems to set up the environment so that a VS 2017 `cl.exe` is found instead of the newest VS 2019 `cl.exe`. This seems to make `vsdevcmd.bat` less useful as a way to find the C compiler. In either case, this makes the current Find-VC documentation not very useful with Visual Studio 2019.

**Comment by heaths** [comment]
Worked for me with what I have installed. Can you be more specific about what doesn't work for you?

**Comment by PerMildner** [comment]
Indeed. I do not know what happened. Sorry about the noise.
