### ISSUE TITLE
vswhere.exe can't find VS2017 version 15.9.21 with -sort

### ISSUE THREAD

**Issue by LilyWangL** [microsoft/vswhere#216]
I used the command to find VS on cmd, and I got the error as below:
```
C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere.exe -prerelease -legacy -products * -sort -utf8 -property installationPath
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.18.21.37008]
Copyright (C) Microsoft Corporation. All rights reserved.

Error 0x57: Unknown parameter: sort
```
I removed `-sort` and try again, and it gave me the correct output.
```
C:\Program Files (x86)\Microsoft Visual Studio\Installer>vswhere.exe -prerelease -legacy -products * -utf8 -property installationPath
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
C:\Program Files (x86)\Microsoft Visual Studio 14.0\
```
My VS2017 version is 15.9.21, who can help to take a look?

**Comment by heaths** [comment]
`-sort` was added in a later version. Passing `-h` will show you what is available.

You can download a newer version from this site, or make a request on https://developercommunity.visualstudio.com to update it. But if you have scripts that require specific functionality, it's recommended you download the version you need. It's available via nuget, chocolatey, and this site from the *Releases* tab.
