### ISSUE TITLE
Support for VS2019 preview

### ISSUE THREAD

**Issue by damon-kwok** [microsoft/vswhere#218]
`vswhere` does not work on vs2019 preview

**Comment by heaths** [comment]
Did you pass `-prerelease` on the command line? Please pass `-?` for additional options.

**Comment by damon-kwok** [comment]
@heaths 
This bug appears in the `toolchains of the pony language`. I think that the -prerelease mechanism can be removed, so that vswhere can find the Preview version by default. it can be convenient for other toolchains to call.

**Comment by damon-kwok** [comment]
thanks
