### ISSUE TITLE
vswhere -all does not find the installation of BuildTools

### ISSUE THREAD

**Issue by damianh** [Microsoft/vswhere#22]
I have installed:

 1. VS Enterprise in  `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin`
 2. [BuildTools](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15) in `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin`

Running `vswhere` is discovering 1, but not 2.

### Actual results
```
PS C:\temp> .\vswhere.exe -all
Visual Studio Locator, version 1.0.14-beta
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: db7eafa1
installDate: 29/01/2017
installationName: VisualStudio/15.0.0-RC.4+26206.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
installationVersion: 15.0.26206.0
displayName: Visual Studio Enterprise 2017 RC
description: Microsoft DevOps solution for productivity and coordination across teams of any size
PS C:\temp>
```

### Expected results

Listing both installation of MSBuild.

**Comment by damianh** [comment]
However, if I specify the `BuildTools` product explicitly, it seems to find it:

```
PS C:\temp> .\vswhere -products 'Microsoft.VisualStudio.Product.BuildTools'
Visual Studio Locator, version 1.0.14-beta
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: f252c89a
installDate: 02/03/2017
installationName: VisualStudio/15.0.0-RC.4+26206.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
installationVersion: 15.0.26206.0
displayName: Visual Studio Build Tools 2017 RC
description: The Visual Studio Build Tools allows you to build native and managed MSBuild-based applications without requiring the Visual Studio IDE. There are options to install the Visual C++ compilers and libraries, MFC, ATL, and C++/CLI support.
```

**Comment by heaths** [comment]
That is by design. `-All` has nothing to do with the products, but rather the instance state. From the usage information,

```
Usage: vswhere.exe [options]

Options:
  -all           Finds all instances regardless if they are complete.
  -products arg  One or more products to find. Defaults to Community, Professional, and Enterprise.
```

**Comment by damianh** [comment]
ah, understood, thx.

**Comment by KindDragon** [comment]
Maybe we can add separate argument (`-products any`) that will do this without specifying all products:
```
$ids = 'Community', 'Professional', 'Enterprise', 'BuildTools' | foreach { 'Microsoft.VisualStudio.Product.' + $_ }
$instance = vswhere -latest -products $ids -requires 'Microsoft.Component.MSBuild'
```

**Comment by KindDragon** [comment]
Why BuildTools excluded from default products list?

**Comment by heaths** [comment]
Because this tools is primarily focused on VS. The new installer is capable of installing many different products and we'll be adding more over time.

**Comment by KindDragon** [comment]
How about new key `products *`?

**Comment by heaths** [comment]
Possibly. Please file a separate issue. This issue was about `-all` not doing what was expected, but was actually by design.
