### ISSUE TITLE
vswhere doesn't work with multiple arguments to -requires

### ISSUE THREAD

**Issue by asklar** [microsoft/vswhere#220]
How can I use `vswhere` to ensure an installation provides a set of workloads? the help says you can pass multiple arguments to `-requires` but I don't get the results I expect. Here's what I tried:

```
$workloads = @( 'Microsoft.Component.MSBuild', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64', 'Microsoft.VisualStudio.ComponentGroup.UWP.Support');

& $vsWhere -version 16 -requires ($workloads -join ';')
& $vsWhere -version 16 -requires ($workloads -join ' ')
& $vsWhere -version 16 -requires ($workloads -join ' -requires ')
```

All of these return an empty response. However if I only pass any one workload, this works fine.

VSWhere version:
Visual Studio Locator version 2.7.1+180c706d56 [query version 2.3.2200.14893]

**Comment by heaths** [comment]
They are space separated, but defaults to an AND query. If you want an OR query, use -requiresAny.

**Comment by asklar** [comment]
@heaths thanks for the reply, it's not exactly what I was asking :) 
I know about -requires and -requiresAny. What I'm seeing though is that vswhere.exe doesn't _properly_ parse its command line arguments:

![image](https://user-images.githubusercontent.com/22989529/81611391-d0265180-938f-11ea-9346-60be69d6b8c4.png)

So I think it expects every argument to -requires to be in its own argv element instead of parsing out the spaces which is what I assume happens when I pass `$workloads -join ' '` (i.e. that it gets passed as one argv).

**Comment by heaths** [comment]
PowerShell in some cases (I'm a LONG time user going back to "Monad", and it's been my daily driver since), but have still never quite figured out when what works when. Try just typing the individual arguments instead of having a separate scope to unroll the arguments. Ultimately, the arguments need to be passed individually. As an expression, that may not be happening when invoking a string command. Multiple arguments definitely works otherwise. Not only do I have tests for it, but build systems are using it as well.

**Comment by heaths** [comment]
I don't have UWP installed, but with the other two the expression works for me:

```powershell
$workloads = @('Microsoft.Component.MSBuild', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64')
$vswhere = (gcm vswhere).Path
& $vswhere -version 16 -requires ($workloads -split ' ') -prerelease # I only have preview installed
```

I'm using the latest version, 2.8.4, but I haven't changed anything in that code path for quite a while.

**Comment by asklar** [comment]
thanks @heaths - yes, the following variants work fine:
- `-split ' '`
-  just passing `$workloads` directly
-  spelling out the options

But passing `-join ' '` is kind of broken. I imagine this is just a quirk of PS.

**Comment by heaths** [comment]
Sorry, yes. `-split` was unnecessary. The default `$OFS` is a space, so no need to `-join` anyway. So just this works:
```powershell
& $vswhere -version 16 -requires ($workloads) -prerelease
```

Not sure why `-join` doesn't work, but it not a bug in vswhere - something quirky with PowerShell. Hope that helps.
