### ISSUE TITLE
Typo in help text

### ISSUE THREAD

**Issue by uljo2** [microsoft/vswhere#221]
This is a really small one, but there is a typo in the help.
version argument range is
[15.0,16.0)
should be
[15.0,16.0]

BR Ulf

**Comment by heaths** [comment]
That is valid syntax, which means 15.0 inclusive to 16.0 exclusive, which is how it reads:
```
 -version arg   A version range for instances to find. Example: [15.0,16.0) will find versions 15.*.
```

**Comment by uljo2** [comment]
Sorry my bad.
It works if you execute in a Cmd prompt, however I got an error message when executing in PowerShell. If using [15.0 16.0] (a closing square bracket) it works for both...

Doing:
vswhere.exe -version "[15.0,16.0)" -property productPath
it works for PS as well.

**Comment by heaths** [comment]
Yes, PowerShell will treat that as the close of an inner scope, which is a language feature of PowerShell.
