### ISSUE TITLE
Publish package for winget

### ISSUE THREAD

**Issue by heaths** [microsoft/vswhere#222]
https://github.com/microsoft/winget-cli appears to be the new attempt where OneGet failed. To support it, consider publishing a package to https://github.com/microsoft/winget-pkg once either microsoft/winget-cli#202 or microsoft/winget-cli#182 is supported for this portable, statically-linked application.

**Comment by tobil4sk** [comment]
Any updates on this? Being able to install via winget would be quite convenient.

**Comment by tobil4sk** [comment]
Ah right, many thanks! I assumed it still wasn't available since it wasn't mentioned in the wiki:
https://github.com/microsoft/vswhere/wiki/Installing

**Comment by heaths** [comment]
Thanks for the heads up. I updated that page.

**Comment by heaths** [comment]
Resolved for version 3.0.3. Closing in lieu of #278
