### ISSUE TITLE
version number conventions

### ISSUE THREAD

**Issue by stefanseefeld** [microsoft/vswhere#224]
Using the documented method of calling `vswhere ... -property installationPath` and looking in that path for the file `Microsoft.VCToolsVersion.default.txt` to report the version, I'm able to discover a version such as "14.26.28801".
`vswhere` also reports a "catalog_productDisplayVersion" property which has the value "16.6.5".

What is the meaning of these two "version" numbers, and how do they relate ? 
And how can I look up the latter using the former (or the installationPath) ?

**Comment by heaths** [comment]
Visual Studio is comprised of hundreds of tools and packages that have their own version numbers, and is best described by those components' documentation.

The catalog version - anything prefaced with "catalog_" - is information about the catalog (manifest) of packages that can be installed, and typically correspond to the Visual Studio version number, e.g. Visual Studio 16.6.5. The APIs that vswhere use are [documented](https://docs.microsoft.com/dotnet/api/microsoft.visualstudio.setup.configuration) and probably the best source of that information.
