### ISSUE TITLE
No product is found, although they are indeed installed

### ISSUE THREAD

**Issue by IngwiePhoenix** [microsoft/vswhere#225]
Using `vswhere -all -format json` or any other variation really doesn't return anything at all. Yet:

```
C:\Program Files (x86)\Microsoft Visual Studio>dir
 Datenträger in Laufwerk C: ist Windows HD
 Volumeseriennummer: 22DC-E964

 Verzeichnis von C:\Program Files (x86)\Microsoft Visual Studio

25.07.2020  02:08    <DIR>          .
25.07.2020  02:08    <DIR>          ..
04.05.2020  12:58    <DIR>          2017
28.10.2019  00:46    <DIR>          2019
25.07.2020  02:08    <DIR>          Installer
04.05.2020  13:13    <DIR>          Shared
               0 Datei(en),              0 Bytes
               6 Verzeichnis(se), 132.471.779.328 Bytes frei
```

So clearly, there is something wrong. I installed 2019 through the installer and 2017 through chocolatey.

Is there something I am overlooking?

**Comment by heaths** [comment]
Are they prereleases? Try `-prerelease`. If nothing still comes up, please run https://aka.ms/vscollect and file an issue on https://developercommunity.visualstudio.com for support with the installation (this is just a utility that enumerates the information).

**Comment by slang25** [comment]
I have found the same thing on my build agent, we have plenty of non-prerelease installs (and the VS Installer displays them), but vswhere displays nothing.

**Comment by heaths** [comment]
Did you install Build Tools on your build agent? If so, you have to use `-products *`. By default, only VS Community, Professional, and Enterprise are enumerated. This is documented in `-?`.

**Comment by slang25** [comment]
Yes, that was exactly it, thanks for your help 😃

**Comment by IngwiePhoenix** [comment]
> Did you install Build Tools on your build agent? If so, you have to use `-products *`. By default, only VS Community, Professional, and Enterprise are enumerated. This is documented in `-?`.

Yes. All those versions are installed as Community. I'll try the `-products "*"` flag and see what happens.

**Comment by IngwiePhoenix** [comment]
```
C:\Users\ingwi\work>vswhere -all -products "*"
Visual Studio Locator version 2.8.4+ff0de50053
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Users\ingwi\work>
```

Guess I'll head to VSCollect...

**Comment by heaths** [comment]
You didn't specify `-prerelease` as well. All those switches do different things, as documented in `-?`.

**Comment by IngwiePhoenix** [comment]
Just retried, still empty. Going to run VSCollect now and put out what I got.

**Comment by IngwiePhoenix** [comment]
[vslogs.zip](https://github.com/microsoft/vswhere/files/5042170/vslogs.zip)
Posting this here for reference.

I tried to install additional Visual Studios for more compilers - and to see if VSWhere starts picking up the other products then. But, no luck whatsoever...

**Comment by heaths** [comment]
Your vslogs.zip doesn't contain the registration files that are under %ProgramData%, which explains the problem. Did you install everything via chocolatey? What packages names, so we can help them fix them? Not only is that registration data required for vswhere to function, but features of Visual Studio and third-party extensions as well.

I'm closing this as external, but please make sure to provide all details to the VS Setup team including which chocolatey packages you used, and whether you redirected, deleted, or did anything with VS files under %ProgramData% after installing.

The recommended way to install VS is from https://www.visualstudio.com. There is silent installation help available. You shouldn't have this issue if you use the proper installer.
