### ISSUE TITLE
Get version of build tools

### ISSUE THREAD

**Issue by tommitytom** [microsoft/vswhere#227]
Is it possible to use this tool to get the version of the build tools - such as `14.28.29333`? 

This folder exists for me at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333` and was installed with `MSVC v142 - VS 2019 - C++ x64/x86 build tools (v14.28)`.  I'd like to be able to detect which versions are installed.

**Comment by heaths** [comment]
That is beyond the scope of vswhere. It can give you the install path, and from there you could enumerate the subdirectories under the subdirectory you referenced above. vswhere is for discovering which instances are installed, were they are installed, and other metadata such as source catalog.
