### ISSUE TITLE
[Documentation] Better document the -products * switch

### ISSUE THREAD

**Issue by Chronial** [microsoft/vswhere#235]
The  `-products *` switch that is needed to find Build Tools would benefit from better documentation.

It is not mentioned in the examples. The [Find MSBuild](https://github.com/microsoft/vswhere/wiki/Find-MSBuild) page used to contained it, but it was [removed from there in January 2019](https://github.com/microsoft/vswhere/wiki/Find-MSBuild/_compare/62adac8eb22431fa91d94e03503d76d48a74939c...bf9b308c1f17569403be1bca9c5c29aa8ea1e017).

The `vswhere /?` built-in help IMO doesn't do a very good job of explaining this switch. At least to me it is rather unexpected that vswhere will only find a subset of usable build tools by default. The cli help should clearly state this restriction and it should be stated that `-products *` is required to find VS Build Tools installation.

This seems to be an issue for many people, see #22, #225, #229, #230 and many of the external issues linking against #8.

----------------------------

This issue is focused on the documentation, but I would like to mention that the default behavior of vswhere is rather counterintuitive. The Readme states:
> vswhere is designed to be a redistributable, single-file executable that can be used in build or deployment scripts to find where Visual Studio - or other products in the Visual Studio family - is located. For example, if you know the relative path to MSBuild, you can find the root of the Visual Studio install and combine the paths to find what you need.

It is exactly this use case that we are using it for: Finding msbuild on our build servers. Since we don't need the IDE there, we only have the build tools installed. The fact that vswhere needs an extra switch to work in this (seemingly simple) setup is surprising to me.

PS: Thanks for making this awesome tool available. Even with our initial struggles, it is extremely helpful :heart:.

**Comment by heaths** [comment]
Build Tools is not a complete build toolset, and didn't fit the original requirements back when this was created. Even if Build Tools did fit the requirements now, changing the behavior now would be a breaking change. There are still tools missing that install with the VS IDE, and build automation everywhere could be broken.

Can you clarify what's not clear for the -products switch when it says that Community, Professional, and Enterprise are found by default? Build Tools is a separate SKU.

**Comment by Chronial** [comment]
> Build Tools is not a complete build toolset, and didn't fit the original requirements back when this was created. Even if Build Tools did fit the requirements now, changing the behavior now would be a breaking change. There are still tools missing that install with the VS IDE, and build automation everywhere could be broken.

That makes sense of course, which is why I tried to classify this as a documentation issue. Is there a reason not to have the `-products *` flag in the "Find MSBuild" example?

> Can you clarify what's not clear for the -products switch when it says that Community, Professional, and Enterprise are found by default? Build Tools is a separate SKU.

A lot of users are probably going to approach vswhere without solid knowledge of the VS infrastructure. That definitely was my position when I first had this problem. The current doc only makes sense if you are aware that "Build Tools" is something disjunct from "Community, Professional, and Enterprise". I was not aware of this and thought "I'm not sure, but we are using either Profession or Enterprise".

You could of course just classify that as pure user error, but I think there's value in making vswhere more useful to people who have little understanding of the topic at large and just want to find msbuild.

**Comment by heaths** [comment]
The SKU names are on the download page, since you are directed to download the bootstrapper for a specific SKU. The usage is explicit about which SKUs are scanned by default, and changing the behavior is a breaking change.

As for the samples, I will call out that this doesn't find Build Tools by default, but the samples are meant to highlight a specific purpose - not account for every possibility. For example, even though you can find MSBuild from Build Tools in much the same way, some targets may not be supported in Build Tools because Build Tools is not a complete VS. MSBuild is just the runner. What is supported by your project and other targets matters entirely on which components are installed.
