### ISSUE TITLE
Batch examples with -version <range>

### ISSUE THREAD

**Issue by KUGA2** [microsoft/vswhere#237]
Thankfully, you got some examples on usage. e.g here:
https://github.com/microsoft/vswhere/wiki/Find-VC

However, no example shows how to use a `-version` range in Batch. This is hard, since `[]()` are keywords in batch and need to be escaped. I could not figure out how.

How do I escape `[]()` in batch? Can you ad this to the examples?

**Comment by heaths** [comment]
Surround the argument in double quotes e.g., `-version "[16.0,17.)"`. This is true of any string in batch scripts (or in PowerShell, or any scripting language really) that contain special characters.

I'll consider it for samples somehow - maybe just general ones in the wiki - but I'm trying to keep samples limited to the exact task being demonstrated. How people add other parameters really depends on their use case. I was intentionally not trying to suggest any particular methodology apart from what the example intends e.g., finding the VC toolset you want to use.

**Comment by KUGA2** [comment]
This does not work when you have spaces in vswhere path :(

```
@echo off

set VSWHERE="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"

for /f "usebackq tokens=*" %%i in (`%VSWHERE% -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do (
  set InstallDir=%%i
)

if exist "%InstallDir%\Common7\Tools\vsdevcmd.bat" (
  "%InstallDir%\Common7\Tools\vsdevcmd.bat" %*
)
```

Add `-version "[16.0,17.0)"`, and it will fail:
```
>vcbuild.cmd
Der Befehl "C:\Program" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
```
(_Command wrong typed or not found_., sorry german Windows version)

**Comment by KUGA2** [comment]
My colleague figured it out:
` -version [16.9^,17.0^)` works.

Please consider documenting this.

**Comment by KUGA2** [comment]
> 
> 
> This isn't really the place to learn about escape patterns in batch scripts, though. The hat `^` symbol is well-documented for batch scripts elsewhere.

I agree. I still think, its worth adding this to examples.
There are many options (^ or \ (at `[,)`), in quotes, as a variable) and it was hard to find the correct permutation.

**Comment by triplef** [comment]
I second this request for adding documentation using the `-version` parameter in a Batch script using `for /f`, as it’s surely a common scenario for using vswhere.

Ideally there should also be an example that specifies the version in a variable, see https://github.com/microsoft/vswhere/issues/208#issuecomment-548610036.

**Comment by heaths** [comment]
https://github.com/microsoft/vswhere/wiki/Examples#escape-versions-in-batch-scripts

**Comment by triplef** [comment]
Thank you @heaths!
