### ISSUE TITLE
Not compatible with older versions?

### ISSUE THREAD

**Issue by poke** [Microsoft/vswhere#24]
I was hoping that I could rely on this tool to find any version of Visual Studio. But apparently it only works with the Visual Studio 2017 (probably and later) but not with e.g. Visual Studio 2015.

It would be cool if there was some legacy detection so that this tool could be used as a single utility to find installed Visual Studio versions—regardless of whether they are new or old.

**Comment by heaths** [comment]
Thanks for the feedback. It had been a consideration but almost none of the other parameters (specifically `-requires` and partly `-products` that would need a mapping) would make sense and may give unexpected results. It's recommended to use the old registry detection.

That said, I'd be interested in your scenario. We haven't closed the door in this and understanding how people might use or would help.

**Comment by poke** [comment]
I understand that it would only have a reduced utility compared to VS2017. However, I was hoping that vswhere could be used as a single query tool without having to add hardcoded registry checks *just in case* an old version is still present.

Btw. are there any plans to ship this tool with Visual Studio, so that one can depend on it to exist (when there is a compatible version of VS installed anywhere), or are we supposed to bundle this tool into our applications when we need this detection?

**Comment by heaths** [comment]
We are discussing shipping it, but not for RTW and have no definite plans otherwise, so you might considering either redist'ing it or downloading as needed. I'm also adding support for both a NuGet package and a Chocolatey package (same package, actually) for added ease of acquisition.

**Comment by JFLarvoire** [comment]
+1 for this request: I'm also maintaining a library that strives to be compatible with all versions of Visual Studio. Finding them is indeed difficult and slow now. And VS 2017 just broke the script that did it.
Being able to rely on vswhere for all of them would be great!

**Comment by heaths** [comment]
This will be fixed in the next release.
