### ISSUE TITLE
vswhere doesn't find MSBuild on Windows 11 ARM64

### ISSUE THREAD

**Issue by dennisameling** [microsoft/vswhere#241]
Windows build: 22000.100 (Windows 11 Beta)

I have the Visual Studio 2019 Build Tools installed on my Surface Pro X (Windows ARM64). I just upgraded to Windows 11 beta (build 22000.100) and now tools like `vswhere` can't find `MSBuild.exe` anymore. I tried reinstalling the 2019 Build Tools to no avail.

MSBuild is installed at `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` and is found correctly by tools like CMake. 

The following command doesn't output anything:

```
PS C:\Program Files (x86)\Microsoft Visual Studio\Installer> .\vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
```

`.\vswhere -all` also isn't particularly helpful 😅 

```
PS C:\Program Files (x86)\Microsoft Visual Studio\Installer> .\vswhere -all
Visual Studio Locator version 2.7.1+180c706d56 [query version 2.7.3111.17308]
Copyright (C) Microsoft Corporation. All rights reserved.
```

Since I'm pretty sure this broke after the Windows 11 Beta upgrade, I consider this a bug for now. Please let me know if that's not the case or if I can provide additional logs.

Here's the packages I have installed:

```JSON
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.CoreBuildTools",
    "Microsoft.VisualStudio.Workload.MSBuildTools",
    "Microsoft.VisualStudio.Component.Windows10SDK",
    "Microsoft.VisualStudio.Component.VC.CoreBuildTools",
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
    "Microsoft.VisualStudio.Component.Windows10SDK.19041",
    "Microsoft.VisualStudio.Component.VC.CMake.Project",
    "Microsoft.VisualStudio.Component.TestTools.BuildTools",
    "Microsoft.VisualStudio.Component.VC.ASAN",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.VC.CoreIde",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.Workload.VCTools",
    "Microsoft.VisualStudio.Component.VC.Tools.ARM64",
    "Microsoft.VisualStudio.Component.VC.ATL.ARM64",
    "Microsoft.VisualStudio.Component.VC.MFC.ARM64"
  ]
}
```

Thanks in advance! 😊

**Comment by dennisameling** [comment]
Just found out this has to do with PowerShell x64 not finding a class that reports whether VS is installed:

```
PS C:\repos\node-gyp> powershell -ExecutionPolicy Unrestricted -Command "Add-Type -Path .\lib\Find-VisualStudio.cs; [VisualStudioConfiguration.Main]::PrintJson()"
Exception calling "PrintJson" with "0" argument(s): "Retrieving the COM class factory for component with CLSID {177F0C4A-1CD3-4DE7-A32C-71DBBB9FA36D} failed due to the following error: 80040154 Klasse is niet geregistreerd (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))."
At line:1 char:44
+ ... b\Find-VisualStudio.cs; [VisualStudioConfiguration.Main]::PrintJson()
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException
```

This works correctly in PowerShell x86 on Windows ARM64. Reported the issue to the VS team: https://developercommunity.visualstudio.com/myfeedback?port=1025&fsid=ede5705d-c496-4469-af0b-ca8275cbb656&entry=myfeedback

So I'm closing the issue here 👍🏼

**Comment by heaths** [comment]
Build Tools is not included by default. You have to pass `-products *` (see #8). The usage `-?` text says only Community, Professional, and Enterprise are included by default.

vswhere.exe is 32-bit only, so it can load the COM server just fine. Loading the COM server yourself in an ARM64 host is a known limitation being considered currently, to either compile the COM server for ARM64 or create a surrogate. These two issues are separate.

If you want to find Build Tools in addition to any Visual Studio SKU, just pass `-products *` along with any other command lines. See `-?` for more information.

**Comment by dennisameling** [comment]
Thanks for the info, great to know. I got distracted by the `-all` switch and expected that to simply return all installed products. It indeed works with `.\vswhere -products * -format json -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe` - thank you!
