### ISSUE TITLE
Finding clang+llvm the right way

### ISSUE THREAD

**Issue by awakecoding** [microsoft/vswhere#242]
I have been trying (and failing) for hours to figure out how to properly call vswhere.exe to find the clang+llvm install path corresponding to the Microsoft.VisualStudio.Component.VC.Lllvm.Clang component.

Here is what I want to query for: find the latest clang+llvm installation path, with a preference for a specific host architecture (x64 over x86). I do not desire anything beyond finding this installation path, I just want to use it the same way I would with the llvm.org clang+llvm distribution for Windows that is installed in "C:\Program Files\LLVM" by default. From that install path I should be able to find clang.exe and other tools under the bin directory for manual invocation outside of MSVC. My first use case is to find clang.exe in a Rust build script to compile Windows ARM64 assembly files, which is much easier than trying to use the limited armasm64.exe MSVC tool.

The best query I could come up with is not very satisfying and returns both the x86 and x64 builds of clang+llvm:
`vswhere.exe -latest -requires Microsoft.VisualStudio.Component.VC.Llvm.Clang -find 'VC\Tools\Llvm\**\bin\clang.exe'`

Here is a screenshot showing the location of clang.exe in both x86 and x64 visual studio command prompts:

![vswhere_clang_llvm](https://user-images.githubusercontent.com/295841/128870972-8ae169d9-0c3c-42d7-a075-a23ad7fa0d3b.png)

The ideal output for the query should be:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm\x64`

The x86 clang+llvm is less desirable, but would still be useful on Windows 10 on ARM where x64 emulation is not available:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\Llvm`

I haven't found a way to query just the clang+llvm install path for a given host architecture. The visual studio command prompt is actually much easier in that regard, but I don't feel like wrapping vcvarsall.bat to obtain PATH modifications and then figuring out the install path from the detection location of clang.exe.

Surely vswhere.exe can solve this in a much cleaner manner? Something like "find latest clang+llvm install path, x64". Thanks a lot!

**Comment by heaths** [comment]
vswhere is for finding VS - not individual components, for which we do not store enough information. If you want to find a particular architecture for LLVM you can pass that as part of the path, e.g. `-find VC\Tools\LLVM\bin\clang.exe`. But if you already know the path, why bother? Get the root installation path and just concatenate either path. `-find` was meant for some tools that have frequently-changing paths like the VC compiler, though they did add a better way that requires a few steps but helps you find the version you want. Our wiki has more information.

**Comment by awakecoding** [comment]
Does that mean vswhere.exe is not really a modern vcvarsall.bat replacement, but really just a command-line tool to find the Visual Studio installation root path (VSINSTALLDIR) from which the other MSVC environment variables and paths can be derived? In other words, vswhere is to MSVC what xcode-select is to Xcode, nothing more?

The example showing a rather complex command to find msbuild using vswhere gives the impression that it could (and should) be used for more than just the root installation path. I figured, why would it not simply give me the root installation path of MSVC clang+llvm?

vswhere is commonly used in a lot of build scripts now, and I have mostly seen it used to find VSINSTALLDIR and msbuild.exe, not much beyond that. I have used it myself to reconstruct what vcvarsall.bat does inside a cmake toolchain file: https://github.com/Devolutions/CBake/blob/master/windows-msvc.toolchain.cmake

Now that I know, I will keep my vswhere usage to the bare minimum and build my own detection code on top of it - it's not a vcvarsall.bat replacement at all.

**Comment by heaths** [comment]
It always was a way to find the root installation - never as a replacement for vcvars. It's used in a lot of build tools, yes, to find the root from which to build on. You can use it to find vcvars, which we have a sample in our wiki.

Dev15 uses a completely different install that enables installing multiple instances of the same version (or minor/patch updates) to different directories, useful for trying out new features or upgrading a toolset without affecting other project requirements. vswhere is useful to help find an instance that meets your needs, like a release (default) or prerelease with components X, Y, and Z.

**Comment by awakecoding** [comment]
Thanks for the clarification. May I suggest that the vswhere readme make its purpose clearer? Yes, it does state it is a Visual Studio locator, but the part about finding specific tools like msbuild may give the impression that it's more than that - a simple mention that vswhere is *not* a vcvarsall.bat replacement would suffice in my mind. I understand it may look like I'm probably the only one who got confused, but it wouldn't hurt just to state what it isn't with one sentence.

**Comment by awakecoding** [comment]
I came up with a clean-enough MSVC clang detection technique that only relies on locating the Visual Studio root to then reconstruct the same environment variables normally provided by vcvarsall.bat, and end up with the proper LLVM_ROOT. Feel free to add it to your vswhere samples if you wish, it can be useful to other people:

```
$VSINSTALLDIR = $(vswhere.exe -latest -requires Microsoft.VisualStudio.Component.VC.Llvm.Clang -property installationPath)
$VCINSTALLDIR = Join-Path $VSINSTALLDIR "VC"
$LLVM_ROOT = Join-Path $VCINSTALLDIR "Tools\Llvm\x64"
$Env:PATH += ";$LLVM_ROOT\bin"
```

![image](https://user-images.githubusercontent.com/295841/129037516-feef4f8c-8a19-4a0b-bbbb-a609caefd4ad.png)
