### ISSUE TITLE
vswhere could not detect VS2022 (preview)

### ISSUE THREAD

**Issue by shx0000123** [Microsoft/vswhere#249]
As I said, vswhere could not detect the VS2022.

**Comment by MaxBosse** [comment]
From what I can see, VS2022 is not a pre-release anymore but vswhere still does not detect it in my case. Was there an update already to remove the requirement of -prerelease?

**Comment by heaths** [comment]
Depends what channel you're in. If you installed from the Preview channel, you'll always have a prerelease unless you switch channels, which you can do now in the installer.

If you're not on the Preview channel, please open a separate bug with more information including the output from `vswhere -all -prerelease`.
