### ISSUE TITLE
vswhere does not detect Visual Studio 2022 installations

### ISSUE THREAD

**Issue by japarson** [Microsoft/vswhere#250]
## Problem
vswhere.exe only returns information about Visual Studio 2019 and below.

## Repro
I have two instances of VS 2022 installed on my machine:
![image](https://user-images.githubusercontent.com/59936622/138999989-a81c552f-65d3-4c6f-81f6-d68409db8d98.png)

And 1 instance of VS 2019:
![image](https://user-images.githubusercontent.com/59936622/139000053-5e560627-cba6-4d1f-84d0-3d569a74ddf0.png)

However, vswhere only returns information about the VS 2019 installation:
![image](https://user-images.githubusercontent.com/59936622/139000186-37e6f381-3730-4c3b-894e-a6ecd48ef8f2.png)

This behavior repros with both `2.8.4` and `2.9.3-21bcdb639c`.

**Comment by cbernth** [comment]
@heaths I'm tracing an issue where vswhere doesn't detect Visual Studio Build Tools 2022

This is using the version bundled in [azure-pipelines-agent](https://github.com/microsoft/azure-pipelines-agent) v2.202.1
https://github.com/Microsoft/azure-pipelines-agent/releases
![image](https://user-images.githubusercontent.com/32438452/164036222-f6e4ae8c-39d3-4553-99a9-6b248b159e27.png)

![image](https://user-images.githubusercontent.com/32438452/164036610-51521a21-0bbf-437f-9c2b-f7a1e17313fd.png)

BuildTools 2022 are installed:
![image](https://user-images.githubusercontent.com/32438452/164036430-8b927100-133e-483e-b295-e6550293d8d4.png)

![image](https://user-images.githubusercontent.com/32438452/164034591-d4877b81-6f41-49a5-9363-53bc24259523.png)

When running on another server with both Build Tools 2019 and 2022 I get this:
![image](https://user-images.githubusercontent.com/32438452/164035811-807ac6e3-7a4e-4616-9b99-dcc3a5d7e3e1.png)

Adding the -prerelease parameter gives an error:
![image](https://user-images.githubusercontent.com/32438452/164037229-3748c9a0-abe3-4714-88cc-49c0e8a2052c.png)

What is the proper way to have vswhere detect the VS Build Tools 2022?

**Comment by cbernth** [comment]
Thanks for the prompt reply @heaths :). Unfortunately, for me it still fails to detect VS 2022 BuildTools with the latest vswhere.exe from the release page:

![image](https://user-images.githubusercontent.com/32438452/164169109-6d85a676-5b77-4d04-bcb8-c95614f42558.png)

![image](https://user-images.githubusercontent.com/32438452/164169161-fc050ad5-56b0-4393-a756-4823710a6753.png)

It also fails to detect it when there is only one BuildTools 2022 installed on the machine.

**Comment by heaths** [comment]
Yes, please open a new bug. But in your case, you specified `-version [16.0,17.0) -latest`. That version will only detect 16.x and will only show the latest. Seems it's working exactly as you specified.

See `vswhere -help` for documentation on the `-version` parameter.
