### ISSUE TITLE
Visual Studio 2022, Detect Microsoft.VisualStudio.Component.VC.Tools.x86.x64 for 142

### ISSUE THREAD

**Issue by TheOneRing** [microsoft/vswhere#251]
In order to locate the build tools for previous releases I used the following command.

For 2017:
```
& "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"  -property installationPath -nologo -latest -version "[15,16)" -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
```

For 2019:
```
& "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"  -property installationPath -nologo -latest -version "[16,17)" -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
```

This seems to still work for the 2022 payload:
```
& "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"  -property installationPath -nologo -latest -version "[17,18)" -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
C:\Program Files\Microsoft Visual Studio\2022\Community
```

But not for the old build tools, which worked perfectly fine with the 2019 release.

**Comment by TheOneRing** [comment]
Closing for now as the error could be located in my script.

**Comment by heaths** [comment]
If you aren't installing the Release channel for VS2022, you need to pass `--prerelease`. Even now that VS2022 has GA'd, if you remain on the Preview channel you'll still need `--prerelease`.

**Comment by TheOneRing** [comment]
I am on the release channel I just looked up the wrong component id (I failed to read the script I last updated with the 2019 release).
For 2017 its `Microsoft.VisualStudio.Component.VC.v141.x86.x64` 
for 2019 its `Microsoft.VisualStudio.Component.VC.14.29.16.11.x86.x64` ( a less specific version number would be handy but I'd need to complain at a different team)
