### ISSUE TITLE
extra bit set in state

### ISSUE THREAD

**Issue by kdschlosser** [microsoft/vswhere#256]
In the InstanceState enumeration there are 5 values defined eNone, eLocal, eRegistered, eNoRebootRequired and eComplete. 

I have an installation of Visual Studio 2019 that I have made some changes to and it is pending a reboot. The state that is returned for the installation is 11 or `1011`. What does the  extra bit mean?

```
 1          0               1         1 
 ^   eNoRebootRequired eRegistered  eLocal
```

**Comment by heaths** [comment]
See https://docs.microsoft.com/dotnet/api/microsoft.visualstudio.setup.configuration.instancestate. It means "NoErrors". If you're checking for a reboot, though, just check bit 3. Bits can be added at any time.
