### ISSUE TITLE
-version does not allow for a single version value

### ISSUE THREAD

**Issue by tydunkel** [microsoft/vswhere#270]
Running `vswhere.exe -version 17` doesn't set the version range to be `[17,18)` but rather uses the max version for the upper bound. It may be less confusing to support a single version value for `-version` and set the maximum of the range to be the same as the minimum.

**Comment by heaths** [comment]
If anything, perhaps we can expand on the version syntax or at least link to https://github.com/microsoft/vswhere/wiki/Examples (maybe add a heading directly for version syntax, or add a new page and link to that from examples).
