### ISSUE TITLE
-utf8 option seems not work

### ISSUE THREAD

**Issue by huhuang03** [microsoft/vswhere#271]
vswhere version:
`Visual Studio Locator version 3.0.1+e2e4e03c65 [query version 3.2.2137.26324]`

`meson` use follow python code to find visual studio:
```python
    bat_json = subprocess.check_output(
        [
            str(bat_locator_bin),
            '-latest',
            '-prerelease',
            '-requiresAny',
            '-requires', 'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
            '-requires', 'Microsoft.VisualStudio.Workload.WDExpress',
            '-products', '*',
            '-utf8',
            '-format',
            'json'
        ]
    )
    bat_info = json.loads(bat_json)
```

And error throw:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 656: invalid start byte` at `json.loads(bat_json)`

I found the can't decode byte is `\xb9\xa6` which encode in gbk is `功`.

So I think it's still output as bgk encoding.

I tryied both in `powershell` and `cmd`. Same issue.

**Comment by heaths** [comment]
That was fixed in version 3.0.3. Please be sure to update to the latest.
