### ISSUE TITLE
How to find installations which support building SSDT projects?

### ISSUE THREAD

**Issue by chadbaldwin** [microsoft/vswhere#272]
Apologies in advance as this is not a bug with `vswhere`, but there is no discussions tab on this repo, and I'm not really sure where else to ask this question.

I'm trying to figure out the "correct" usage of `vswhere` to identify installations of MSBuild which support building SSDT projects.

The documentation for `vswhere` recommends using:

```powershell
vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
```

However, this does not guarantee that it will build an SSDT project. I looked around to see what package/component/workload I'd I need to include to also require building SSDT projects.

It seems there are some inconsistencies between Visual Studio Build Tools and Visual Studio.

After installing SSDT for Visual Studio, I see the following packages:

|id|type|
|-|-|
|Microsoft.VisualStudio.Component.SQL.SSDT|Component|
|Microsoft.VisualStudio.Workload.Data|Workload|
|SSDT|Vsix|

However, for Visual Studio Build Tools, I see these packages:
|id|type|
|-|-|
|Microsoft.VisualStudio.Component.SQL.SSDTBuildSku|Component|
|Microsoft.VisualStudio.Workload.DataBuildTools|Workload|
|SQLBuildSku|Vsix|

So because the names of the Component, Workload and Vsix packages do not line up between VS and VS Build Tools...it makes using `vswhere` difficult. Because I want to identify items that have:

```plaintext
(
  Microsoft.Component.MSBuild
  AND (
    Microsoft.VisualStudio.Component.SQL.SSDT
    OR
    Microsoft.VisualStudio.Component.SQL.SSDTBuildSku
  )
)
```

Maybe I'm being too strict and over thinking it...I can probably use this and be fine:

```powershell
vswhere `
  -latest `
  -requires `
    Microsoft.VisualStudio.Component.SQL.SSDT `
    Microsoft.VisualStudio.Component.SQL.SSDTBuildSku `
  -requiresany `
  -find 'MSBuild\**\Bin\MSBuild.exe'
```

Because if it finds `MSBuild.exe`, then that sort of implies that `Microsoft.Component.MSBuild` is installed.

**Comment by heaths** [comment]
You're suggestion of:

```
vswhere `
  -latest `
  -requires `
    Microsoft.VisualStudio.Component.SQL.SSDT `
    Microsoft.VisualStudio.Component.SQL.SSDTBuildSku `
  -requiresany `
  -find 'MSBuild\**\Bin\MSBuild.exe'
```

Is what I would do, yes. Let us know if that doesn't work for you.
