### ISSUE TITLE
Cannot locate msbuild on ARM64 installations

### ISSUE THREAD

**Issue by timheuer** [microsoft/vswhere#277]
When running on Windows ARM with VSARM64 installed, the find command for MSBuild returns nothing:

`vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1`

EXPECT:
A path

ACTUAL:
nothing.

Affects updating https://github.com/microsoft/setup-msbuild/issues/96

**Comment by heaths** [comment]
If you have a prerelease instance installed, you need to also pass `-prerelease`.

**Comment by timheuer** [comment]
ack, thanks @heaths
