### ISSUE TITLE
Wiki documentation does not detect VSTest fom Build Tools

### ISSUE THREAD

**Issue by davisnw** [microsoft/vswhere#285]
https://github.com/microsoft/vswhere/wiki/Find-VSTest gives the following snippet

```powershell
vswhere -latest -products * -requires Microsoft.VisualStudio.Workload.ManagedDesktop Microsoft.VisualStudio.Workload.Web -requiresAny -property installationPath
```

However, for e.g. build server where Visual Studio Build Tools is installed, you need to additionally check
- `Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools`
- `Microsoft.VisualStudio.Workload.Web Microsoft.VisualStudio.Workload.WebBuildTools`

e.g.
```powershell
vswhere -latest -products * -requires Microsoft.VisualStudio.Workload.ManagedDesktop Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools Microsoft.VisualStudio.Workload.Web Microsoft.VisualStudio.Workload.WebBuildTools -requiresAny -property installationPath
```

Consider adding docs with notes for build tools, or finding a more generic means of locating VSTest.

Note that https://github.com/microsoft/vswhere/wiki/Find-MSBuild works for both Visual Studio and Visual Studio Build Tools installations.

**Comment by heaths** [comment]
Thank you for letting us know. I'll make the changes to the wiki. Normally workload and component IDs don't change, but it happens occasionally
