### ISSUE TITLE
vswhere cannot find v17.5.0-pre.5.0 Build Tools on Arm64 device with -prerelease option

### ISSUE THREAD

**Issue by Blackhex** [microsoft/vswhere#286]
I have only Visual Studio Build Tools v17.5.0-pre.5.0 installed on my Arm64 device and 

```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease  -property installationPath -format json
```

just returns

```
[]
```

**Comment by heaths** [comment]
Build Tools is not included by default. Please see pinned issue #130.

**Comment by Blackhex** [comment]
Ah, OK, thank you and sorry for the hustle.
