### ISSUE TITLE
Can we get an example in the wiki of selecting a specific version of VS?

### ISSUE THREAD

**Issue by Ershany** [microsoft/vswhere#287]
I would like to prioritize VS 2019 over any other VS version when using CMake. Seems like a semi-common use-case and I didn't see a clear example on the wiki.

Maybe I am missing something?

**Comment by heaths** [comment]
Does https://github.com/microsoft/vswhere/wiki/Versions help?

**Comment by Ershany** [comment]
How did I miss that. Ugh sorry, I will close this out. I was just looking at the indented bullets on the wiki. Thank you!
