### ISSUE TITLE
VS Buildtools 2022 17.7 not detected

### ISSUE THREAD

**Issue by Arthapz** [microsoft/vswhere#296]
Hi,

i recently removed VS Buildtools Preview 17.8 and installed VS Buildtools 17.7 but now vswhere doesn't detect my installation anymore

![260631329-57ecb146-ad06-461c-94f1-7bf4f5b37058](https://github.com/microsoft/vswhere/assets/27437334/e7d15192-8ad7-4adf-82ec-f7e50c5ed3dd)

**Comment by heaths** [comment]
Please see https://github.com/microsoft/vswhere/wiki/FAQ#why-doesnt-vswhere-find-visual-studio-build-tools.
