### ISSUE TITLE
-path is only for selection, not specifying a copied Visual Studio

### ISSUE THREAD

**Issue by MarkSchofield** [microsoft/vswhere#297]
The Enterprised WDK (eWDK; [documentation](https://learn.microsoft.com/en-us/windows-hardware/drivers/develop/using-the-enterprise-wdk)) includes a build of Visual Studio. Launching an eWDK prompt sets the `VSINSTALLDIR` environment variable to the path of Visual Studio - for example `W:\eWDK\Program Files\Microsoft Visual Studio\2022\BuildTools\` - and specifying that as the path to `vswhere.exe -path <path>` gives no results. It _appears as though_ `-path` is only for filtering known instances, and not specifying a 'copied' instance. It would be great - if possible - if `-path` could specify a path to a copied instances, so that vswhere-like details of the installation could be retrieved.

**Comment by heaths** [comment]
Instances not installed by the Visual Studio Installer are not supported as they are not properly registered.
