### ISSUE TITLE
How do I find Visual Studio by year?

### ISSUE THREAD

**Issue by idbrii** [microsoft/vswhere#300]
I use premake which specifies Visual Studio toolchain like this: `vs2017`.

Is there some kind of query I can use, or do I need to list all versions and search for `2017` in the results?

[Versions on the wiki](https://github.com/microsoft/vswhere/wiki/Versions) only lists internal product versions (14) instead of name versions (2017).

**Comment by idbrii** [comment]
Using [pyvswhere](https://github.com/joelspadin/pyvswhere), I got to this:

```py
def match_year(t, year):
    return t['catalog']['productLineVersion'] == year

print(next(t['productPath'] for t in vswhere.find() if match_year(t, '2017')))
```

But it would be great if I could use something to easily find the latest for the user-facing name:

```python
print(t['productPath'] for t in vswhere.find_first(productyear=2017))
```
```batch
vswhere.exe -productyear 2017 -latest -property productPath
```

**Comment by heaths** [comment]
Marketing (year) versions are not supported, on. There's little value in them over the more descriptive major.minor.build versions encoded into the product information. I added a new section to that page that should help, however.
