### ISSUE TITLE
Add ability to locate Visual Studio Build Tools installations

### ISSUE THREAD

**Issue by lukaaash** [microsoft/vswhere#302]
We don't have Visual Studio installed on our build servers, because Visual Studio Build Tools are sufficient to build our projects and contain all the tools we need. Unfortunately, vswhere doesn't seem to be able to locate VS Build Tools installations, so we have to fall back to a different approach (pretty much equivalent to pre-vswhere days) when running the script on a build server. It would be great if vswhere could be used to locate supported VS Built Tools installation as well.

**Comment by heaths** [comment]
See pinned issue #130. You have to pass `-products *`.

**Comment by rsxdalv** [comment]
I think it's problematic that -all does not mean 'all'.

**Comment by heaths** [comment]
The usage text says "instances":

```text
  -all           Finds instances in complete, launchable, and incomplete states. By default, only instances
                 in a complete state - no errors or reboot required - are searched.
```
