### ISSUE TITLE
-version doesn't support pre-release suffixes

### ISSUE THREAD

**Issue by DamianEdwards** [microsoft/vswhere#304]
I'm trying to use vswhere to locate the latest release before a specific pre-release version, but it seems the `-version` option doesn't support pre-release syntax:

![image](https://github.com/microsoft/vswhere/assets/249088/6dfdbd50-09be-4864-977c-5c88b3693ba5)

**Comment by heaths** [comment]
Prerelease metadata is not part of the versions, nor are the versions actually semver anyway. If you want to work with prereleases, you need to also include `-prerelease` as well as `-version` where the `-version` parameter value deals only with the dotted-quad version numbers. Prereleases still have newer numbers, so it all works out.

**Comment by DamianEdwards** [comment]
Not sure what you mean by preview versions not being SemVer, as prefix suffixes are supported under SemVer 2.0, unless you meant VS versions specifically?

The example I pasted shows that I am using `-prerelease` as well as `-version`. What property should I be using to base the value I pass to `-version` on? I see `catalog_productSemanticVersion` which includes pre-release metadata, I see `catalog_buildVersion` which is a dotted-quad version number but a 17.9.0-pre.2.0 build is lower than the official 17.9.0-pre.1.0 build.
