### ISSUE TITLE
WARNING: Failed to activate VS environment: Could not parse vswhere.exe output

### ISSUE THREAD

**Issue by tarun253** [microsoft/vswhere#305]
Failed to activate VS environment: Could not parse vswhere.exe output
![Screenshot (71)](https://github.com/microsoft/vswhere/assets/84408817/8b73460c-d943-4d46-a54c-0efa6b7899cc)

**Comment by heaths** [comment]
You'll need to file a bug on the tool using vswhere, presumably `meson`. They may need to pass `-utf8` to force UTF8 output; otherwise, the console code page may mess up their parsing.
