### ISSUE TITLE
What does it check for?

### ISSUE THREAD

**Issue by mc0re** [microsoft/vswhere#314]
I have a situation where I need some custom tools installed for a build. I do it in a Docker container, which is then used from within Azure DevOps. The problem is, I cannot install Visual Studio on that container, as it exceeds 10 GB storage limitation for a build agent. But Visual Studio is already installed on the default agents, so I can just tap into it by mapping a number of directories inside the container.
Apparently, this is not enough to make `vswhere` happy. It probably needs some Registry entries. Therefore my question: what do I need to do to make `vswhere` see the Visual Studio installed on the host machine? The code merely uses `ISetupConfiguration2`, and I don't know where I can find the implementation of it.

**Comment by heaths** [comment]
The directories are not documented as they are an implementation detail. But if you already map in the directories where VS is installed, why do you need `vswhere`? You already know where VS is installed, and many - if not most - Azure DevOps tasks allow you to set a path to the tools you need. Using `vswhere` seems unnecessary.

**Comment by mc0re** [comment]
I am at home now, so I can't post the Azure log here. But I believe it is `VSBuild` task that calls `vswhere` internally.
Does `vswhere` check the file system or the registry?

**Comment by heaths** [comment]
The mode of function is undocumented because it's unsupported. You're welcome to use something like procmon but whatever you discover may not work in the future. FWIW, you could just run msbuild from within your mapped directories. You've already made the choice to use the VS version on the agent, so there's no reason to have the task find and choose a version just for it to find msbuild. Would be a little faster anyway.

**Comment by mc0re** [comment]
This is a normal build:
```
Starting: Build XXX.sln
==============================================================================
Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.231.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
==============================================================================
"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [17.0,18.0) -latest -format json
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" "C:\__w\1\s\Source\XXX.sln" /nologo /nr:false /dl:CentralLogger,"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=556e5e26-c7aa-4c6e-8725-3a42f7ab07d2|SolutionDir=C:\__w\1\s\Source|enableOrphanedProjectsLogs=true"*ForwardingLogger,"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll" -p:RunWixToolsOutOfProc=true -p:SkipInvalidConfigurations=true -p:OutDir=C:\__w\1\a\Binaries\ -p:OutputPath=C:\__w\1\a\Binaries\ -p:Version=1.1.1.1 /p:platform="Mixed Platforms" /p:configuration="Release" /p:VisualStudioVersion="17.0" /p:_MSDeployUserAgent="VSTS_da45d9d4-ec09-42a0-8d19-7e7512b7ee89_build_4_0"
Build started 8/2/2024 7:54:34 AM.
```

And this is a failed execution.
```
Starting: Build XXX.sln
==============================================================================
Task         : Visual Studio build
Description  : Build with MSBuild and set the Visual Studio version property
Version      : 1.231.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
==============================================================================
"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [17.0,18.0) -latest -format json
"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [17.0,18.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [16.0,17.0) -latest -format json
"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [16.0,17.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [15.0,16.0) -latest -format json
"C:\__w\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.231.0\node_modules\azure-pipelines-tasks-msbuildhelpers\tools\vswhere.exe" -version [15.0,16.0) -products Microsoft.VisualStudio.Product.BuildTools -latest -format json
##[warning]Visual Studio was not found. Try installing a supported version of Visual Studio. See the task definition for a list of supported versions.
##[warning]Unable to find MSBuild version '14.0' for architecture 'x86'. Falling back to version '4.0'.
```

The call to `vswhere` is generated by `VSBuild@1`, I don't think I have any control over this.

**Comment by heaths** [comment]
You can probably just use the `MSBuild` task pointing to the `msbuild.exe` path that VS installs as documented [here](https://github.com/microsoft/vswhere/wiki/Find-MSBuild) - the relative path. You know the root location since you mapped it. VSBuild doesn't really do much more than locating an appropriate version of MSBuild and execute it.
