### ISSUE TITLE
dll support

### ISSUE THREAD

**Issue by sapsari** [microsoft/vswhere#317]
Instead of an executable, I need an dll with the same functionalities. Because not every platform allows executables to be distributed.
Also a .Net Standard 2.0 dll wrapping the native dll would even be better.

**Comment by sapsari** [comment]
Or never mind, I did miss the part that it can be found at %ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe

**Comment by heaths** [comment]
See also https://www.nuget.org/packages/Microsoft.VisualStudio.Setup.Configuration.Interop, but it doesn't do all the queries for you like vswhere.exe.
