### ISSUE TITLE
Searching with `-find "**\bin\HostX64\x64\cl.exe"` takes 500s on Github Actions

### ISSUE THREAD

**Issue by touilleMan** [microsoft/vswhere#318]
Hi,

I have a script that [uses `vswhere` to find `cl.exe`](https://github.com/elijahr/python-autopxd2/blob/1e4ec707b1b040c7451d51f9af6bea852c09ed0f/autopxd/__init__.py#L39-L65)

On Github Action, [this takes 500s](https://github.com/elijahr/python-autopxd2/issues/48) to run `"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -prerelease latest -format json -utf8 -find "**\bin\HostX64\x64\cl.exe"` (then returns the correct result)

My guess is the -find with a `**` globing leads to quadratic complexity, however I don't know enough of `vswhere` to track the issue further...

PS: I there some documentation on `vswhere` ? Looking into the project, I've [only seen some examples](https://github.com/Microsoft/vswhere/wiki/Examples). Lack of documentation makes understanding `vswhere` pretty hard (for instance `-products *` is often used in the examples... but I could not find what is the list of products possible)

**Comment by heaths** [comment]
There is both usage via `-?` and this wiki. There's really not any more documentation to write about it. It has a simple interface.

If the agents are taking 500s to check the disk, I suggest you use the older instructions in the wiki for finding the installation root and, based on what version of VS you require, just hardcode the path. The `-find` was added for more general cases, like GitHub Action developers who may not know what versions of VS their users will require.

The searching algorithm tries to be as efficient as possible but with wildcards near the beginning, there's little more the algorithm can do. It's going to be a function of how slow disk IO is at that point.

**Comment by touilleMan** [comment]
> The -find was added for more general cases, like GitHub Action developers who may not know what versions of VS their users will require.

In my case, `vswhere` is used from within the application code (i.e. it's not part of the init script run in Github Actions).

This is because the project I'm working on (`autopxd2`) is a C to Cython transpiler, so it needs a C compiler at hand to handle the C preprocessing step.

Hence `autopxd2` is run on someone's computer and  it needs a way to find the C compiler which can be basically anywhere (and adding 10mn to the transpilation for this is a no go ^^).

> There is both usage via -? and this wiki. There's really not any more documentation to write about it. It has a simple interface.

To give you my (humble :smiley: ) user feedback:
- My usecase is fixing a build on Github Action and I don't have a Windows machine at hand. So interactive solution like `vswhere -?` is very cumbersome.
- The [wiki page about finding VC](https://github.com/microsoft/vswhere/wiki/Find-VC) mentions things such as `-products *`, `-requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64`, `-property installationPath`. None of those items are explained and there is no information on the accepted values either.
- I have absolutely no idea why `-find "**\bin\HostX64\x64\cl.exe"` takes so much time, and no idea how to improve this since there is no information on what this option does (for instance: does the `**` part means the match is done from the root of every drive on the computer ? or is it only on every found installation of VisualStudio ?).

On top of that I want to state that I am thankful for this tool and you quick answer on my issue :smiley: 

I believe providing user feedback has value, as complexity is not seen the same depending on one's experience in the field.

**Comment by touilleMan** [comment]
Ok so after spending my saturday morning playing hide and seek with Github Actions CI, I found a way to fix this (see https://github.com/elijahr/python-autopxd2/pull/55).

I'm putting the snippet here in case anyone stumble on this issue ;-)

```python
def _find_cl():
    """Use vswhere.exe to locate the Microsoft C compiler."""
    host_platform = {
        "X86": "X86",
        "AMD64": "X64",
        "ARM64": "ARM64",
    }.get(platform.machine(), "X86")
    build_platform = {
        "X86": "x86",
        "AMD64": "x64",
        "ARM64": "arm64",
    }.get(platform.machine(), "x86")
    program_files = os.getenv("ProgramFiles(x86)") or os.getenv("ProgramFiles")

    if build_platform in ("x86", "x64"):
        # Note the `x86.x64` here not related to cross compilation, but just
        # poor naming of something which should have been called `x86_or_x64`.
        require = "Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
    else:
        assert build_platform == "arm64"
        require = "Microsoft.VisualStudio.Component.VC.Tools.ARM64"

    cmd = [
        os.path.join(program_files, r"Microsoft Visual Studio\Installer\vswhere.exe"),
        "-prerelease",
        "-latest",
        "-products",
        "*",
        "-requires",
        require,
        "-property",
        "installationPath",
        "-utf8",
    ]
    try:
        install_dir = subprocess.check_output(cmd, encoding="utf-8").strip()
    except subprocess.CalledProcessError as ex:
        raise RuntimeError("No suitable compiler available") from ex

    with open(rf"{install_dir}\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt", encoding="ascii") as fd:
        default_version = fd.read().strip()

    return rf"{install_dir}\VC\Tools\MSVC\{default_version}\bin\Host{host_platform}\{build_platform}\cl.exe"
```
