### ISSUE TITLE
Locate MSBuild sample is not up-to-date

### ISSUE THREAD

**Issue by lextm** [Microsoft/vswhere#34]
I am using https://github.com/Microsoft/vswhere/wiki/Find-MSBuild to detect MSBuild 15 in batch file, but except the first snippet for batch file, the other two do not work, even if 1.0.47 version is used. Why?

**Comment by heaths** [comment]
I have updated the documentation.

**Comment by lextm** [comment]
Thanks. This time everything works like a charm.
