### ISSUE TITLE
Proposal: exit code != 0 when requested asset(s) aren't installed

### ISSUE THREAD

**Issue by per-samuelsson** [Microsoft/vswhere#35]
We're trying out `vswhere` as a means to get installation info of 2017 and also need a way to check if 2017 is at all installed. Based on the later, we know if we should continue or not (installing an extension).

Now, invoking `vswhere` on a machine where a requested product and/or prerequisite is not found, what about returning an exit code other than 0 for that? Preferable one even with some semantics (where that applies).

Hence, doing `vswhere -products *` on a machine where 2017 never was installed would give me 123 instead of 0.

**Comment by heaths** [comment]
This is by design. Returning an empty result set allows loops to just work. If you look at the various samples in the wiki here you'll see that variables set by output from vswhere would be empty / unset. The samples even deal with those results.

**Comment by per-samuelsson** [comment]
> This is by design.

I see. I just think it limits using this tool in two areas - scripting and where someone would use it from within a host, e.g

```csharp
void IsVS2017Installed() {
  return Process.Start("vswhere.exe").WaitForExit().ExitCode != 123;
}
```

By your design, you would force such a tool to redirect output streams and start parsing.

But thanks for the answer!
