### ISSUE TITLE
-legacy -latest returns wrong instance

### ISSUE THREAD

**Issue by vbtrek** [Microsoft/vswhere#40]
I've been testing out 1.0.50 and using the -legacy -latest, and not getting the results I expected. I have 2 instances found v10.0 and v14.0 however the -latest switch returns v10.0, it this expected?

C:\>VSWHERE.EXE -nologo -legacy -all
instanceId: VisualStudio.14.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 14.0\
installationVersion: 14.0

instanceId: VisualStudio.10.0
installationPath: c:\Program Files (x86)\Microsoft Visual Studio 10.0\
installationVersion: 10.0

C:\>VSWHERE.EXE -nologo -legacy -latest
instanceId: VisualStudio.10.0
installationPath: c:\Program Files (x86)\Microsoft Visual Studio 10.0\
installationVersion: 10.0

C:\>VSWHERE.EXE
Visual Studio Locator, version 1.0.50
Copyright (C) Microsoft Corporation. All rights reserved.

**Comment by heaths** [comment]
Can you run `get-itemproperty HKLM:\Software\WOW6432Node\Microsoft\VisualStudio\SxS\VS7` and paste the output? If you're running in a 32-bit powershell console, drop the "WOW6432Node".

**Comment by vbtrek** [comment]
Sure, he you go:
PS C:\Users> get-itemproperty HKLM:\Software\WOW6432Node\Microsoft\VisualStudio\SxS\VS7


14.0         : C:\Program Files (x86)\Microsoft Visual Studio 14.0\
10.0         : c:\Program Files (x86)\Microsoft Visual Studio 10.0\
PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\VisualStudio\SxS\V
               S7
PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\VisualStudio\SxS
PSChildName  : VS7
PSDrive      : HKLM
PSProvider   : Microsoft.PowerShell.Core\Registry

**Comment by heaths** [comment]
Could you also paste the output from:

```powershell
get-item $env:ProgramData\Microsoft\VisualStudio\Setup\x86\Microsoft.VisualStudio.Setup.Configuration.Nati
ve.dll | select -expand VersionInfo | select *
```

**Comment by vbtrek** [comment]
Yep, got an error on that one:
```
PS C:\Users> get-item $env:ProgramData\Microsoft\VisualStudio\Setup\x86\Microsoft.VisualStudio.Setup.Configuration.Native.dll | select -expand VersionInfo | select *
get-item : Cannot find path
'C:\ProgramData\Microsoft\VisualStudio\Setup\x86\Microsoft.VisualStudio.Setup.Configuration.Native.dll' because it does not exist.
At line:1 char:1
+ get-item $env:ProgramData\Microsoft\VisualStudio\Setup\x86\Microsoft. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...tion.Native.dll:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

```

**Comment by heaths** [comment]
I understand the problem now. Thank you.

**Comment by heaths** [comment]
Will be fixed in next release.

**Comment by vbtrek** [comment]
Great stuff, thanks.
