### ISSUE TITLE
XP Build?

### ISSUE THREAD

**Issue by vbtrek** [Microsoft/vswhere#44]
Any chance this could be built to run on Windows XP? We're stuck in legacy land with XP build machines at present which have Visual Studio 2010 installed on them, however running vswhere.exe gives the following error:
![15-03-2017 4-09-59 pm](https://cloud.githubusercontent.com/assets/26403480/23958477/2aa3e8da-099a-11e7-8ad7-fdbffaf5c053.png)

**Comment by heaths** [comment]
I would have to build an XP machine (given it's out of support, I don't have an image handy) so please download the artifact from the PR build from https://ci.appveyor.com/project/heaths/vswhere/build/1.0.57%2Bgc757b8a2cf/job/b3l2uccqouj1tk6a/artifacts and see if _vswhere.exe_ works for you on XP before I can merge the PR.

**Comment by vbtrek** [comment]
That did the trick. I’ve tested it on Windows XP 32bit, Windows 7 32bit, and Windows 10 64bit and it worked fine on all.

 

Thanks

Derek

**Comment by heaths** [comment]
Thank you for your help!
