### ISSUE TITLE
Doesn't locate Visual Studio 2015 installation

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vswhere#49]
Hi,

I have side by side VS 2017 and VS 2015.
When I execute the tool, it prints only `VS 2017` location.

Wouldn't be great idea that this should spit out all VS installations as it sounds?

**Comment by KindDragon** [comment]
You can use `-legacy` parameter for that

**Comment by heaths** [comment]
Correct. `-legacy` was added to get the installation path for VS2010 through VS2015. This is documented in the usage content for newer versions as well.
