### ISSUE TITLE
Version range filter includes wrong instance (-version [12.0,14.0] returns 10.0)

### ISSUE THREAD

**Issue by gcollector13** [Microsoft/vswhere#51]
I want to identify a supported legacy VS instance, however by running:

vswhere -legacy -version [12.0,14.0]

it returns:
Visual Studio Locator, version 1.0.58
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: VisualStudio.12.0
installationPath: D:\Program Files (x86)\Microsoft Visual Studio 12.0\
installationVersion: 12.0

instanceId: VisualStudio.10.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 10.0\
installationVersion: 10.0

Being outside the version range filter, the 10.0 is part of the output.

**Comment by heaths** [comment]
I'm not able to repro this in either PowerShell (with quotes) or cmd.exe (with or without quotes) using 1.0.58. What shell are you using?

**Comment by heaths** [comment]
What is the file version of %ProgramData%\Microsoft\VisualStudio\Setup\x86\Microsoft.VisualStudio.Setup.Configuration.Native.dll?

**Comment by gcollector13** [comment]
well... currently it returns only 12.0 instance from both powershell and cmd, which is great
I did some changes in the mean time, it's one of our test agents, replaced Test Agent 2013 with 2017
(we are switching slowly to 2017)
The Microsoft.VisualStudio.Setup.Configuration.Native version is 1.8.8.44148

but, on another machine (build agent) I have a similar issue
running from cmd without quotes of from powershell 3.0 with quotes:
PS D:\> .\vswhere.exe -legacy -version '[12.0,14.0]'
Visual Studio Locator, version 1.0.58
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: VisualStudio.14.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 14.0\
installationVersion: 14.0

instanceId: VisualStudio.12.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 12.0\
installationVersion: 12.0

instanceId: VisualStudio.11.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 11.0\
installationVersion: 11.0

in this case it shows 11.0 in the output
on this machine there is no Setup folder under %ProgramData%\Microsoft\VisualStudio
it contains only these folders 11.0, 12.0, 14.0 and Packages

**Comment by heaths** [comment]
If you have no _%ProgramData%\Microsoft\VisualStudio_ folder, then where did you find _Microsoft.VisualStudio.Setup.Configuration.Native.dll_ at version 1.8.8?

**Comment by heaths** [comment]
I cannot reproduce this. Please reopen the issue with the requested information and we can continue to investigate.
