### ISSUE TITLE
vswhere 1.0.60 crashes on Windows 7

### ISSUE THREAD

**Issue by yuichi-github** [Microsoft/vswhere#55]
v1.0.60 crashes on my Windows 7(x64, SP1, Japanese, VS2010, VS2015 are installed.).
It's OK with my Windows 10.

The error information of the event log is below.

    Faulting application name: vswhere.exe, Version: 1.0.60.6534, Timestamp: 0x58ec036f
    Faulting module name: vswhere.exe, Version: 1.0.60.6534, Timestamp: 0x58ec036f
    Exception code: 0xc0000005
    Fault offset: 0x00001cfe
    Faulting process id: 0x1ac8
    Faulting application start time: 0x01d2b28045bd8f81
    Faulting application path: C:\Users\userid\iq\nuget\packages\vswhere.1.0.60\tools\vswhere.exe
    Faulting module path: C:\Users\userid\iq\nuget\packages\vswhere.1.0.60\tools\vswhere.exe
    Report  ID: 83713e5d-1e73-11e7-8c5e-f8b156a57939

Note: The user belongs to the Administrators Group.

**Comment by heaths** [comment]
I noticed this as well. It should be fixed in pull request #56 which I'm releasing now.

**Comment by yuichi-github** [comment]
I've already confirmed that the problem is fixed with 1.0.62.
Thank you very much!

**Comment by heaths** [comment]
To those who discover this work item if you have the same issue, please use release 1.0.62 or newer. I have removed/unlisted 1.0.60 from existing download sources.
