### ISSUE TITLE
Update wiki/install

### ISSUE THREAD

**Issue by refack** [Microsoft/vswhere#58]
https://github.com/Microsoft/vswhere/wiki/Find-MSBuild
I've sketched a paragraph here as diif, [inst.upd.txt](https://github.com/Microsoft/vswhere/files/946872/inst.upd.txt)
and here as is:

&nbsp;

[update April 20, 2017 - [vswhere is now installed with visual studio 2017](https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017)]
As of release 15.2 (26418.1-Preview - Installer version 15.0.26418.1) the VS installer will include `vswhere.exe` and place it in `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer` (on 32-bit operating systems before Windows 10, it will be `%ProgramFiles%\Microsoft Visual Studio\Installer`).
<sub>On exsisting installation you can run the installer with `--update --quiet` to quitly get in to upgrade</sub>
[/end update]

---

**Comment by heaths** [comment]
Wiki has been updated.
