### ISSUE TITLE
vshwere hangs

### ISSUE THREAD

**Issue by sebastienros** [Microsoft/vswhere#59]
Running with any parameters but `/?` results in a failure:

![image](https://cloud.githubusercontent.com/assets/1165805/25442327/98dcb87e-2a59-11e7-9bda-1a93211313d8.png)

Windows 10 (not creator update)
Visual Studio 2015 only

**Comment by KindDragon** [comment]
What version are you using?

**Comment by heaths** [comment]
I'm working with him internally. I have a dump I'm looking at now. It crashed (not hung) with an access violation.

**Comment by heaths** [comment]
From the dump, the query API server is version 1.1.89 which is incredibly old (VS2017 RTM shipped version 1.8.8). Please update to VS2017 RTM. If this issue is reproduced after that, please reopen the bug with a separate dump.

**Comment by sebastienros** [comment]
I don't have VS 2017, I need to run the tool even if VS 2017 is not installed.

**Comment by heaths** [comment]
You must have remnants of a very old copy then. vswhere is loading Microsoft.VisualStudio.Setup.Configuration.Native.dll – a pre-release version no longer supports – which appears to be causing this issue. vswhere requires no VS2017, or VS2017 RTW (seems to work also on newer RCs, but those have limited to no support). The COM server you have installed does not appear to be aligned. Given the relative small developer audience and little known use, I made some COM-unfriendly changes very early in the pre-releases that may be causing issues.

I suggest you unregister and remove the files. From a 64-bit command prompt:
```batch
%windir%\System32\regsvr32.exe /s /u "%ProgramData%\Microsoft\VisualStudio\Setup\x64\Microsoft.VisualStudio.Setup.Configuration.Native.dll"
del /q /s "%ProgramData%\Microsoft\VisualStudio\Setup\x64"
%windir%\SysNative\regsvr32.exe /s /u "%ProgramData%\Microsoft\VisualStudio\Setup\x86\Microsoft.VisualStudio.Setup.Configuration.Native.dll"
del /q /s "%ProgramData%\Microsoft\VisualStudio\Setup\x86"
```

**Comment by sebastienros** [comment]
Thanks a lot, that worked.
