### ISSUE TITLE
vswhere -version '[15.1,16.0)' doesn't find 15.1.0 (26403.7)

### ISSUE THREAD

**Issue by flcdrg** [Microsoft/vswhere#60]
I have the latest VS 2017 installed:
![image](https://cloud.githubusercontent.com/assets/384747/25553589/817d8c9a-2cf6-11e7-9848-08d6c3540432.png)

If I run `vswhere -version '[15.1,16.0)'` all I get is:

> Visual Studio Locator version 1.0.62 [query version 1.9.77.53636]
> Copyright (C) Microsoft Corporation. All rights reserved.

But if I run ` vswhere -version '[15.0,16.0)'` I get:

> Visual Studio Locator version 1.0.62 [query version 1.9.77.53636]
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> instanceId: 9df01e36
> installDate: 12/04/2017
> installationName: VisualStudio/15.1.0+26403.7
> installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
> installationVersion: 15.0.26403.7
> displayName: Visual Studio Enterprise 2017
> description: Microsoft DevOps solution for productivity and coordination across teams of any size
> enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
> channelId: VisualStudio.15.Release
> channelPath: C:\Users\david\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\4CB340F5\catalog.json
> channelUri: https://aka.ms/vs/15/release/channel
> releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660090#15.1.26403.07
> thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660105

Shouldn't I get a match for the first range?

**Comment by KindDragon** [comment]
But, installationVersion: **15.0**.26403.7

**Comment by refack** [comment]
There is an inconsistency, maybe it's not `vswhere`'s fault:
1. `installationName: VisualStudio/15.1.0+26403.7`
2. `installationVersion: 15.0.26403.7`
3. the GUI

**Comment by flcdrg** [comment]
This is still a problem even for the 15.2 preview, which you might have thought would have an updated installationVersion

> instanceId: 9df01e36
> installDate: 12/04/2017
> installationName: VisualStudio/15.1.0+26403.7
> installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
> installationVersion: 15.0.26403.7
> displayName: Visual Studio Enterprise 2017
> description: Microsoft DevOps solution for productivity and coordination across teams of any size
> enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
> channelId: VisualStudio.15.Release
> channelPath: C:\Users\david\AppData\Local\Microsoft\VisualStudio\Packages\_Channels\4CB340F5\catalog.json
> channelUri: https://aka.ms/vs/15/release/channel
> releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660090#15.1.26403.07
> thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660105

**Comment by heaths** [comment]
We are considering fixes to the versioning to address this going forward, but is a problem with how we build and publish VS and not _vswhere_.
