### ISSUE TITLE
Was vswhere.exe supposed to find a "Build tools" install?

### ISSUE THREAD

**Issue by brunomlopes** [Microsoft/vswhere#61]
On a build agent I installed the "Build tools for Visual Studio 2017" ( taken from https://www.visualstudio.com/downloads/ , under "Other Tools and Frameworks", "Build Tools for Visual Studio 2017" ).

Running vswhere doesn't find that install. Shouldn't it?

```
PS S:\temp> .\vswhere -latest -requires Microsoft.Component.MSBuild
Visual Studio Locator version 1.0.62 [query version 1.9.77.53636]
Copyright (C) Microsoft Corporation. All rights reserved.

PS S:\temp>
```
It does find the install for a "legacy" version, if that's relevant:
```
PS S:\temp> .\vswhere -legacy
Visual Studio Locator version 1.0.62 [query version 1.9.77.53636]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: VisualStudio.10.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 10.0\
installationVersion: 10.0
PS S:\temp>
```

**Comment by refack** [comment]
As of version `1.0.40` you can add `-products *` to include Buildtools is the search
See last paragraph of https://github.com/Microsoft/vswhere/wiki/Find-MSBuild

**Comment by heaths** [comment]
As stated in the usage output and documentation herein, *vs*where searches, by default, for Community, Professional, and Enterprise products. Build Tools and other products installed by the new Installer can by found either by passing in a comma-separated list of product IDs to `-products` or just specifying `-products *` as @refack mentioned.

**Comment by brunomlopes** [comment]
So sorry, I must have missed that. I wasn't considering BuildTools to be a
product, but makes sense.

Thanks for the responses.

**Comment by uli-weltersbach** [comment]
Just to be clear, the reason why I'm not seeing any output on our build server is because the build tools were not installed with "the new installer"?
If so, what is "the new installer"?
![vswhere exe and msbuild tools](https://cloud.githubusercontent.com/assets/1416006/26620711/2f3a20cc-45e4-11e7-957a-70bd4921d8e8.png)

**Comment by brunomlopes** [comment]
I think for 2015 and earlier you need to use "-legacy"

**Comment by uli-weltersbach** [comment]
Thanks a lot, that did the trick :)

**Comment by heaths** [comment]
Because that is not a VS path. MSBuild was located under Visual Studio starting with 2017. It was in the same place under _%ProgramFiles(x86)%\MSBuild_ before that. There are other ways to find MSBuild prior to 2017 that are outside the scope and purpose of _vswhere_.
