### ISSUE TITLE
RFE: Improved semantics when multiple products are installed

### ISSUE THREAD

**Issue by mistachkin** [Microsoft/vswhere#63]
If there are multiple products installed, it would be nice to have one or both of the following features:

1.  An option to output the products in order from the "best" one down, e.g. Enterprise first, etc.

2.  Alternatively, there could be an option, perhaps called "-best", that returns only the best installed product for a particular version.  It should, of course, work with the "-version" option.

**Comment by heaths** [comment]
There is already `-latest`. Which is best for your needs is subjective.

**Comment by mistachkin** [comment]
Ok, I was mistaken.  I thought that the "-latest" option was only used to select the latest *version*.  I should have read the help text more closely.

**Comment by mistachkin** [comment]
Related question: Does the -latest option work with -version?  e.g. If I want to find the "last installed" SKU for Visual Studio 2017 only via "-latest -version 15.0" ?

**Comment by heaths** [comment]
It does, yes. It is a supported scenario. All instances are enumerated based on criteria and `-latest` is processed last.
