### ISSUE TITLE
Add -listproducts option

### ISSUE THREAD

**Issue by sldr** [Microsoft/vswhere#66]
This option would list all the available product name options that could be used with the -products arg option. This could also be hardcoded in the help if it isn't dynamic.

Thanks,
SLDR
(Stephen L. De Rudder)

**Comment by heaths** [comment]
This information is not exposed from the query APIs by design (requires deserializing and handling something very different and not intended for general consumption). The supported and documented values can be found at https://docs.microsoft.com/visualstudio/install/workload-and-component-ids.

**Comment by sldr** [comment]
Please consider adding the above link to the help or a maybe a search string to "bing" to try to find the link above.

Thanks,
SLDR
(Stephen L. De Rudder)

**Comment by heaths** [comment]
Thanks for the suggestion. We will take that under advisement.

**Comment by sldr** [comment]
Thanks!!!
