### ISSUE TITLE
Using vswhere to find BuildTools

### ISSUE THREAD

**Issue by n9** [Microsoft/vswhere#67]
[Someone suggests](https://gist.github.com/jpluimers/9b9953050aab8e3e511f#gistcomment-2021989) to use vswhere to locate msbuild. However, it seems that current release of vswhere does not list "BuildTools edition of VS". I understand that BuildTools is not a real edition of VS, but rather an extracted component from VS. (It is located inside VS install directory.) 

Could vswhere also list plain BuildTools installation? Or could anyone suggest a proper way to locate msbuild? Or, is checking the directories the only proper way to locate msbuild as, for instance, [gulp-msbuild does](https://github.com/hoffi/gulp-msbuild/blob/9aece0cc4dc28776071cb69bf0e086adb7d108ba/lib/msbuild-finder.js#L9).)

**Comment by refack** [comment]
@n9 see #61

**Comment by n9** [comment]
Thanks.
