### ISSUE TITLE
Is `VC\Tools\MSVC\14.10.25017\bin\HostX64\x64` for MSVC tool consistent?

### ISSUE THREAD

**Issue by SaschaNaz** [Microsoft/vswhere#73]
If I do `where cl` on VS2017 Command Prompt then I see `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\cl.exe`. I don't think this is a consistent path for future VS2017.x or VS201x, is there a way to get a path that can work for future versions of Visual Studio?

The current sample on the main page uses MSBuild which has simpler path, but still it uses version number `15.0` which makes it incompatible with future VS versions.

**Comment by SaschaNaz** [comment]
Specifically I want to add VS2017+ support on emscirpten, but I'm not sure hard-coding the path with version number `14.10.25017` is any good.

https://github.com/kripken/emscripten/blob/6dc4ac5f9e4d8484e273e4dcc554f809738cedd6/tools/shared.py#L656

**Comment by refack** [comment]
I'll give my 2<sub>¢</sub> before @heaths gives an official answer:
The version part of the `cl.exe` path changes with interversion updates, and is host and target dependent (x86 / x64). Also by calling it directly you'll need to explicitly setup `INCLUDE` and `LIBPATH` equivalent args.
What we started doing in `node` is calling this script [`vswhere_usability_wrapper.cmd`](https://github.com/node4good/msvs-com-helper/blob/master/vswhere_usability_wrapper.cmd) then calling `vcvarsall.bat` to setup the env - https://github.com/nodejs/node/pull/11852/files

**Comment by SaschaNaz** [comment]
I've written similar code on [FLIF repo](https://github.com/FLIF-hub/FLIF/blob/504b2a1c8b206e63d49e9c366e03c57418eff401/build/MSVC/dl_make_vs.ps1), it seems wrappers are common for vswhere. I hope vswhere automatically provide the environment variables rather than forcing users write their own wrappers to get them.

**Comment by refack** [comment]
It might be interesting to have `vswhere` perform `vcvarsall`'s functionality.

**Comment by heaths** [comment]
You can use _vswhere_ to find _vcvarsall_. _vswhere_ is general purpose and you can use it to set environment variables in your own scripts. As has been stated, environment variables do not make sense when multiple instances of VS can be installed simultaneously. To which would they point?

As to how to handle the situation where the path to VC tools may change with each version, @dangrif can offer some insight.

**Comment by dangrif** [comment]
@SaschaNaz Please see the "[Finding installed Visual C++ tools for Visual Studio 2017](https://blogs.msdn.microsoft.com/vcblog/2017/03/06/finding-the-visual-c-compiler-tools-in-visual-studio-2017/)" article on the Visual C++ team blog.  

The information you're looking for is towards the bottom of the blog article in the section with the heading "Identifying the VC++ compiler tools version".  To be specific, installation of VC++ tools places a file with a "default" toolset version number in the following location (there's also a .props version of the file for MSBuild-based build systems):

VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt

You can use Common7\Tools\vsdevcmd\ext\vcvars.bat as an example of how this can be used to assemble a full path from the version included in the file.

Regards,
--Daniel Griffing, Visual C++ Libraries

**Comment by SaschaNaz** [comment]
>To which would they point?

The one of the matching instance. That's how vswhere works.

**Comment by heaths** [comment]
Environment variables are global the machine or process (depending on which you set). And if another task or developer needs different features from another instance, what then?

You are free to use _vswhere_ to set environment variables or use full paths or whatever your scenarios require. That's why we created this general purpose tool. But because we enable multi-instancing for VS and related products, it will not set global state because different instances can fulfill different requirements.

**Comment by SaschaNaz** [comment]
@heaths Hmm, it seems I shouldn't have used the word "environment variables"...

My code (and the Node script mentioned above) currently 1) finds vsvarsall.bat for each instance (by `-requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64` in my case), 2) gets the variables by `cmd -c` and 3) parses the output from cmd, so that I can use them as environment variables inside of my process, not global.

**Comment by SaschaNaz** [comment]
`vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -vcvarsall`

This will work for me.

**Comment by heaths** [comment]
Visual Studio has many features to support developers of many languages and toolkits. _vswhere_ provides access to the install root with which you can tailor to your scenarios. It also supports non-VS products like Build Tools and Remote Tools. You are free to write scripts using _vswhere_ (I've made it available to acquire through different mechanisms) or even fork and add whatever feature you want to fit your specific scenario's needs.

**Comment by refack** [comment]
@heaths you can consider this a feature request. A flag that either runs `vcvarsall` and outputs the env vars, or actually sets them for the invoking process.

**Comment by SaschaNaz** [comment]
>Visual Studio has many features to support developers of many languages and toolkits

Using [vsdevcmd](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/how-to-set-environment-variables-for-the-visual-studio-command-line) instead of vcvarsall will allow more general use for other "many features". (The vsvars32.bat is replaced by vsdevcmd.bat in VS2017, not sure why the document is not updated yet)
