### ISSUE TITLE
Getting the full path to MSBuild.exe

### ISSUE THREAD

**Issue by uli-weltersbach** [Microsoft/vswhere#74]
Hi

I feel like I'm missing some obvious way to determine the full path to `MSBuild.exe`.
To illustrate, here's where we're at currently:

1. Run `vswhere.exe -latest -requires Microsoft.Component.MSBuild -property installationFolder`.

2. The return value "C:\Path\To\VisualStudio\Root\" seems useless, because we have to make an additional assumption reg. the location of `MSBuild.exe` inside that folder. 
We could append "\MSBuild\15.0\MSBuild\bin\MSBuild.exe", but that seems to defeat the purpose of not making assumptions/including hard coded paths in our build scripts.

3. Run `vswhere.exe -latest -requires Microsoft.Component.MSBuild -property installationVersion`.

4. The return value "15.0.26430.6" seems useless, because the actual path is "C:\Path\To\My\VisualStudio\Root\\__15.0__\\" which means we'd again need to do additional handling, e.g. using either a 2 or 3 digit substring based on whether the major revision is less than/greater than 10.

**Comment by uli-weltersbach** [comment]
On a more general note: Is this tool in any way intended to be runnable on a build server which ONLY has MS Build Tools installed, i.e. no version of Visual Studio?

**Comment by 3F** [comment]
you can simply try something like this if you need only full path to msbuild:

```bat
...
for /f "usebackq tokens=1* delims=: " %%a in (`!vswbin! -latest -requires Microsoft.Component.MSBuild`) do (
    if /i "%%a"=="installationPath" set vspath=%%b
    if /i "%%a"=="installationVersion" set vsver=%%b
)
...
for /f "tokens=1,2 delims=." %%a in ("!vsver!") do (
    set vsver=%%a.%%b
)
set msbuildPath=!vspath!\MSBuild\!vsver!\Bin
```

this part from [hMSBuild helper](https://github.com/3F/hMSBuild), and as you can already noticed we specially use this for simple access to msbuild tools -_-

just to be clear, the latest version already supports also a local vswhere tool (#41) and via key `-vswhere-version` can control this behaviour.

```bat
 -vswhere-version {num} - Specific version of vswhere. Where {num}:
                          * Versions: 1.0.50 ...
                          * Keywords:
                            `latest` to get latest available version;
                            `local`  to use only local versions:
                                     (.bat;.exe /or from +15.2.26418.1 VS-build);

```

**Comment by uli-weltersbach** [comment]
Thanks for the reply, I've already downloaded hMSBuild.bat and am working on getting it into our build system :)

**Comment by heaths** [comment]
If you look at the [wiki](https://github.com/Microsoft/vswhere/wiki) there are plenty of examples, and issue #61 describes - as do the docs and command line usage text - that _**vs**where_ searches for VS by default but can easily support Build Tools as well.

**Comment by heaths** [comment]
Also, as of Visual Studio 2017 version 15.2 _vswhere_ will always be available in _%ProgramFiles(x86)%\Microsoft Visual Studio\Installer_ if VS, Build Tools, Remote Tools, or other 2017 family of products or newer is installed.

But that still doesn't change the fact that support for `-legacy` is, as documented, limited. That was a feature I added solely to find the roots of then-supported Visual Studio installations that did not use the query API. Older versions of MSBuild were not limited to being installed by VS and are locatable by other means. You will need to script your environment appropriately to handle legacy MSBuild.
