### ISSUE TITLE
[Feature request] An option for -requires to detect 15063/1703 Windows SDK

### ISSUE THREAD

**Issue by ifarbod** [Microsoft/vswhere#75]
Just as the title says, I'm not sure if this is the right place to ask this (since `-requires` options may be defined by Visual Studio's SxS installer. But I'll give it a try (since Windows SDK can be installed with its standalone installer, too).

**Comment by heaths** [comment]
_vswhere_ and the query API which it uses is only for products - not components - installed by the Visual Studio installer. Windows SDK is only an optional component, which you can detect using `-requires` already but only if installed with Visual Studio. I recommend you look at the registry detection supported by the Windows SDK already.
