### ISSUE TITLE
Cannot distinguish releases from prereleases

### ISSUE THREAD

**Issue by heaths** [Microsoft/vswhere#79]
Some internal and external users have asked for a way to filter out prereleases. Visual Studio ships a number of prereleases to our preview channel before releasing the final updated versions. Currently, this information is not exposed through the query API but we are working to make it so.

This is a tracking item and a request for comments on how to expose this ability.

Currently, I have a prototype which,

1. Filters out prereleases by default.
2. Adds a `IsPrerelease : boolean` property.
3. Adds a `-prerelease` switch parameter to _vswhere.exe_ to allow prereleases in results.

This means prereleases will no longer show up in results by default, but you can opt into considering prereleases with the `-prerelease` switch.

**Comment by heaths** [comment]
@refack, @KindDragon, @grafikrobot, @dangrif what do you think about this proposal? Preview releases haven't been out very long and telemetry shows good but relatively low distribution (compared to all Visual Studio users/downloads), so I don't think this would be a significant breaking change and at least two people have asked for this default behavior anyway.

**Comment by ben-may** [comment]
This sounds like a great solution :) and is likely what I'm looking for!

**Comment by KindDragon** [comment]
> Filters our prereleases by default.

👍

**Comment by refack** [comment]
This is going to hurt a little bit (a.k.a. `semver-major`). So if you are planning this for VS16 that's Ok. Removing (1) and negating (3) would turn this into opt-in, a.k.a `semver-minor` which will go smoother. But my guess is as good as yours.

As for telemetry, intuitively I'd say it's anti-correlated with the users of my wrappers (`node` and `chrome` devs), but these people know what they are getting into. My main concern would have been `node-gyp` but there we query the COM server directly...

**Comment by heaths** [comment]
@refak, this would be for Visual Studio 2017 but I don't understand your comment about `semver-major` or `semver-minor`. Could you clarify with examples of what you mean, and how you think it might solve the problem better?

**Comment by refack** [comment]
Assuming you (or any other future reader) are not acquainted with [Semantic Versioning](http://semver.org/), it's a concept of "ranking" changes to software:
1. Major - some code will break
2. Minor - only new features
3. Patch - only bug fixes.

In this case for a dev with only a prerelase installed, `vswhere` will stop detecting that prerelase -> something that worked will stop working -> `semver-major`
If you don't change the default behavior and add a `--noprerelease` switch (and/or `IsPrerelease`). Everything works as before, and whomever wants to opt-in to the new behaviour has a way to do it ->`semver-minor`

**Comment by heaths** [comment]
@refack, I understand semver (and the differences between 1.0 and 2.0), but not what you're asking. Are you asking that Visual Studio use semver? Parts of it do, actually. Catalog information that will be made available through a new interface do just that, but for legacy reasons we are bound to dotted quads for many things including the `InstallationVersion`. Besides, then you're asking every caller to understand and parse semver. What I'm proposing here is lifting that burden to _vswhere_. In fact, internally in my prototype I am (basically) parsing the semver available in the catalog information to determine if the instance is for a release or prerelease. But why make every caller have to do that?

**Comment by heaths** [comment]
...or are you asking that I use semver for _vswhere_ itself? I had considered it, but 1) doubt developers actually check, since NuGet itself (unlikely NPM) doesn't fully utilize it, and 2) figured very few people are using the Preview channel right now. I could bump the major version of _vswhere_ since this would be a behavioral, breaking change. I just don't see why it would help in this case.

For example, if NuGet supported matches like "1.*" in _packages.config_ I would totally agree. It seems like floating versions are only [supported in project files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files).

**Comment by refack** [comment]
I'm using `semver` only as metaphor to the severity of your proposed change.
Your (1) will break people's setup, since it's by definition "a change to defaults". Will they handle it with patience? I don't know. I'm just bringing my POV. In that making this feature opt-in will go down smoother (since it was not easy to filter for prereleases before I assume those who asked for it will be satisfied with the ability to opt-in)

**Comment by refack** [comment]
Simple scenario that is happening right now on my computer:
1. I have ` 15.0.26430.12` comunity edition
2. I use it to build `node` with `vcbuild.bat` a build script that does detection via `vswhere`
3. I'm updating to `15.3.26608.05`
4. If `vcbuild.bat` stops working I'll be surprised

**Comment by refack** [comment]
> 3. I'm updating to 15.3.26608.05

Now I see the installer will not let me "update" but rather add new install, so if I have to uninstall the previous version I'll be less surprised if things stop working but still.
(Also if I was on the prerelease channel, a breaking "update" could happen)

**Comment by heaths** [comment]
You can upgrade from 15.0, 15.2, and 15.2 to 15.3. If that's not what you see, please gather logs via http://aka.ms/vscollect.exe and attach to a new bug on http://developercommunity.visualstudio.com.

That said, Visual Studio does not exhibit semver that way currently. Any breaking change within a major version is almost certainly a bug.

This seems orthogonal to the discussion, however. This is about whether _vswhere_ shows prereleases - regardless of their advertised version - from the Preview channel. What I've proposed appears to work for others and doesn't seem blocking to you since you use the query API in scripts you've written and shared.

**Comment by refack** [comment]
`vswhere` was a big success so [`nodejs/node`](https://github.com/nodejs/node/blob/master/tools/msvs/vswhere_usability_wrapper.cmd) is using it.

**Comment by heaths** [comment]
Do you or @gibfahn think this change in behavior would be bad for node? If anything, this would more likely eliminate potentially buggy (though our Previews are well-tested) releases being selected by _vswhere_.

**Comment by refack** [comment]
> Do you or @gibfahn think this change in behavior would be bad for node? If anything, this would more likely eliminate potentially buggy (though our Previews are well-tested) releases being selected by vswhere.

1. node releases are still made with VS2015
2. I can respond quickly if anyone complains, or add `-prerelease` preemptively

Bottom line I'm not against this change, but would like `-noprerelease` better.

**Comment by heaths** [comment]
I considered `-noprerelease` but others expressed interested in this behavior by default. If preview deployments were more prevalent, I would be inclined to agree to opt out of seeing them. In most implementations such as NuGet and NPM, you opt into seeing prereleases so figured normalcy over _vswhere_ back-compat for a relatively young project (i.e. break behavior now while it's young).

Thanks for all your comments.

**Comment by gibfahn** [comment]
I think this makes sense as proposed. Not installing betas unless you actively ask for them (i.e. betas being opt-in) seems like the least surprising behaviour to me.

**Comment by gibfahn** [comment]
However it does seem like a breaking change (CI setups that rely on a prerelease Visual Studio build will mysteriously stop working after the next VS update AIUI). Is the plan to release this in a minor/patch/non-major update to VS?

**Comment by heaths** [comment]
This thread is only for _vswhere_. Visual Studio itself really isn't changing. I'm merely exposing information from Visual Studio and using it in _vswhere_ to fulfill this request. And while I could bump the major version of _vswhere_, see a bit above for why I don't think it's really necessary (w.r.t. NuGet's basic support for semvers). I'm not opposed to bumping this to v2, however. I just don't think it would really make a difference since NuGet defaults to "get the highest version".

**Comment by heaths** [comment]
...specifically this comment above: https://github.com/Microsoft/vswhere/issues/79#issuecomment-310508744

**Comment by gibfahn** [comment]
>This thread is only for vswhere. Visual Studio itself really isn't changing.

But vswhere is bundled with Visual Studio right? So updating Visual Studio updates your vswhere.

Anyway, if it's not going to make a difference then 🤷‍♂️ , although I guess it might be worth bumping so that if people see that vswhere got updated from `1.0.x` to `2.0.x` then that might give them a clue that reading the release notes would be a good idea.
