### ISSUE TITLE
vswhere returns Preview version even without the -prerelease switch

### ISSUE THREAD

**Issue by thomaslevesque** [Microsoft/vswhere#82]
I updated vswhere to 2.0.2 because I needed the new behavior described in the help message:

    -prerelease    Also searches prereleases. By default, only releases are searched.

But it doesn't work as described. It always returns the 15.3 Preview version, which I want to filter out. How can I get the path for the latest stable version?

**Comment by heaths** [comment]
See https://blogs.msdn.microsoft.com/heaths/2017/06/24/vswhere-version-2-0-released/

Are you using query API version 1.11.2290 or newer, as reported in the logo printed by _vswhere_?

**Comment by thomaslevesque** [comment]
It says "query version 1.11.2273.21075". How do I use the newer API version? The blog post says:

> This new query API will be released in Visual Studio 2017 version 15.3.

I have VS2017 15.3 preview 3 installed (VisualStudioPreview/15.3.0-pre.3.0+26621.2), so shouldn't it use the newer API?

**Comment by heaths** [comment]
Visual Studio 2017 version 15.3 Preview 4 will contain the newer query API. Its version (like the installer version, with which it's built) are distinct from typical Visual Studio file versions.

Once you can update to preview 4, if this still repros please reopen.

**Comment by thomaslevesque** [comment]
OK, thanks.
