### ISSUE TITLE
Clarification on parameter -version

### ISSUE THREAD

**Issue by steamonimo** [Microsoft/vswhere#86]
The range of the parameter -version can be given as follows -version A,B. Here the filter seems to include all installations with a version >= A and < B.

The query for Version 15 only must then be formulated as -version 15,16 and not -version 15,15. Is that correct?

In my opinion <= B would have been more logical from the perspective of querying a range. But others might already rely on this specific filtering behaviour.

**Comment by heaths** [comment]
The syntax is the same as for NuGet packages VSIXes, and requires usage of square brackets and parenthesis. I you wanted `15.0 <= x < 16`, you'd type:
```
-version "[15.0, 16.0)"
```
More information on the format is available [here](https://msdn.microsoft.com/en-us/library/ee943167.aspx) and [here](https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#version-ranges). We use the same version range internally for our dependency graph and VSIX v3 formats.

I will add a link in the wiki to that documentation.
