### ISSUE TITLE
-legacy does not list all installed versions

### ISSUE THREAD

**Issue by zanseb** [Microsoft/vswhere#89]
I am trying to find the installation path of Visual Studio 2008.
I get following output by invoking `vswhere.exe -legacy`:
```
instanceId: VisualStudio.14.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 14.0\
installationVersion: 14.0

instanceId: VisualStudio.12.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 12.0\
installationVersion: 12.0

instanceId: VisualStudio.11.0
installationPath: C:\Program Files (x86)\Microsoft Visual Studio 11.0\
installationVersion: 11.0
```

Unfortunately VisualStudio.9.0 is missing altough it is installed on my machine.

**Comment by zanseb** [comment]
The problem could be in `InstanceSelector.cpp`. The version 9.0 is not listed in the versions array (https://github.com/Microsoft/vswhere/blob/c0952830ccfc109e9a25917201094c299dede835/src/vswhere.lib/InstanceSelector.cpp#L125). Would it be possible to add it?

**Comment by heaths** [comment]
Visual Studio 2008 is no longer supported, and so was not included in _vswhere_.
