### ISSUE TITLE
Invalid JSON output with CP932 encoding

### ISSUE THREAD

**Issue by vector-of-bool** [Microsoft/vswhere#92]
Got a [bug report on my own project](https://github.com/vector-of-bool/vscode-cmake-tools/issues/220) regarding invalid JSON. Is vswhere generating invalid json? Or do I need to set the environment properly to get valid output?

**Comment by heaths** [comment]
Please see https://github.com/Microsoft/vswhere/wiki/Encoding for encoding issues. The console code page needs to be set correctly and the LCID that dictates the display name and description must work with the selected console code page.

**Comment by vector-of-bool** [comment]
D'oh! Thanks for the info.
