### ISSUE TITLE
Bettre qualify the Nuget id

### ISSUE THREAD

**Issue by zosrothko** [Microsoft/vswhere#93]
Hi

The <id> of the wshere nuget package is set to    <id>vswhere</id>. This is IMO not enough qualified as suggedted by the  [NuGet documentation](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#choosing-a-unique-package-identifier-and-setting-the-version-number). Thus I would suggest to change this id to something like ```
<id>Microsoft.VisualStudio.Locator</id> ``` so that the NuGet.org namespace be not overpolluted by single id.

**Comment by heaths** [comment]
The nuget package is also used for http://chocolatey.org and as the official distribution should not be qualified. It would also be a breaking change.

**Comment by zosrothko** [comment]
Chocolatey is not officially endorsed by Microsoft while NuGet IS the chossen package distribution management chossen by the Visual Studio team. So I would like that the Nuget id for vswhere follow the NuGet way

**Comment by heaths** [comment]
Other groups are welcome to publish vswhere variants but they would nonetheless be unofficial distributions. They are **not** precluded from publishing packages like _Contoso_.vswhere regardless.

Namespaces are recommended but not required, and as this would be a breaking change I'll not be making it.
