### ISSUE TITLE
Support for older versions

### ISSUE THREAD

**Issue by am11** [Microsoft/vswhere#94]
A lot of software would benefit from for it, if the utility provides backward compatibility for older version of VS. For example, the following PowerShell script covers some basic use-cases:

<details> 
  <summary>Click to expand PS script</summary> 

```powershell
function Get-VisualStudioVersionAndPath
{
  [CmdletBinding()]
  [Alias("gvsvp")]
  PARAM()
  process
  {
    foreach($v in @("15.0", "14.0", "12.0", "11.0", "10.0"))
    {
      try
      {
        $path = (gp "HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\SxS\VS7" -Name $v -EA Stop).$v
        return @($v, $path)
      }
      catch { <# ignore #> }
    }

    throw [System.InvalidOperationException] "Couldn't find suitable version of Visual Studio!"
  }
}

# usage (throws)
$VSVersion,$VSPath = Get-VisualStudioVersionAndPath
# or compactly
$vsver,$vsp = gsvp

# usage (no-throw)
$VSVersion,$VSPath = Get-VisualStudioVersionAndPath -ErrorAction SilentlyContinue
# or compactly
$vsver,$vsp = gsvp -ea 0
```

</details>
<br />

There are many scripts laying around on the internet to perform similar operations; finding VS version/path, finding MSBuild version/path, Windows SDK version/path etc. Would be super cool, if this utility masters some more use cases completely, so we at the downstream solely rely on one and only nuget package (`nuget install vswhere -o . -ex && vswhere\tools\vswhere -help`).

**Comment by heaths** [comment]
As noted in the wiki and several other issues, the multi-instancing of VS does not lend itself to a single registry location. This utility - built on the query APIs that other utilities can use (see also https://github.com/Microsoft/vssetup.powershell) - is designed to find an appropriate version. vswhere also supports versions 10.0 and newer. You can see example scripts in the wiki, and community members have built several tools and scripts atop vswhere as well.
