### ISSUE TITLE
What possible format of the directory name for installed MSBuild tools

### ISSUE THREAD

**Issue by 3F** [Microsoft/vswhere#95]
https://github.com/3F/hMSBuild/issues/3

So for clarify, 
What possible format of versions for this directory - `\{major}.0\` or it may be like `\{major}.{minor}\` ? some other ?

**Comment by heaths** [comment]
To date it's _major_.0, but you'd have to ask the @Microsoft/msbuild-maintainers team what their future plans are. They own their content.

**Comment by rainersigwald** [comment]
Replied over in 3F/hMSBuild#3. Briefly, for the foreseeable future major.0 should be fine.

**Comment by 3F** [comment]
thanks again :)
