### ISSUE TITLE
Return location of Visual Studio settings file

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vswhere#96]
With Visual Studio starting from version 15.3 using a [installation specific location](https://docs.microsoft.com/en-us/visualstudio/ide/synchronized-settings-in-visual-studio#side-by-side-synchronized-settings) for its settings file, it would be nice if vswhere could also return the location of the settings file used by a Visual Studio installation.

**Comment by heaths** [comment]
As previously detailed, _vswhere_ is independent of specific VS settings and can be used for products like Build Tools 2017, Remote Tools 2017, etc. We do not store, know about, or otherwise expose product-specific settings in the query API that _vswhere_ uses.
