### ISSUE TITLE
Add support to find all versions of visual studio 

### ISSUE THREAD

**Issue by clmcgrath** [Microsoft/vswhere#97]
Can this be modified to find previous versions of visual studio 
while the functionality is useful for finding 2017 we have a lot of legacy projects with dependencies as early as 2010 

.\vswhere.exe -version "[11.0,16.0)"

only returns  2017 skus

**Comment by heaths** [comment]
_vswhere_ already supports finding the installation path for Visual Studio 2010 and has for a while. If you're not seeing that behavior, please update to a newer version of _vswhere_. You also need to pass `-legacy` as documented in the `-h` usage information. But `-version` will not work without Visual Studio 2017 installed. See issue #91 for details.

**Comment by clmcgrath** [comment]
noted , ya i have  the latest now  and i am seeing the legacy option now
