### ISSUE TITLE
vswhere does not locate Visual Studio Test Agent 2017

### ISSUE THREAD

**Issue by cmenzi** [Microsoft/vswhere#98]
In order to execute code coverage the Test Agent 2017 is needed, but vswhere does not list this installation.

But it's installed:

<img width="346" alt="vs2017" src="https://user-images.githubusercontent.com/1763806/29704115-ac3f8558-8978-11e7-802c-a331de614302.PNG">

Any suggestions?

**Comment by heaths** [comment]
As documented, _vswhere_ by default finds Community, Professional, and Enterprise. If you want to find a different, specific product pass `-product <product ID>` or just pass `-product *` to find all products.
